; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 193
; Schema: 0
OpCapability Shader
OpCapability StorageBufferArrayDynamicIndexing
OpCapability RawAccessChainsNV
OpExtension "SPV_NV_raw_access_chains"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %14
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %32 "ByteAddressMask"
OpName %30 "index"
OpName %31 "stride"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 0
OpDecorate %14 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpConstant %5 2
%9 = OpTypeArray %7 %8
%10 = OpTypePointer StorageBuffer %9
%11 = OpVariable %10 StorageBuffer
%12 = OpTypeVector %5 3
%13 = OpTypePointer Input %12
%14 = OpVariable %13 Input
%15 = OpTypePointer Input %5
%17 = OpConstant %5 0
%20 = OpConstant %5 6
%21 = OpTypePointer StorageBuffer %7
%23 = OpTypeFloat 32
%24 = OpTypeVector %23 4
%25 = OpTypePointer StorageBuffer %24
%28 = OpConstant %5 4
%29 = OpTypeFunction %5 %5 %5
%35 = OpConstant %5 4294967295
%39 = OpConstant %5 16
%49 = OpConstant %5 1
%65 = OpConstant %5 48
%69 = OpConstant %5 3
%77 = OpConstant %23 4
%103 = OpConstant %5 32
%115 = OpConstant %5 80
%119 = OpConstant %5 5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %191
%191 = OpLabel
%16 = OpAccessChain %15 %14 %17
%18 = OpLoad %5 %16
%19 = OpShiftLeftLogical %5 %18 %20
%22 = OpAccessChain %21 %11 %17
%27 = OpIMul %5 %18 %28
%38 = OpFunctionCall %5 %32 %27 %39
%26 = OpRawAccessChainNV %25 %22 %39 %38 %17 RobustnessPerElementNV
%40 = OpLoad %24 %26 Aligned 16
%41 = OpCompositeExtract %23 %40 0
%42 = OpCompositeExtract %23 %40 1
%43 = OpCompositeExtract %23 %40 2
%44 = OpCompositeExtract %23 %40 3
%45 = OpBitwiseOr %5 %19 %39
%47 = OpIMul %5 %18 %28
%48 = OpIAdd %5 %47 %49
%50 = OpFunctionCall %5 %32 %48 %39
%46 = OpRawAccessChainNV %25 %22 %39 %50 %17 RobustnessPerElementNV
%51 = OpLoad %24 %46 Aligned 16
%52 = OpCompositeExtract %23 %51 0
%53 = OpCompositeExtract %23 %51 1
%54 = OpCompositeExtract %23 %51 2
%55 = OpCompositeExtract %23 %51 3
%56 = OpIAdd %5 %45 %39
%58 = OpShiftRightLogical %5 %56 %28
%57 = OpRawAccessChainNV %25 %22 %39 %58 %17 RobustnessPerElementNV
%59 = OpLoad %24 %57 Aligned 16
%60 = OpCompositeExtract %23 %59 0
%61 = OpCompositeExtract %23 %59 1
%62 = OpCompositeExtract %23 %59 2
%63 = OpCompositeExtract %23 %59 3
%64 = OpBitwiseOr %5 %19 %65
%67 = OpIMul %5 %18 %28
%68 = OpIAdd %5 %67 %69
%70 = OpFunctionCall %5 %32 %68 %39
%66 = OpRawAccessChainNV %25 %22 %39 %70 %17 RobustnessPerElementNV
%71 = OpLoad %24 %66 Aligned 16
%72 = OpCompositeExtract %23 %71 0
%73 = OpCompositeExtract %23 %71 1
%74 = OpCompositeExtract %23 %71 2
%75 = OpCompositeExtract %23 %71 3
%76 = OpFAdd %23 %41 %77
%78 = OpFAdd %23 %42 %77
%79 = OpFAdd %23 %43 %77
%80 = OpFAdd %23 %44 %77
%81 = OpFAdd %23 %52 %77
%82 = OpFAdd %23 %53 %77
%83 = OpFAdd %23 %54 %77
%84 = OpFAdd %23 %55 %77
%85 = OpFAdd %23 %60 %77
%86 = OpFAdd %23 %61 %77
%87 = OpFAdd %23 %62 %77
%88 = OpFAdd %23 %63 %77
%89 = OpFAdd %23 %72 %77
%90 = OpFAdd %23 %73 %77
%91 = OpFAdd %23 %74 %77
%92 = OpFAdd %23 %75 %77
%94 = OpIMul %5 %18 %28
%95 = OpFunctionCall %5 %32 %94 %39
%93 = OpRawAccessChainNV %25 %22 %39 %95 %17 RobustnessPerElementNV
%96 = OpCompositeConstruct %24 %76 %81 %85 %89
OpStore %93 %96 Aligned 16
%98 = OpIMul %5 %18 %28
%99 = OpIAdd %5 %98 %49
%100 = OpFunctionCall %5 %32 %99 %39
%97 = OpRawAccessChainNV %25 %22 %39 %100 %17 RobustnessPerElementNV
%101 = OpCompositeConstruct %24 %78 %82 %86 %90
OpStore %97 %101 Aligned 16
%102 = OpBitwiseOr %5 %19 %103
%105 = OpIMul %5 %18 %28
%106 = OpIAdd %5 %105 %8
%107 = OpFunctionCall %5 %32 %106 %39
%104 = OpRawAccessChainNV %25 %22 %39 %107 %17 RobustnessPerElementNV
%108 = OpCompositeConstruct %24 %79 %83 %87 %91
OpStore %104 %108 Aligned 16
%110 = OpIMul %5 %18 %28
%111 = OpIAdd %5 %110 %69
%112 = OpFunctionCall %5 %32 %111 %39
%109 = OpRawAccessChainNV %25 %22 %39 %112 %17 RobustnessPerElementNV
%113 = OpCompositeConstruct %24 %80 %84 %88 %92
OpStore %109 %113 Aligned 16
%114 = OpIMul %5 %18 %115
%116 = OpAccessChain %21 %11 %49
%118 = OpIMul %5 %18 %119
%120 = OpFunctionCall %5 %32 %118 %39
%117 = OpRawAccessChainNV %25 %116 %39 %120 %17 RobustnessPerElementNV
%121 = OpLoad %24 %117 Aligned 16
%122 = OpCompositeExtract %23 %121 0
%123 = OpCompositeExtract %23 %121 1
%124 = OpCompositeExtract %23 %121 2
%125 = OpCompositeExtract %23 %121 3
%126 = OpIAdd %5 %114 %39
%128 = OpIMul %5 %18 %119
%129 = OpIAdd %5 %128 %49
%130 = OpFunctionCall %5 %32 %129 %39
%127 = OpRawAccessChainNV %25 %116 %39 %130 %17 RobustnessPerElementNV
%131 = OpLoad %24 %127 Aligned 16
%132 = OpCompositeExtract %23 %131 0
%133 = OpCompositeExtract %23 %131 1
%134 = OpCompositeExtract %23 %131 2
%135 = OpCompositeExtract %23 %131 3
%136 = OpIAdd %5 %114 %103
%138 = OpIMul %5 %18 %119
%139 = OpIAdd %5 %138 %8
%140 = OpFunctionCall %5 %32 %139 %39
%137 = OpRawAccessChainNV %25 %116 %39 %140 %17 RobustnessPerElementNV
%141 = OpLoad %24 %137 Aligned 16
%142 = OpCompositeExtract %23 %141 0
%143 = OpCompositeExtract %23 %141 1
%144 = OpCompositeExtract %23 %141 2
%145 = OpCompositeExtract %23 %141 3
%146 = OpIAdd %5 %114 %65
%148 = OpIMul %5 %18 %119
%149 = OpIAdd %5 %148 %69
%150 = OpFunctionCall %5 %32 %149 %39
%147 = OpRawAccessChainNV %25 %116 %39 %150 %17 RobustnessPerElementNV
%151 = OpLoad %24 %147 Aligned 16
%152 = OpCompositeExtract %23 %151 0
%153 = OpCompositeExtract %23 %151 1
%154 = OpCompositeExtract %23 %151 2
%155 = OpCompositeExtract %23 %151 3
%156 = OpFAdd %23 %122 %77
%157 = OpFAdd %23 %123 %77
%158 = OpFAdd %23 %124 %77
%159 = OpFAdd %23 %125 %77
%160 = OpFAdd %23 %132 %77
%161 = OpFAdd %23 %133 %77
%162 = OpFAdd %23 %134 %77
%163 = OpFAdd %23 %135 %77
%164 = OpFAdd %23 %142 %77
%165 = OpFAdd %23 %143 %77
%166 = OpFAdd %23 %144 %77
%167 = OpFAdd %23 %145 %77
%168 = OpFAdd %23 %152 %77
%169 = OpFAdd %23 %153 %77
%170 = OpFAdd %23 %154 %77
%171 = OpFAdd %23 %155 %77
%173 = OpIMul %5 %18 %119
%174 = OpFunctionCall %5 %32 %173 %39
%172 = OpRawAccessChainNV %25 %116 %39 %174 %17 RobustnessPerElementNV
%175 = OpCompositeConstruct %24 %156 %160 %164 %168
OpStore %172 %175 Aligned 16
%177 = OpIMul %5 %18 %119
%178 = OpIAdd %5 %177 %49
%179 = OpFunctionCall %5 %32 %178 %39
%176 = OpRawAccessChainNV %25 %116 %39 %179 %17 RobustnessPerElementNV
%180 = OpCompositeConstruct %24 %157 %161 %165 %169
OpStore %176 %180 Aligned 16
%182 = OpIMul %5 %18 %119
%183 = OpIAdd %5 %182 %8
%184 = OpFunctionCall %5 %32 %183 %39
%181 = OpRawAccessChainNV %25 %116 %39 %184 %17 RobustnessPerElementNV
%185 = OpCompositeConstruct %24 %158 %162 %166 %170
OpStore %181 %185 Aligned 16
%187 = OpIMul %5 %18 %119
%188 = OpIAdd %5 %187 %69
%189 = OpFunctionCall %5 %32 %188 %39
%186 = OpRawAccessChainNV %25 %116 %39 %189 %17 RobustnessPerElementNV
%190 = OpCompositeConstruct %24 %159 %163 %167 %171
OpStore %186 %190 Aligned 16
OpReturn
OpFunctionEnd
%32 = OpFunction %5 None %29
%30 = OpFunctionParameter %5
%31 = OpFunctionParameter %5
%33 = OpLabel
%34 = OpUDiv %5 %35 %31
%36 = OpBitwiseAnd %5 %30 %34
OpReturnValue %36
OpFunctionEnd

