#version 460
#extension GL_KHR_shader_subgroup_quad : require
#extension GL_EXT_samplerless_texture_functions : require
layout(local_size_x = 8, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) writeonly buffer SSBO
{
    uvec4 _m0[];
} _17;

layout(set = 0, binding = 0) uniform texture1D _8;
layout(set = 0, binding = 1) uniform texture1DArray _11;
layout(set = 0, binding = 0) uniform sampler _20;

void main()
{
    float _28 = float(gl_GlobalInvocationID.x);
    float _29 = _28 * 0.00999999977648258209228515625;
    float _31 = _28 * 0.100000001490116119384765625;
    float _55 = exp2(_31);
    float _80 = exp2(_31);
    _17._m0[gl_GlobalInvocationID.x * 2u] = uvec4(floatBitsToUint(textureGrad(sampler1D(_8, _20), _29, _29 - subgroupQuadSwapHorizontal(_29), _29 - subgroupQuadSwapVertical(_29)).x), floatBitsToUint(textureGrad(sampler1D(_8, _20), _29, (_29 - subgroupQuadSwapHorizontal(_29)) * _55, (_29 - subgroupQuadSwapVertical(_29)) * _55).x), floatBitsToUint(textureGrad(sampler1DArray(_11, _20), vec2(_29, 1.0), _29 - subgroupQuadSwapHorizontal(_29), _29 - subgroupQuadSwapVertical(_29)).x), floatBitsToUint(textureGrad(sampler1DArray(_11, _20), vec2(_29, 1.0), (_29 - subgroupQuadSwapHorizontal(_29)) * _80, (_29 - subgroupQuadSwapVertical(_29)) * _80).x));
    float _105 = float(textureSize(_8, 0));
    float _106 = (subgroupQuadSwapHorizontal(_29) - _29) * _105;
    float _107 = (subgroupQuadSwapVertical(_29) - _29) * _105;
    float _126 = float(textureSize(_11, 0).x);
    float _127 = (subgroupQuadSwapHorizontal(_29) - _29) * _126;
    float _128 = (subgroupQuadSwapVertical(_29) - _29) * _126;
    _17._m0[(gl_GlobalInvocationID.x * 2u) + 1u] = uvec4(floatBitsToUint(clamp(log2(max(_106 * _106, _107 * _107)) * 0.5, -128.0, 128.0)), floatBitsToUint(clamp(log2(max(_127 * _127, _128 * _128)) * 0.5, -128.0, 128.0)), floatBitsToUint(0.0), floatBitsToUint(0.0));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 146
; Schema: 0
OpCapability Shader
OpCapability Sampled1D
OpCapability ImageQuery
OpCapability GroupNonUniformQuad
%54 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %23
OpExecutionMode %3 LocalSize 8 1 1
OpName %3 "main"
OpName %15 "SSBO"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 1
OpDecorate %14 ArrayStride 16
OpMemberDecorate %15 0 Offset 0
OpDecorate %15 Block
OpDecorate %17 DescriptorSet 0
OpDecorate %17 Binding 0
OpDecorate %17 NonReadable
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 0
OpDecorate %23 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeFloat 32
%6 = OpTypeImage %5 1D 0 0 0 1 Unknown
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpTypeImage %5 1D 0 1 0 1 Unknown
%10 = OpTypePointer UniformConstant %9
%11 = OpVariable %10 UniformConstant
%12 = OpTypeInt 32 0
%13 = OpTypeVector %12 4
%14 = OpTypeRuntimeArray %13
%15 = OpTypeStruct %14
%16 = OpTypePointer StorageBuffer %15
%17 = OpVariable %16 StorageBuffer
%18 = OpTypeSampler
%19 = OpTypePointer UniformConstant %18
%20 = OpVariable %19 UniformConstant
%21 = OpTypeVector %12 3
%22 = OpTypePointer Input %21
%23 = OpVariable %22 Input
%24 = OpTypePointer Input %12
%26 = OpConstant %12 0
%30 = OpConstant %5 0.00999999978
%32 = OpConstant %5 0.100000001
%35 = OpTypeSampledImage %6
%37 = OpConstant %5 0
%38 = OpTypeVector %5 4
%40 = OpConstant %12 3
%42 = OpConstant %12 1
%62 = OpTypeSampledImage %9
%64 = OpConstant %5 1
%70 = OpTypeVector %5 2
%88 = OpConstant %12 2
%94 = OpTypePointer StorageBuffer %13
%98 = OpTypeInt 32 1
%104 = OpConstant %98 0
%113 = OpConstant %5 0.5
%115 = OpConstant %5 -128
%116 = OpConstant %5 128
%123 = OpTypeVector %98 2
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %144
%144 = OpLabel
%25 = OpAccessChain %24 %23 %26
%27 = OpLoad %12 %25
%28 = OpConvertUToF %5 %27
%29 = OpFMul %5 %28 %30
%31 = OpFMul %5 %28 %32
%33 = OpLoad %6 %8
%34 = OpLoad %18 %20
%36 = OpSampledImage %35 %33 %34
%39 = OpGroupNonUniformQuadSwap %5 %40 %29 %26
%41 = OpGroupNonUniformQuadSwap %5 %40 %29 %42
%43 = OpFSub %5 %29 %39
%44 = OpFSub %5 %29 %41
%45 = OpImageSampleExplicitLod %38 %36 %29 Grad %43 %44
%46 = OpCompositeExtract %5 %45 0
%47 = OpLoad %6 %8
%48 = OpLoad %18 %20
%49 = OpSampledImage %35 %47 %48
%50 = OpGroupNonUniformQuadSwap %5 %40 %29 %26
%51 = OpGroupNonUniformQuadSwap %5 %40 %29 %42
%52 = OpFSub %5 %29 %50
%53 = OpFSub %5 %29 %51
%55 = OpExtInst %5 %54 Exp2 %31
%56 = OpFMul %5 %52 %55
%57 = OpFMul %5 %53 %55
%58 = OpImageSampleExplicitLod %38 %49 %29 Grad %56 %57
%59 = OpCompositeExtract %5 %58 0
%60 = OpLoad %9 %11
%61 = OpLoad %18 %20
%63 = OpSampledImage %62 %60 %61
%65 = OpGroupNonUniformQuadSwap %5 %40 %29 %26
%66 = OpGroupNonUniformQuadSwap %5 %40 %29 %42
%67 = OpFSub %5 %29 %65
%68 = OpFSub %5 %29 %66
%71 = OpCompositeConstruct %70 %29 %64
%69 = OpImageSampleExplicitLod %38 %63 %71 Grad %67 %68
%72 = OpCompositeExtract %5 %69 0
%73 = OpLoad %9 %11
%74 = OpLoad %18 %20
%75 = OpSampledImage %62 %73 %74
%76 = OpGroupNonUniformQuadSwap %5 %40 %29 %26
%77 = OpGroupNonUniformQuadSwap %5 %40 %29 %42
%78 = OpFSub %5 %29 %76
%79 = OpFSub %5 %29 %77
%80 = OpExtInst %5 %54 Exp2 %31
%81 = OpFMul %5 %78 %80
%82 = OpFMul %5 %79 %80
%84 = OpCompositeConstruct %70 %29 %64
%83 = OpImageSampleExplicitLod %38 %75 %84 Grad %81 %82
%85 = OpCompositeExtract %5 %83 0
%86 = OpShiftLeftLogical %12 %27 %42
%87 = OpIMul %12 %27 %88
%89 = OpBitcast %12 %46
%90 = OpBitcast %12 %59
%91 = OpBitcast %12 %72
%92 = OpBitcast %12 %85
%93 = OpCompositeConstruct %13 %89 %90 %91 %92
%95 = OpAccessChain %94 %17 %26 %87
OpStore %95 %93
%96 = OpLoad %6 %8
%97 = OpLoad %18 %20
%99 = OpGroupNonUniformQuadSwap %5 %40 %29 %26
%100 = OpGroupNonUniformQuadSwap %5 %40 %29 %42
%101 = OpFSub %5 %99 %29
%102 = OpFSub %5 %100 %29
%103 = OpImageQuerySizeLod %98 %96 %104
%105 = OpConvertSToF %5 %103
%106 = OpFMul %5 %101 %105
%107 = OpFMul %5 %102 %105
%108 = OpFMul %5 %106 %106
%109 = OpFMul %5 %107 %107
%110 = OpExtInst %5 %54 FMax %108 %109
%111 = OpExtInst %5 %54 Log2 %110
%112 = OpFMul %5 %111 %113
%114 = OpExtInst %5 %54 FClamp %112 %115 %116
%117 = OpLoad %9 %11
%118 = OpLoad %18 %20
%119 = OpGroupNonUniformQuadSwap %5 %40 %29 %26
%120 = OpGroupNonUniformQuadSwap %5 %40 %29 %42
%121 = OpFSub %5 %119 %29
%122 = OpFSub %5 %120 %29
%124 = OpImageQuerySizeLod %123 %117 %104
%125 = OpCompositeExtract %98 %124 0
%126 = OpConvertSToF %5 %125
%127 = OpFMul %5 %121 %126
%128 = OpFMul %5 %122 %126
%129 = OpFMul %5 %127 %127
%130 = OpFMul %5 %128 %128
%131 = OpExtInst %5 %54 FMax %129 %130
%132 = OpExtInst %5 %54 Log2 %131
%133 = OpFMul %5 %132 %113
%134 = OpExtInst %5 %54 FClamp %133 %115 %116
%135 = OpBitwiseOr %12 %86 %42
%136 = OpIMul %12 %27 %88
%137 = OpIAdd %12 %136 %42
%138 = OpBitcast %12 %114
%139 = OpBitcast %12 %134
%140 = OpBitcast %12 %37
%141 = OpBitcast %12 %37
%142 = OpCompositeConstruct %13 %138 %139 %140 %141
%143 = OpAccessChain %94 %17 %26 %137
OpStore %143 %142
OpReturn
OpFunctionEnd
#endif
