; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 169
; Schema: 0
OpCapability Shader
OpCapability Int64
OpCapability LongVectorEXT
OpExtension "SPV_EXT_long_vector"
%42 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %9 %14 %19 %24
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %12 "SSBO"
OpName %17 "SSBO"
OpName %22 "SSBO"
OpDecorate %6 ArrayStride 8
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %11 ArrayStride 32
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Aliased
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonWritable
OpDecorate %14 Aliased
OpDecorate %16 ArrayStride 4
OpMemberDecorate %17 0 Offset 0
OpDecorate %17 Block
OpDecorate %21 ArrayStride 16
OpMemberDecorate %22 0 Offset 0
OpDecorate %22 Block
OpDecorate %19 DescriptorSet 0
OpDecorate %19 Binding 1
OpDecorate %19 NonReadable
OpDecorate %19 Aliased
OpDecorate %24 DescriptorSet 0
OpDecorate %24 Binding 1
OpDecorate %24 NonReadable
OpDecorate %24 Aliased
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 64 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 4
%11 = OpTypeRuntimeArray %10
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeInt 32 0
%16 = OpTypeRuntimeArray %15
%17 = OpTypeStruct %16
%18 = OpTypePointer StorageBuffer %17
%19 = OpVariable %18 StorageBuffer
%20 = OpTypeVector %15 4
%21 = OpTypeRuntimeArray %20
%22 = OpTypeStruct %21
%23 = OpTypePointer StorageBuffer %22
%24 = OpVariable %23 StorageBuffer
%25 = OpConstant %15 0
%26 = OpTypePointer StorageBuffer %5
%31 = OpConstant %15 1
%35 = OpConstant %15 2
%37 = OpTypeVector %5 3
%39 = OpTypePointer StorageBuffer %10
%43 = OpTypeVector %15 6
%45 = OpTypeVector %15 3
%50 = OpConstant %15 32
%51 = OpConstantComposite %45 %50 %50 %50
%56 = OpTypePointer StorageBuffer %15
%68 = OpTypeBool
%69 = OpTypeVector %68 3
%71 = OpConstant %15 4294967295
%72 = OpConstantComposite %45 %71 %71 %71
%74 = OpConstant %15 63
%75 = OpConstantComposite %45 %74 %74 %74
%80 = OpConstant %15 3
%91 = OpTypeInt 32 1
%92 = OpTypeVector %91 3
%94 = OpConstant %91 31
%95 = OpConstantComposite %92 %94 %94 %94
%96 = OpTypeVector %91 6
%110 = OpConstant %15 6
%119 = OpTypeVector %15 8
%125 = OpConstantComposite %20 %50 %50 %50 %50
%127 = OpTypePointer StorageBuffer %20
%135 = OpTypeVector %68 4
%137 = OpConstantComposite %20 %71 %71 %71 %71
%139 = OpConstantComposite %20 %74 %74 %74 %74
%144 = OpConstant %15 4
%148 = OpTypeVector %91 4
%150 = OpConstantComposite %148 %94 %94 %94 %94
%151 = OpTypeVector %91 8
%165 = OpConstant %15 5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %167
%167 = OpLabel
%27 = OpAccessChain %26 %9 %25 %25
%28 = OpLoad %5 %27
%30 = OpIAdd %15 %25 %31
%29 = OpAccessChain %26 %9 %25 %30
%32 = OpLoad %5 %29
%34 = OpIAdd %15 %25 %35
%33 = OpAccessChain %26 %9 %25 %34
%36 = OpLoad %5 %33
%38 = OpCompositeConstruct %37 %28 %32 %36
%40 = OpAccessChain %39 %14 %25 %31
%41 = OpLoad %10 %40
%44 = OpBitcast %43 %38
%46 = OpExtInst %43 %42 FindILsb %44
%47 = OpVectorShuffle %45 %46 %46 0 2 4
%48 = OpVectorShuffle %45 %46 %46 1 3 5
%49 = OpBitwiseOr %45 %48 %51
%52 = OpExtInst %45 %42 UMin %47 %49
%53 = OpCompositeExtract %15 %52 0
%54 = OpCompositeExtract %15 %52 1
%55 = OpCompositeExtract %15 %52 2
%57 = OpAccessChain %56 %19 %25 %25
OpStore %57 %53
%59 = OpIAdd %15 %25 %31
%58 = OpAccessChain %56 %19 %25 %59
OpStore %58 %54
%61 = OpIAdd %15 %25 %35
%60 = OpAccessChain %56 %19 %25 %61
OpStore %60 %55
%62 = OpBitcast %43 %38
%63 = OpExtInst %43 %42 FindUMsb %62
%64 = OpVectorShuffle %45 %63 %63 0 2 4
%65 = OpVectorShuffle %45 %63 %63 1 3 5
%66 = OpBitwiseOr %45 %65 %51
%67 = OpExtInst %45 %42 SMax %64 %66
%70 = OpIEqual %69 %67 %72
%73 = OpISub %45 %75 %67
%76 = OpSelect %45 %70 %72 %73
%77 = OpISub %45 %75 %76
%78 = OpIEqual %69 %76 %72
%79 = OpSelect %45 %78 %72 %77
%81 = OpCompositeExtract %15 %79 0
%82 = OpCompositeExtract %15 %79 1
%83 = OpCompositeExtract %15 %79 2
%84 = OpAccessChain %56 %19 %25 %80
OpStore %84 %81
%86 = OpIAdd %15 %80 %31
%85 = OpAccessChain %56 %19 %25 %86
OpStore %85 %82
%88 = OpIAdd %15 %80 %35
%87 = OpAccessChain %56 %19 %25 %88
OpStore %87 %83
%89 = OpBitcast %43 %38
%90 = OpVectorShuffle %45 %89 %89 1 3 5
%93 = OpShiftRightArithmetic %92 %90 %95
%97 = OpVectorShuffle %96 %93 %93 0 0 1 1 2 2
%98 = OpBitwiseXor %43 %89 %97
%99 = OpExtInst %43 %42 FindUMsb %98
%100 = OpVectorShuffle %45 %99 %99 0 2 4
%101 = OpVectorShuffle %45 %99 %99 1 3 5
%102 = OpBitwiseOr %45 %101 %51
%103 = OpExtInst %45 %42 SMax %100 %102
%104 = OpIEqual %69 %103 %72
%105 = OpISub %45 %75 %103
%106 = OpSelect %45 %104 %72 %105
%107 = OpISub %45 %75 %106
%108 = OpIEqual %69 %106 %72
%109 = OpSelect %45 %108 %72 %107
%111 = OpCompositeExtract %15 %109 0
%112 = OpCompositeExtract %15 %109 1
%113 = OpCompositeExtract %15 %109 2
%114 = OpAccessChain %56 %19 %25 %110
OpStore %114 %111
%116 = OpIAdd %15 %110 %31
%115 = OpAccessChain %56 %19 %25 %116
OpStore %115 %112
%118 = OpIAdd %15 %110 %35
%117 = OpAccessChain %56 %19 %25 %118
OpStore %117 %113
%120 = OpBitcast %119 %41
%121 = OpExtInst %119 %42 FindILsb %120
%122 = OpVectorShuffle %20 %121 %121 0 2 4 6
%123 = OpVectorShuffle %20 %121 %121 1 3 5 7
%124 = OpBitwiseOr %20 %123 %125
%126 = OpExtInst %20 %42 UMin %122 %124
%128 = OpAccessChain %127 %24 %25 %80
OpStore %128 %126
%129 = OpBitcast %119 %41
%130 = OpExtInst %119 %42 FindUMsb %129
%131 = OpVectorShuffle %20 %130 %130 0 2 4 6
%132 = OpVectorShuffle %20 %130 %130 1 3 5 7
%133 = OpBitwiseOr %20 %132 %125
%134 = OpExtInst %20 %42 SMax %131 %133
%136 = OpIEqual %135 %134 %137
%138 = OpISub %20 %139 %134
%140 = OpSelect %20 %136 %137 %138
%141 = OpISub %20 %139 %140
%142 = OpIEqual %135 %140 %137
%143 = OpSelect %20 %142 %137 %141
%145 = OpAccessChain %127 %24 %25 %144
OpStore %145 %143
%146 = OpBitcast %119 %41
%147 = OpVectorShuffle %20 %146 %146 1 3 5 7
%149 = OpShiftRightArithmetic %148 %147 %150
%152 = OpVectorShuffle %151 %149 %149 0 0 1 1 2 2 3 3
%153 = OpBitwiseXor %119 %146 %152
%154 = OpExtInst %119 %42 FindUMsb %153
%155 = OpVectorShuffle %20 %154 %154 0 2 4 6
%156 = OpVectorShuffle %20 %154 %154 1 3 5 7
%157 = OpBitwiseOr %20 %156 %125
%158 = OpExtInst %20 %42 SMax %155 %157
%159 = OpIEqual %135 %158 %137
%160 = OpISub %20 %139 %158
%161 = OpSelect %20 %159 %137 %160
%162 = OpISub %20 %139 %161
%163 = OpIEqual %135 %161 %137
%164 = OpSelect %20 %163 %137 %162
%166 = OpAccessChain %127 %24 %25 %165
OpStore %166 %164
OpReturn
OpFunctionEnd

