#version 460
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_quad : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, r32ui) uniform writeonly uimageBuffer _8;

void main()
{
    uint _22 = (gl_WorkGroupID.x * 31u) + 7u;
    uint _31 = gl_GlobalInvocationID.x * 4u;
    imageStore(_8, int(_31), uvec4(_22));
    imageStore(_8, int(_31 + 1u), uvec4(_22));
    imageStore(_8, int(_31 + 2u), uvec4(subgroupBroadcast(gl_GlobalInvocationID.x, 0u)));
    imageStore(_8, int(_31 + 3u), uvec4(subgroupQuadSwapHorizontal(gl_GlobalInvocationID.x)));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 44
; Schema: 0
OpCapability Shader
OpCapability ImageBuffer
OpCapability GroupNonUniform
OpCapability GroupNonUniformBallot
OpCapability GroupNonUniformQuad
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %12 %17 %24
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %8 NonReadable
OpDecorate %12 BuiltIn GlobalInvocationId
OpDecorate %17 BuiltIn WorkgroupId
OpDecorate %24 BuiltIn SubgroupLocalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%10 = OpTypeVector %5 3
%11 = OpTypePointer Input %10
%12 = OpVariable %11 Input
%13 = OpTypePointer Input %5
%15 = OpConstant %5 0
%17 = OpVariable %11 Input
%21 = OpConstant %5 31
%23 = OpConstant %5 7
%24 = OpVariable %13 Input
%27 = OpConstant %5 1
%29 = OpConstant %5 3
%32 = OpConstant %5 4
%33 = OpTypeVector %5 4
%39 = OpConstant %5 2
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %42
%42 = OpLabel
%9 = OpLoad %6 %8
%14 = OpAccessChain %13 %12 %15
%16 = OpLoad %5 %14
%18 = OpAccessChain %13 %17 %15
%19 = OpLoad %5 %18
%20 = OpIMul %5 %19 %21
%22 = OpIAdd %5 %20 %23
%25 = OpLoad %5 %24
%26 = OpBitwiseXor %5 %25 %27
%28 = OpGroupNonUniformBroadcast %5 %29 %16 %15
%30 = OpGroupNonUniformQuadSwap %5 %29 %16 %15
%31 = OpIMul %5 %16 %32
%34 = OpCompositeConstruct %33 %22 %22 %22 %22
OpImageWrite %9 %31 %34
%35 = OpCompositeConstruct %33 %22 %22 %22 %22
%36 = OpIAdd %5 %31 %27
OpImageWrite %9 %36 %35
%37 = OpCompositeConstruct %33 %28 %28 %28 %28
%38 = OpIAdd %5 %31 %39
OpImageWrite %9 %38 %37
%40 = OpCompositeConstruct %33 %30 %30 %30 %30
%41 = OpIAdd %5 %31 %29
OpImageWrite %9 %41 %40
OpReturn
OpFunctionEnd
#endif
