#version 460
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_shuffle : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, r32ui) uniform writeonly uimageBuffer _8;

void main()
{
    uint _15;
    _15 = gl_SubgroupInvocationID + 1u;
    uint _17;
    uint _20;
    uint _22;
    for (;;)
    {
        _17 = subgroupAdd(1u);
        _20 = subgroupBroadcastFirst(gl_SubgroupInvocationID);
        _22 = subgroupShuffle(_17, gl_SubgroupInvocationID);
        uint _16 = _15 + 4294967295u;
        if (_16 == 0u)
        {
            break;
        }
        else
        {
            _15 = _16;
        }
    }
    uint _34 = _17 + 7u;
    uint _39 = gl_GlobalInvocationID.x * 8u;
    imageStore(_8, int(_39), uvec4(subgroupBroadcast(_17, 0u)));
    imageStore(_8, int(_39 + 1u), uvec4(subgroupBroadcastFirst(_17)));
    imageStore(_8, int(_39 + 2u), uvec4(subgroupBroadcast(_34, 0u)));
    imageStore(_8, int(_39 + 3u), uvec4(subgroupBroadcastFirst(_34)));
    uint _57 = (gl_GlobalInvocationID.x * 8u) + 4u;
    imageStore(_8, int(_57), uvec4(subgroupBroadcastFirst(_20)));
    imageStore(_8, int(_57 + 1u), uvec4(subgroupBroadcast(_20, 0u)));
    imageStore(_8, int(_57 + 2u), uvec4(subgroupBroadcastFirst(_22)));
    imageStore(_8, int(_57 + 3u), uvec4(subgroupBroadcast(_22, 0u)));
}


#if 0
// SPIR-V disassembly
// HeuristicWaveSize(32)
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 69
; Schema: 0
OpCapability Shader
OpCapability ImageBuffer
OpCapability GroupNonUniform
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpCapability GroupNonUniformShuffle
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %11 %29
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %8 NonReadable
OpDecorate %11 BuiltIn SubgroupLocalInvocationId
OpDecorate %29 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%10 = OpTypePointer Input %5
%11 = OpVariable %10 Input
%14 = OpConstant %5 1
%18 = OpConstant %5 3
%23 = OpConstant %5 4294967295
%24 = OpTypeBool
%26 = OpConstant %5 0
%27 = OpTypeVector %5 3
%28 = OpTypePointer Input %27
%29 = OpVariable %28 Input
%35 = OpConstant %5 7
%40 = OpConstant %5 8
%41 = OpTypeVector %5 4
%47 = OpConstant %5 2
%56 = OpConstant %5 4
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %65
%65 = OpLabel
%9 = OpLoad %6 %8
%12 = OpLoad %5 %11
%13 = OpIAdd %5 %12 %14
OpBranch %66
%66 = OpLabel
%15 = OpPhi %5 %13 %65 %16 %66
%17 = OpGroupNonUniformIAdd %5 %18 Reduce %14
%19 = OpLoad %5 %11
%20 = OpGroupNonUniformBroadcastFirst %5 %18 %19
%21 = OpLoad %5 %11
%22 = OpGroupNonUniformShuffle %5 %18 %17 %21
%16 = OpIAdd %5 %15 %23
%25 = OpIEqual %24 %16 %26
OpLoopMerge %67 %66 None
OpBranchConditional %25 %67 %66
%67 = OpLabel
%30 = OpAccessChain %10 %29 %26
%31 = OpLoad %5 %30
%32 = OpGroupNonUniformBroadcast %5 %18 %17 %26
%33 = OpGroupNonUniformBroadcastFirst %5 %18 %17
%34 = OpIAdd %5 %17 %35
%36 = OpGroupNonUniformBroadcast %5 %18 %34 %26
%37 = OpGroupNonUniformBroadcastFirst %5 %18 %34
%38 = OpShiftLeftLogical %5 %31 %14
%39 = OpIMul %5 %31 %40
%42 = OpCompositeConstruct %41 %32 %32 %32 %32
OpImageWrite %9 %39 %42
%43 = OpCompositeConstruct %41 %33 %33 %33 %33
%44 = OpIAdd %5 %39 %14
OpImageWrite %9 %44 %43
%45 = OpCompositeConstruct %41 %36 %36 %36 %36
%46 = OpIAdd %5 %39 %47
OpImageWrite %9 %46 %45
%48 = OpCompositeConstruct %41 %37 %37 %37 %37
%49 = OpIAdd %5 %39 %18
OpImageWrite %9 %49 %48
%50 = OpGroupNonUniformBroadcastFirst %5 %18 %20
%51 = OpGroupNonUniformBroadcast %5 %18 %20 %26
%52 = OpGroupNonUniformBroadcastFirst %5 %18 %22
%53 = OpGroupNonUniformBroadcast %5 %18 %22 %26
%54 = OpBitwiseOr %5 %38 %14
%55 = OpIMul %5 %31 %40
%57 = OpIAdd %5 %55 %56
%58 = OpCompositeConstruct %41 %50 %50 %50 %50
OpImageWrite %9 %57 %58
%59 = OpCompositeConstruct %41 %51 %51 %51 %51
%60 = OpIAdd %5 %57 %14
OpImageWrite %9 %60 %59
%61 = OpCompositeConstruct %41 %52 %52 %52 %52
%62 = OpIAdd %5 %57 %47
OpImageWrite %9 %62 %61
%63 = OpCompositeConstruct %41 %53 %53 %53 %53
%64 = OpIAdd %5 %57 %18
OpImageWrite %9 %64 %63
OpReturn
OpFunctionEnd
#endif
