; SPIR-V
; Version: 1.4
; Generator: Unknown(30017); 21022
; Bound: 125
; Schema: 0
OpCapability Shader
OpCapability ImageBuffer
OpCapability RayQueryKHR
OpCapability RayTraversalPrimitiveCullingKHR
OpCapability RayTracingLinearSweptSpheresGeometryNV
OpExtension "SPV_KHR_ray_query"
OpExtension "SPV_NV_linear_swept_spheres"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %8 %12 %17
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %17 "RayQueryHeap"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %12 DescriptorSet 0
OpDecorate %12 Binding 1
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 1
%6 = OpTypeAccelerationStructureKHR
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpTypeInt 32 0
%10 = OpTypeImage %9 Buffer 0 0 0 2 R32ui
%11 = OpTypePointer UniformConstant %10
%12 = OpVariable %11 UniformConstant
%13 = OpTypeRayQueryKHR
%14 = OpConstant %9 2
%15 = OpTypeArray %13 %14
%16 = OpTypePointer Private %15
%17 = OpVariable %16 Private
%21 = OpConstant %9 0
%22 = OpConstant %9 1
%23 = OpTypePointer Private %13
%25 = OpConstant %9 255
%26 = OpTypeFloat 32
%27 = OpConstant %26 0
%28 = OpConstant %26 1
%29 = OpTypeVector %26 3
%31 = OpConstant %26 0.00100000005
%33 = OpConstant %26 10
%37 = OpTypeVector %9 4
%43 = OpConstant %9 3
%47 = OpTypeBool
%59 = OpConstantFalse %47
%79 = OpTypeArray %29 %14
%80 = OpTypeArray %26 %14
%99 = OpConstant %9 4
%107 = OpConstant %9 8
%3 = OpFunction %1 None %2
%4 = OpLabel
%38 = OpUndef %9
%39 = OpUndef %9
%40 = OpUndef %9
OpBranch %115
%115 = OpLabel
%18 = OpLoad %10 %12
%20 = OpLoad %6 %8
%24 = OpInBoundsAccessChain %23 %17 %21
%30 = OpCompositeConstruct %29 %27 %27 %27
%32 = OpCompositeConstruct %29 %27 %27 %28
OpRayQueryInitializeKHR %24 %20 %22 %25 %30 %31 %32 %33
%34 = OpInBoundsAccessChain %23 %17 %22
%35 = OpCompositeConstruct %29 %28 %27 %27
%36 = OpCompositeConstruct %29 %27 %27 %28
OpRayQueryInitializeKHR %34 %20 %22 %25 %35 %31 %36 %33
%42 = OpIAdd %9 %21 %43
%41 = OpImageRead %37 %18 %42
%44 = OpCompositeExtract %9 %41 0
%45 = OpCompositeConstruct %37 %38 %39 %40 %44
%46 = OpCompositeExtract %9 %45 3
%48 = OpIEqual %47 %46 %21
OpSelectionMerge %117 None
OpBranchConditional %48 %117 %116
%116 = OpLabel
OpBranch %117
%117 = OpLabel
%49 = OpPhi %9 %21 %115 %22 %116
%50 = OpInBoundsAccessChain %23 %17 %49
%51 = OpCompositeConstruct %29 %27 %27 %27
%52 = OpCompositeConstruct %29 %27 %27 %28
OpRayQueryInitializeKHR %50 %20 %22 %25 %51 %31 %52 %33
OpBranch %118
%118 = OpLabel
%53 = OpInBoundsAccessChain %23 %17 %49
%54 = OpRayQueryProceedKHR %47 %53
OpLoopMerge %119 %118 None
OpBranchConditional %54 %118 %119
%119 = OpLabel
%55 = OpInBoundsAccessChain %23 %17 %49
%56 = OpRayQueryGetIntersectionTypeKHR %9 %55 %22
%57 = OpIEqual %47 %56 %21
OpSelectionMerge %121 None
OpBranchConditional %57 %121 %120
%120 = OpLabel
%71 = OpInBoundsAccessChain %23 %17 %49
%72 = OpRayQueryGetRayFlagsKHR %9 %71
%73 = OpInBoundsAccessChain %23 %17 %49
%74 = OpRayQueryIsLSSHitNV %47 %73 %22
%75 = OpSelect %9 %74 %22 %21
%60 = OpINotEqual %47 %75 %21
OpBranch %121
%121 = OpLabel
%58 = OpPhi %47 %59 %119 %60 %120
%61 = OpSelect %9 %58 %22 %21
%62 = OpInBoundsAccessChain %23 %17 %49
%63 = OpRayQueryGetIntersectionTypeKHR %9 %62 %22
%64 = OpCompositeConstruct %37 %61 %61 %61 %61
OpImageWrite %18 %21 %64
%65 = OpCompositeConstruct %37 %63 %63 %63 %63
%66 = OpIAdd %9 %21 %22
OpImageWrite %18 %66 %65
%67 = OpCompositeConstruct %37 %21 %21 %21 %21
%68 = OpIAdd %9 %21 %14
OpImageWrite %18 %68 %67
%69 = OpCompositeConstruct %37 %21 %21 %21 %21
%70 = OpIAdd %9 %21 %43
OpImageWrite %18 %70 %69
OpSelectionMerge %123 None
OpBranchConditional %58 %122 %123
%122 = OpLabel
%76 = OpInBoundsAccessChain %23 %17 %49
%77 = OpRayQueryGetRayFlagsKHR %9 %76
%78 = OpInBoundsAccessChain %23 %17 %49
%81 = OpRayQueryGetIntersectionLSSPositionsNV %79 %78 %22
%82 = OpRayQueryGetIntersectionLSSRadiiNV %80 %78 %22
%83 = OpCompositeExtract %26 %81 0 0
%84 = OpBitcast %9 %83
%85 = OpCompositeExtract %26 %81 0 1
%86 = OpBitcast %9 %85
%87 = OpCompositeExtract %26 %81 0 2
%88 = OpBitcast %9 %87
%89 = OpCompositeExtract %26 %82 0
%90 = OpBitcast %9 %89
%91 = OpCompositeExtract %26 %81 1 0
%92 = OpBitcast %9 %91
%93 = OpCompositeExtract %26 %81 1 1
%94 = OpBitcast %9 %93
%95 = OpCompositeExtract %26 %81 1 2
%96 = OpBitcast %9 %95
%97 = OpCompositeExtract %26 %82 1
%98 = OpBitcast %9 %97
%100 = OpCompositeConstruct %37 %84 %84 %84 %84
OpImageWrite %18 %99 %100
%101 = OpCompositeConstruct %37 %86 %86 %86 %86
%102 = OpIAdd %9 %99 %22
OpImageWrite %18 %102 %101
%103 = OpCompositeConstruct %37 %88 %88 %88 %88
%104 = OpIAdd %9 %99 %14
OpImageWrite %18 %104 %103
%105 = OpCompositeConstruct %37 %90 %90 %90 %90
%106 = OpIAdd %9 %99 %43
OpImageWrite %18 %106 %105
%108 = OpCompositeConstruct %37 %92 %92 %92 %92
OpImageWrite %18 %107 %108
%109 = OpCompositeConstruct %37 %94 %94 %94 %94
%110 = OpIAdd %9 %107 %22
OpImageWrite %18 %110 %109
%111 = OpCompositeConstruct %37 %96 %96 %96 %96
%112 = OpIAdd %9 %107 %14
OpImageWrite %18 %112 %111
%113 = OpCompositeConstruct %37 %98 %98 %98 %98
%114 = OpIAdd %9 %107 %43
OpImageWrite %18 %114 %113
OpBranch %123
%123 = OpLabel
OpReturn
OpFunctionEnd

