; SPIR-V
; Version: 1.4
; Generator: Unknown(30017); 21022
; Bound: 97
; Schema: 0
OpCapability Shader
OpCapability ImageBuffer
OpCapability RayQueryKHR
OpCapability RayTraversalPrimitiveCullingKHR
OpCapability RayTracingLinearSweptSpheresGeometryNV
OpExtension "SPV_KHR_ray_query"
OpExtension "SPV_NV_linear_swept_spheres"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %8 %12 %18
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %12 DescriptorSet 0
OpDecorate %12 Binding 1
OpDecorate %12 NonReadable
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 1
%6 = OpTypeAccelerationStructureKHR
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpTypeInt 32 0
%10 = OpTypeImage %9 Buffer 0 0 0 2 R32ui
%11 = OpTypePointer UniformConstant %10
%12 = OpVariable %11 UniformConstant
%16 = OpTypeRayQueryKHR
%17 = OpTypePointer Private %16
%18 = OpVariable %17 Private
%19 = OpConstant %9 1
%20 = OpConstant %9 255
%21 = OpTypeFloat 32
%22 = OpConstant %21 0
%23 = OpConstant %21 1
%24 = OpTypeVector %21 3
%26 = OpConstant %21 0.00100000005
%28 = OpConstant %21 10
%29 = OpTypeBool
%33 = OpConstant %9 0
%35 = OpConstantFalse %29
%39 = OpTypeVector %9 4
%45 = OpConstant %9 2
%48 = OpConstant %9 3
%53 = OpTypeArray %24 %45
%54 = OpTypeArray %21 %45
%73 = OpConstant %9 4
%81 = OpConstant %9 8
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %89
%89 = OpLabel
%13 = OpLoad %10 %12
%15 = OpLoad %6 %8
%25 = OpCompositeConstruct %24 %22 %22 %22
%27 = OpCompositeConstruct %24 %22 %22 %23
OpRayQueryInitializeKHR %18 %15 %19 %20 %25 %26 %27 %28
OpBranch %90
%90 = OpLabel
%30 = OpRayQueryProceedKHR %29 %18
OpLoopMerge %91 %90 None
OpBranchConditional %30 %90 %91
%91 = OpLabel
%31 = OpRayQueryGetIntersectionTypeKHR %9 %18 %19
%32 = OpIEqual %29 %31 %33
OpSelectionMerge %93 None
OpBranchConditional %32 %93 %92
%92 = OpLabel
%49 = OpRayQueryGetRayFlagsKHR %9 %18
%50 = OpRayQueryIsLSSHitNV %29 %18 %19
%51 = OpSelect %9 %50 %19 %33
%36 = OpINotEqual %29 %51 %33
OpBranch %93
%93 = OpLabel
%34 = OpPhi %29 %35 %91 %36 %92
%37 = OpSelect %9 %34 %19 %33
%38 = OpRayQueryGetIntersectionTypeKHR %9 %18 %19
%40 = OpCompositeConstruct %39 %37 %37 %37 %37
OpImageWrite %13 %33 %40
%41 = OpCompositeConstruct %39 %38 %38 %38 %38
%42 = OpIAdd %9 %33 %19
OpImageWrite %13 %42 %41
%43 = OpCompositeConstruct %39 %33 %33 %33 %33
%44 = OpIAdd %9 %33 %45
OpImageWrite %13 %44 %43
%46 = OpCompositeConstruct %39 %33 %33 %33 %33
%47 = OpIAdd %9 %33 %48
OpImageWrite %13 %47 %46
OpSelectionMerge %95 None
OpBranchConditional %34 %94 %95
%94 = OpLabel
%52 = OpRayQueryGetRayFlagsKHR %9 %18
%55 = OpRayQueryGetIntersectionLSSPositionsNV %53 %18 %19
%56 = OpRayQueryGetIntersectionLSSRadiiNV %54 %18 %19
%57 = OpCompositeExtract %21 %55 0 0
%58 = OpBitcast %9 %57
%59 = OpCompositeExtract %21 %55 0 1
%60 = OpBitcast %9 %59
%61 = OpCompositeExtract %21 %55 0 2
%62 = OpBitcast %9 %61
%63 = OpCompositeExtract %21 %56 0
%64 = OpBitcast %9 %63
%65 = OpCompositeExtract %21 %55 1 0
%66 = OpBitcast %9 %65
%67 = OpCompositeExtract %21 %55 1 1
%68 = OpBitcast %9 %67
%69 = OpCompositeExtract %21 %55 1 2
%70 = OpBitcast %9 %69
%71 = OpCompositeExtract %21 %56 1
%72 = OpBitcast %9 %71
%74 = OpCompositeConstruct %39 %58 %58 %58 %58
OpImageWrite %13 %73 %74
%75 = OpCompositeConstruct %39 %60 %60 %60 %60
%76 = OpIAdd %9 %73 %19
OpImageWrite %13 %76 %75
%77 = OpCompositeConstruct %39 %62 %62 %62 %62
%78 = OpIAdd %9 %73 %45
OpImageWrite %13 %78 %77
%79 = OpCompositeConstruct %39 %64 %64 %64 %64
%80 = OpIAdd %9 %73 %48
OpImageWrite %13 %80 %79
%82 = OpCompositeConstruct %39 %66 %66 %66 %66
OpImageWrite %13 %81 %82
%83 = OpCompositeConstruct %39 %68 %68 %68 %68
%84 = OpIAdd %9 %81 %19
OpImageWrite %13 %84 %83
%85 = OpCompositeConstruct %39 %70 %70 %70 %70
%86 = OpIAdd %9 %81 %45
OpImageWrite %13 %86 %85
%87 = OpCompositeConstruct %39 %72 %72 %72 %72
%88 = OpIAdd %9 %81 %48
OpImageWrite %13 %88 %87
OpBranch %95
%95 = OpLabel
OpReturn
OpFunctionEnd

