#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 4, binding = 0, std430) buffer SSBO
{
    uint16_t _m0[];
} _14[];

layout(set = 4, binding = 0, std430) buffer _17_20
{
    u16vec2 _m0[];
} _20[];

layout(set = 4, binding = 0, scalar) buffer _23_26
{
    u16vec3 _m0[];
} _26[];

layout(set = 4, binding = 0, std430) buffer _29_32
{
    u16vec4 _m0[];
} _32[];

layout(set = 4, binding = 0, std430) buffer _34_37
{
    uint16_t _m0[];
} _37[];

layout(set = 4, binding = 0, std430) buffer _39_42
{
    u16vec2 _m0[];
} _42[];

layout(set = 4, binding = 0, std430) buffer _44_47
{
    u16vec4 _m0[];
} _47[];

layout(set = 4, binding = 0, std430) buffer _49_52
{
    uint _m0[];
} _52[];

layout(set = 4, binding = 0, std430) buffer _55_58
{
    uvec4 _m0[];
} _58[];

layout(set = 4, binding = 0, std430) writeonly buffer _60_63
{
    uint16_t _m0[];
} _63[];

layout(set = 4, binding = 0, std430) writeonly buffer _65_68
{
    u16vec2 _m0[];
} _68[];

layout(set = 4, binding = 0, std430) writeonly buffer _70_73
{
    u16vec4 _m0[];
} _73[];

layout(push_constant, std430) uniform RootConstants
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
    uint _m5;
    uint _m6;
    uint _m7;
} registers;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _78 = registers._m4 + 6u;
    uint _88 = registers._m4 + 5u;
    uint _95 = registers._m4 + 4u;
    uint _108 = registers._m4 + 3u;
    uint _114 = registers._m4 + 2u;
    uint _120 = registers._m4 + 1u;
    _14[registers._m4]._m0[gl_GlobalInvocationID.x] = float16BitsToUint16(uint16BitsToFloat16(_14[registers._m4]._m0[gl_GlobalInvocationID.x]) + float16_t(1.0));
    _20[_120]._m0[gl_GlobalInvocationID.x] = u16vec2(_20[_120]._m0[gl_GlobalInvocationID.x].x + 2us, _20[_120]._m0[gl_GlobalInvocationID.x].y + 2us);
    f16vec3 _158 = uint16BitsToFloat16(_26[_114]._m0[gl_GlobalInvocationID.x]);
    _26[_114]._m0[gl_GlobalInvocationID.x] = u16vec3(float16BitsToUint16(_158.x + float16_t(3.0)), float16BitsToUint16(_158.y + float16_t(3.0)), float16BitsToUint16(_158.z + float16_t(3.0)));
    _32[_108]._m0[gl_GlobalInvocationID.x] = u16vec4(_32[_108]._m0[gl_GlobalInvocationID.x].x + 4us, _32[_108]._m0[gl_GlobalInvocationID.x].y + 4us, _32[_108]._m0[gl_GlobalInvocationID.x].z + 4us, _32[_108]._m0[gl_GlobalInvocationID.x].w + 4us);
    uint16_t _197 = _37[_95]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 2u)];
    float _200 = float(uint16BitsToFloat16(_197));
    u16vec2 _204 = _42[_95]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)];
    f16vec2 _206 = uint16BitsToFloat16(_204);
    float _210 = float(_206.y);
    uint _214 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 2u);
    uint16_t _216 = _37[_95]._m0[_214];
    uint16_t _219 = _37[_95]._m0[_214 + 1u];
    uint16_t _222 = _37[_95]._m0[_214 + 2u];
    f16vec3 _224 = uint16BitsToFloat16(u16vec3(_216, _219, _222));
    float _228 = float(_224.x);
    u16vec4 _236 = _47[_95]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 8u)];
    f16vec4 _238 = uint16BitsToFloat16(_236);
    uint16_t _250 = _37[_95]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 2u)];
    float _251 = float(_250);
    uint _253 = ByteAddressMask(gl_GlobalInvocationID.x, 4u);
    u16vec2 _255 = _42[_95]._m0[_253];
    float _259 = float(_255.y);
    uint _262 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 2u);
    uint16_t _264 = _37[_95]._m0[_262];
    uint16_t _267 = _37[_95]._m0[_262 + 1u];
    uint16_t _270 = _37[_95]._m0[_262 + 2u];
    u16vec3 _271 = u16vec3(_264, _267, _270);
    float _275 = float(_271.x);
    uint _279 = ByteAddressMask(gl_GlobalInvocationID.x, 8u);
    u16vec4 _281 = _47[_95]._m0[_279];
    _63[_88]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 2u)] = float16BitsToUint16(float16_t(1.0));
    _68[_88]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)] = u16vec2(float16BitsToUint16(float16_t(2.0)), float16BitsToUint16(float16_t(4.0)));
    uint _302 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 2u);
    _63[_88]._m0[_302] = float16BitsToUint16(float16_t(4.0));
    _63[_88]._m0[_302 + 1u] = float16BitsToUint16(float16_t(5.0));
    _63[_88]._m0[_302 + 2u] = float16BitsToUint16(float16_t(6.0));
    _73[_88]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 8u)] = u16vec4(float16BitsToUint16(float16_t(7.0)), float16BitsToUint16(float16_t(8.0)), float16BitsToUint16(float16_t(9.0)), float16BitsToUint16(float16_t(10.0)));
    _63[_78]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 2u)] = 1us;
    _68[_78]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)] = u16vec2(2us, 4us);
    uint _331 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 2u);
    _63[_78]._m0[_331] = 4us;
    _63[_78]._m0[_331 + 1u] = 5us;
    _63[_78]._m0[_331 + 2u] = 6us;
    _73[_78]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 8u)] = u16vec4(7us, 8us, 9us, 10us);
    uint _349 = _52[_95]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 4u)];
    float _350 = uintBitsToFloat(_349);
    uint _355 = registers._m4 + (gl_GlobalInvocationID.x + 0u);
    uint16_t _361 = _37[nonuniformEXT(_355)]._m0[ByteAddressMask(gl_GlobalInvocationID.x * 2u, 2u)];
    float _363 = float(uint16BitsToFloat16(_361));
    float _366 = ((float(_206.x) + _200) + _251) + float(_255.x);
    float _372 = (((((_366 + _228) + float(_238.x)) + _275) + float(_281.x)) + _350) + _363;
    float _378 = (((((_366 + float(_224.y)) + float(_238.y)) + float(_271.y)) + float(_281.y)) + _350) + _363;
    _42[nonuniformEXT(_355)]._m0[ByteAddressMask(gl_GlobalInvocationID.x * 2u, 4u)] = u16vec2(float16BitsToUint16(float16_t(_372)), float16BitsToUint16(float16_t(_378)));
    _58[_95]._m0[ByteAddressMask(gl_GlobalInvocationID.x, 16u)] = uvec4(uint((float(uint(_14[registers._m4]._m0.length()) / 1u) + _372) + float(uint(_73[_88]._m0.length()) * 8u)), uint(_378 + 2.0), uint((((((((((_210 + _200) + float(_224.z)) + float(_238.z)) + _251) + _259) + float(_271.z)) + float(_281.z)) + _350) + _363) + float(uint(_32[_108]._m0.length()) / 1u)), uint((((((((((_200 + 8.0) + _210) + _228) + float(_238.w)) + _251) + _259) + _275) + float(_281.w)) + _350) + _363));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 425
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Int16
OpCapability StorageBufferArrayDynamicIndexing
OpCapability ImageQuery
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpCapability RuntimeDescriptorArray
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability PhysicalStorageBufferAddresses
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_KHR_physical_storage_buffer"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %130
OpExecutionMode %3 LocalSize 64 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %11 "SSBO"
OpName %17 "SSBO"
OpName %23 "SSBO"
OpName %29 "SSBO"
OpName %34 "SSBO"
OpName %39 "SSBO"
OpName %44 "SSBO"
OpName %49 "SSBO"
OpName %55 "SSBO"
OpName %60 "SSBO"
OpName %65 "SSBO"
OpName %70 "SSBO"
OpName %189 "ByteAddressMask"
OpName %187 "index"
OpName %188 "stride"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpDecorate %10 ArrayStride 2
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %14 DescriptorSet 4
OpDecorate %14 Binding 0
OpDecorate %16 ArrayStride 4
OpMemberDecorate %17 0 Offset 0
OpDecorate %17 Block
OpDecorate %20 DescriptorSet 4
OpDecorate %20 Binding 0
OpDecorate %22 ArrayStride 6
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %26 DescriptorSet 4
OpDecorate %26 Binding 0
OpDecorate %28 ArrayStride 8
OpMemberDecorate %29 0 Offset 0
OpDecorate %29 Block
OpDecorate %32 DescriptorSet 4
OpDecorate %32 Binding 0
OpDecorate %33 ArrayStride 2
OpMemberDecorate %34 0 Offset 0
OpDecorate %34 Block
OpDecorate %37 DescriptorSet 4
OpDecorate %37 Binding 0
OpDecorate %37 Aliased
OpDecorate %38 ArrayStride 4
OpMemberDecorate %39 0 Offset 0
OpDecorate %39 Block
OpDecorate %42 DescriptorSet 4
OpDecorate %42 Binding 0
OpDecorate %42 Aliased
OpDecorate %43 ArrayStride 8
OpMemberDecorate %44 0 Offset 0
OpDecorate %44 Block
OpDecorate %47 DescriptorSet 4
OpDecorate %47 Binding 0
OpDecorate %47 Aliased
OpDecorate %48 ArrayStride 4
OpMemberDecorate %49 0 Offset 0
OpDecorate %49 Block
OpDecorate %52 DescriptorSet 4
OpDecorate %52 Binding 0
OpDecorate %52 Aliased
OpDecorate %54 ArrayStride 16
OpMemberDecorate %55 0 Offset 0
OpDecorate %55 Block
OpDecorate %58 DescriptorSet 4
OpDecorate %58 Binding 0
OpDecorate %58 Aliased
OpDecorate %59 ArrayStride 2
OpMemberDecorate %60 0 Offset 0
OpDecorate %60 Block
OpDecorate %63 DescriptorSet 4
OpDecorate %63 Binding 0
OpDecorate %63 NonReadable
OpDecorate %63 Aliased
OpDecorate %64 ArrayStride 4
OpMemberDecorate %65 0 Offset 0
OpDecorate %65 Block
OpDecorate %68 DescriptorSet 4
OpDecorate %68 Binding 0
OpDecorate %68 NonReadable
OpDecorate %68 Aliased
OpDecorate %69 ArrayStride 8
OpMemberDecorate %70 0 Offset 0
OpDecorate %70 Block
OpDecorate %73 DescriptorSet 4
OpDecorate %73 Binding 0
OpDecorate %73 NonReadable
OpDecorate %73 Aliased
OpDecorate %130 BuiltIn GlobalInvocationId
OpDecorate %355 NonUniform
OpDecorate %356 NonUniform
OpDecorate %357 NonUniform
OpDecorate %360 NonUniform
OpDecorate %387 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeInt 16 0
%10 = OpTypeRuntimeArray %9
%11 = OpTypeStruct %10
%12 = OpTypeRuntimeArray %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %9 2
%16 = OpTypeRuntimeArray %15
%17 = OpTypeStruct %16
%18 = OpTypeRuntimeArray %17
%19 = OpTypePointer StorageBuffer %18
%20 = OpVariable %19 StorageBuffer
%21 = OpTypeVector %9 3
%22 = OpTypeRuntimeArray %21
%23 = OpTypeStruct %22
%24 = OpTypeRuntimeArray %23
%25 = OpTypePointer StorageBuffer %24
%26 = OpVariable %25 StorageBuffer
%27 = OpTypeVector %9 4
%28 = OpTypeRuntimeArray %27
%29 = OpTypeStruct %28
%30 = OpTypeRuntimeArray %29
%31 = OpTypePointer StorageBuffer %30
%32 = OpVariable %31 StorageBuffer
%33 = OpTypeRuntimeArray %9
%34 = OpTypeStruct %33
%35 = OpTypeRuntimeArray %34
%36 = OpTypePointer StorageBuffer %35
%37 = OpVariable %36 StorageBuffer
%38 = OpTypeRuntimeArray %15
%39 = OpTypeStruct %38
%40 = OpTypeRuntimeArray %39
%41 = OpTypePointer StorageBuffer %40
%42 = OpVariable %41 StorageBuffer
%43 = OpTypeRuntimeArray %27
%44 = OpTypeStruct %43
%45 = OpTypeRuntimeArray %44
%46 = OpTypePointer StorageBuffer %45
%47 = OpVariable %46 StorageBuffer
%48 = OpTypeRuntimeArray %5
%49 = OpTypeStruct %48
%50 = OpTypeRuntimeArray %49
%51 = OpTypePointer StorageBuffer %50
%52 = OpVariable %51 StorageBuffer
%53 = OpTypeVector %5 4
%54 = OpTypeRuntimeArray %53
%55 = OpTypeStruct %54
%56 = OpTypeRuntimeArray %55
%57 = OpTypePointer StorageBuffer %56
%58 = OpVariable %57 StorageBuffer
%59 = OpTypeRuntimeArray %9
%60 = OpTypeStruct %59
%61 = OpTypeRuntimeArray %60
%62 = OpTypePointer StorageBuffer %61
%63 = OpVariable %62 StorageBuffer
%64 = OpTypeRuntimeArray %15
%65 = OpTypeStruct %64
%66 = OpTypeRuntimeArray %65
%67 = OpTypePointer StorageBuffer %66
%68 = OpVariable %67 StorageBuffer
%69 = OpTypeRuntimeArray %27
%70 = OpTypeStruct %69
%71 = OpTypeRuntimeArray %70
%72 = OpTypePointer StorageBuffer %71
%73 = OpVariable %72 StorageBuffer
%74 = OpTypePointer PushConstant %5
%76 = OpConstant %5 4
%79 = OpConstant %5 6
%80 = OpTypePointer StorageBuffer %60
%82 = OpTypePointer StorageBuffer %65
%84 = OpTypePointer StorageBuffer %70
%89 = OpConstant %5 5
%96 = OpTypePointer StorageBuffer %34
%98 = OpTypePointer StorageBuffer %39
%100 = OpTypePointer StorageBuffer %44
%102 = OpTypePointer StorageBuffer %49
%104 = OpTypePointer StorageBuffer %55
%109 = OpConstant %5 3
%110 = OpTypePointer StorageBuffer %29
%115 = OpConstant %5 2
%116 = OpTypePointer StorageBuffer %23
%121 = OpConstant %5 1
%122 = OpTypePointer StorageBuffer %17
%126 = OpTypePointer StorageBuffer %11
%128 = OpTypeVector %5 3
%129 = OpTypePointer Input %128
%130 = OpVariable %129 Input
%131 = OpTypePointer Input %5
%133 = OpConstant %5 0
%135 = OpTypePointer StorageBuffer %9
%138 = OpTypeFloat 16
%141 = OpConstant %138 0x1p+0
%144 = OpTypePointer StorageBuffer %15
%150 = OpConstant %9 2
%154 = OpTypePointer StorageBuffer %21
%157 = OpTypeVector %138 3
%163 = OpConstant %138 0x1.8p+1
%171 = OpTypePointer StorageBuffer %27
%179 = OpConstant %9 4
%186 = OpTypeFunction %5 %5 %5
%192 = OpConstant %5 4294967295
%199 = OpTypeFloat 32
%205 = OpTypeVector %138 2
%234 = OpConstant %5 8
%237 = OpTypeVector %138 4
%295 = OpConstant %138 0x1p+1
%297 = OpConstant %138 0x1p+2
%304 = OpConstant %138 0x1.4p+2
%306 = OpConstant %138 0x1.8p+2
%314 = OpConstant %138 0x1.cp+2
%316 = OpConstant %138 0x1p+3
%318 = OpConstant %138 0x1.2p+3
%320 = OpConstant %138 0x1.4p+3
%325 = OpConstant %9 1
%332 = OpConstant %9 5
%333 = OpConstant %9 6
%340 = OpConstant %9 7
%341 = OpConstant %9 8
%342 = OpConstant %9 9
%343 = OpConstant %9 10
%347 = OpTypePointer StorageBuffer %5
%393 = OpConstant %199 2
%399 = OpConstant %199 8
%419 = OpConstant %5 16
%421 = OpTypePointer StorageBuffer %53
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %423
%423 = OpLabel
%75 = OpAccessChain %74 %8 %76
%77 = OpLoad %5 %75
%78 = OpIAdd %5 %77 %79
%81 = OpAccessChain %80 %63 %78
%83 = OpAccessChain %82 %68 %78
%85 = OpAccessChain %84 %73 %78
%86 = OpAccessChain %74 %8 %76
%87 = OpLoad %5 %86
%88 = OpIAdd %5 %87 %89
%90 = OpAccessChain %80 %63 %88
%91 = OpAccessChain %82 %68 %88
%92 = OpAccessChain %84 %73 %88
%93 = OpAccessChain %74 %8 %76
%94 = OpLoad %5 %93
%95 = OpIAdd %5 %94 %76
%97 = OpAccessChain %96 %37 %95
%99 = OpAccessChain %98 %42 %95
%101 = OpAccessChain %100 %47 %95
%103 = OpAccessChain %102 %52 %95
%105 = OpAccessChain %104 %58 %95
%106 = OpAccessChain %74 %8 %76
%107 = OpLoad %5 %106
%108 = OpIAdd %5 %107 %109
%111 = OpAccessChain %110 %32 %108
%112 = OpAccessChain %74 %8 %76
%113 = OpLoad %5 %112
%114 = OpIAdd %5 %113 %115
%117 = OpAccessChain %116 %26 %114
%118 = OpAccessChain %74 %8 %76
%119 = OpLoad %5 %118
%120 = OpIAdd %5 %119 %121
%123 = OpAccessChain %122 %20 %120
%124 = OpAccessChain %74 %8 %76
%125 = OpLoad %5 %124
%127 = OpAccessChain %126 %14 %125
%132 = OpAccessChain %131 %130 %133
%134 = OpLoad %5 %132
%136 = OpAccessChain %135 %127 %133 %134
%137 = OpLoad %9 %136
%139 = OpBitcast %138 %137
%140 = OpFAdd %138 %139 %141
%142 = OpBitcast %9 %140
%143 = OpAccessChain %135 %127 %133 %134
OpStore %143 %142
%145 = OpAccessChain %144 %123 %133 %134
%146 = OpLoad %15 %145
%147 = OpCompositeExtract %9 %146 0
%148 = OpCompositeExtract %9 %146 1
%149 = OpIAdd %9 %147 %150
%151 = OpIAdd %9 %148 %150
%152 = OpCompositeConstruct %15 %149 %151
%153 = OpAccessChain %144 %123 %133 %134
OpStore %153 %152
%155 = OpAccessChain %154 %117 %133 %134
%156 = OpLoad %21 %155
%158 = OpBitcast %157 %156
%159 = OpCompositeExtract %138 %158 0
%160 = OpCompositeExtract %138 %158 1
%161 = OpCompositeExtract %138 %158 2
%162 = OpFAdd %138 %159 %163
%164 = OpFAdd %138 %160 %163
%165 = OpFAdd %138 %161 %163
%166 = OpBitcast %9 %162
%167 = OpBitcast %9 %164
%168 = OpBitcast %9 %165
%169 = OpCompositeConstruct %21 %166 %167 %168
%170 = OpAccessChain %154 %117 %133 %134
OpStore %170 %169
%172 = OpAccessChain %171 %111 %133 %134
%173 = OpLoad %27 %172
%174 = OpCompositeExtract %9 %173 0
%175 = OpCompositeExtract %9 %173 1
%176 = OpCompositeExtract %9 %173 2
%177 = OpCompositeExtract %9 %173 3
%178 = OpIAdd %9 %174 %179
%180 = OpIAdd %9 %175 %179
%181 = OpIAdd %9 %176 %179
%182 = OpIAdd %9 %177 %179
%183 = OpCompositeConstruct %27 %178 %180 %181 %182
%184 = OpAccessChain %171 %111 %133 %134
OpStore %184 %183
%185 = OpShiftLeftLogical %5 %134 %121
%195 = OpFunctionCall %5 %189 %134 %115
%196 = OpAccessChain %135 %97 %133 %195
%197 = OpLoad %9 %196
%198 = OpBitcast %138 %197
%200 = OpFConvert %199 %198
%201 = OpShiftLeftLogical %5 %134 %115
%202 = OpFunctionCall %5 %189 %134 %76
%203 = OpAccessChain %144 %99 %133 %202
%204 = OpLoad %15 %203
%206 = OpBitcast %205 %204
%207 = OpCompositeExtract %138 %206 0
%208 = OpCompositeExtract %138 %206 1
%209 = OpFConvert %199 %207
%210 = OpFConvert %199 %208
%211 = OpFAdd %199 %210 %200
%212 = OpIMul %5 %134 %79
%213 = OpIMul %5 %134 %109
%214 = OpFunctionCall %5 %189 %213 %115
%215 = OpAccessChain %135 %97 %133 %214
%216 = OpLoad %9 %215
%218 = OpIAdd %5 %214 %121
%217 = OpAccessChain %135 %97 %133 %218
%219 = OpLoad %9 %217
%221 = OpIAdd %5 %214 %115
%220 = OpAccessChain %135 %97 %133 %221
%222 = OpLoad %9 %220
%223 = OpCompositeConstruct %21 %216 %219 %222
%224 = OpBitcast %157 %223
%225 = OpCompositeExtract %138 %224 0
%226 = OpCompositeExtract %138 %224 1
%227 = OpCompositeExtract %138 %224 2
%228 = OpFConvert %199 %225
%229 = OpFConvert %199 %226
%230 = OpFConvert %199 %227
%231 = OpFAdd %199 %211 %230
%232 = OpShiftLeftLogical %5 %134 %109
%233 = OpFunctionCall %5 %189 %134 %234
%235 = OpAccessChain %171 %101 %133 %233
%236 = OpLoad %27 %235
%238 = OpBitcast %237 %236
%239 = OpCompositeExtract %138 %238 0
%240 = OpCompositeExtract %138 %238 1
%241 = OpCompositeExtract %138 %238 2
%242 = OpCompositeExtract %138 %238 3
%243 = OpFConvert %199 %239
%244 = OpFConvert %199 %240
%245 = OpFConvert %199 %241
%246 = OpFConvert %199 %242
%247 = OpFAdd %199 %231 %245
%248 = OpFunctionCall %5 %189 %134 %115
%249 = OpAccessChain %135 %97 %133 %248
%250 = OpLoad %9 %249
%251 = OpConvertUToF %199 %250
%252 = OpFAdd %199 %247 %251
%253 = OpFunctionCall %5 %189 %134 %76
%254 = OpAccessChain %144 %99 %133 %253
%255 = OpLoad %15 %254
%256 = OpCompositeExtract %9 %255 0
%257 = OpCompositeExtract %9 %255 1
%258 = OpConvertUToF %199 %256
%259 = OpConvertUToF %199 %257
%260 = OpFAdd %199 %252 %259
%261 = OpIMul %5 %134 %109
%262 = OpFunctionCall %5 %189 %261 %115
%263 = OpAccessChain %135 %97 %133 %262
%264 = OpLoad %9 %263
%266 = OpIAdd %5 %262 %121
%265 = OpAccessChain %135 %97 %133 %266
%267 = OpLoad %9 %265
%269 = OpIAdd %5 %262 %115
%268 = OpAccessChain %135 %97 %133 %269
%270 = OpLoad %9 %268
%271 = OpCompositeConstruct %21 %264 %267 %270
%272 = OpCompositeExtract %9 %271 0
%273 = OpCompositeExtract %9 %271 1
%274 = OpCompositeExtract %9 %271 2
%275 = OpConvertUToF %199 %272
%276 = OpConvertUToF %199 %273
%277 = OpConvertUToF %199 %274
%278 = OpFAdd %199 %260 %277
%279 = OpFunctionCall %5 %189 %134 %234
%280 = OpAccessChain %171 %101 %133 %279
%281 = OpLoad %27 %280
%282 = OpCompositeExtract %9 %281 0
%283 = OpCompositeExtract %9 %281 1
%284 = OpCompositeExtract %9 %281 2
%285 = OpCompositeExtract %9 %281 3
%286 = OpConvertUToF %199 %282
%287 = OpConvertUToF %199 %283
%288 = OpConvertUToF %199 %284
%289 = OpConvertUToF %199 %285
%290 = OpFAdd %199 %278 %288
%291 = OpFunctionCall %5 %189 %134 %115
%292 = OpBitcast %9 %141
%293 = OpAccessChain %135 %90 %133 %291
OpStore %293 %292
%294 = OpFunctionCall %5 %189 %134 %76
%296 = OpBitcast %9 %295
%298 = OpBitcast %9 %297
%299 = OpCompositeConstruct %15 %296 %298
%300 = OpAccessChain %144 %91 %133 %294
OpStore %300 %299
%301 = OpIMul %5 %134 %109
%302 = OpFunctionCall %5 %189 %301 %115
%303 = OpBitcast %9 %297
%305 = OpBitcast %9 %304
%307 = OpBitcast %9 %306
%308 = OpAccessChain %135 %90 %133 %302
OpStore %308 %303
%310 = OpIAdd %5 %302 %121
%309 = OpAccessChain %135 %90 %133 %310
OpStore %309 %305
%312 = OpIAdd %5 %302 %115
%311 = OpAccessChain %135 %90 %133 %312
OpStore %311 %307
%313 = OpFunctionCall %5 %189 %134 %234
%315 = OpBitcast %9 %314
%317 = OpBitcast %9 %316
%319 = OpBitcast %9 %318
%321 = OpBitcast %9 %320
%322 = OpCompositeConstruct %27 %315 %317 %319 %321
%323 = OpAccessChain %171 %92 %133 %313
OpStore %323 %322
%324 = OpFunctionCall %5 %189 %134 %115
%326 = OpAccessChain %135 %81 %133 %324
OpStore %326 %325
%327 = OpFunctionCall %5 %189 %134 %76
%328 = OpCompositeConstruct %15 %150 %179
%329 = OpAccessChain %144 %83 %133 %327
OpStore %329 %328
%330 = OpIMul %5 %134 %109
%331 = OpFunctionCall %5 %189 %330 %115
%334 = OpAccessChain %135 %81 %133 %331
OpStore %334 %179
%336 = OpIAdd %5 %331 %121
%335 = OpAccessChain %135 %81 %133 %336
OpStore %335 %332
%338 = OpIAdd %5 %331 %115
%337 = OpAccessChain %135 %81 %133 %338
OpStore %337 %333
%339 = OpFunctionCall %5 %189 %134 %234
%344 = OpCompositeConstruct %27 %340 %341 %342 %343
%345 = OpAccessChain %171 %85 %133 %339
OpStore %345 %344
%346 = OpFunctionCall %5 %189 %134 %76
%348 = OpAccessChain %347 %103 %133 %346
%349 = OpLoad %5 %348
%350 = OpBitcast %199 %349
%351 = OpFAdd %199 %290 %350
%352 = OpIAdd %5 %134 %133
%353 = OpAccessChain %74 %8 %76
%354 = OpLoad %5 %353
%355 = OpIAdd %5 %354 %352
%356 = OpAccessChain %96 %37 %355
%357 = OpAccessChain %98 %42 %355
%358 = OpIMul %5 %134 %115
%359 = OpFunctionCall %5 %189 %358 %115
%360 = OpAccessChain %135 %356 %133 %359
%361 = OpLoad %9 %360
%362 = OpBitcast %138 %361
%363 = OpFConvert %199 %362
%364 = OpFAdd %199 %209 %200
%365 = OpFAdd %199 %364 %251
%366 = OpFAdd %199 %365 %258
%367 = OpFAdd %199 %366 %228
%368 = OpFAdd %199 %367 %243
%369 = OpFAdd %199 %368 %275
%370 = OpFAdd %199 %369 %286
%371 = OpFAdd %199 %370 %350
%372 = OpFAdd %199 %371 %363
%373 = OpFAdd %199 %366 %229
%374 = OpFAdd %199 %373 %244
%375 = OpFAdd %199 %374 %276
%376 = OpFAdd %199 %375 %287
%377 = OpFAdd %199 %376 %350
%378 = OpFAdd %199 %377 %363
%379 = OpFAdd %199 %351 %363
%380 = OpFConvert %138 %372
%381 = OpFConvert %138 %378
%382 = OpIMul %5 %134 %115
%383 = OpFunctionCall %5 %189 %382 %76
%384 = OpBitcast %9 %380
%385 = OpBitcast %9 %381
%386 = OpCompositeConstruct %15 %384 %385
%387 = OpAccessChain %144 %357 %133 %383
OpStore %387 %386
%388 = OpArrayLength %5 %127 0
%389 = OpUDiv %5 %388 %121
%390 = OpConvertUToF %199 %389
%391 = OpFAdd %199 %390 %372
%392 = OpFAdd %199 %378 %393
%394 = OpArrayLength %5 %111 0
%395 = OpUDiv %5 %394 %121
%396 = OpConvertUToF %199 %395
%397 = OpFAdd %199 %379 %396
%398 = OpFAdd %199 %200 %399
%400 = OpFAdd %199 %398 %210
%401 = OpFAdd %199 %400 %228
%402 = OpFAdd %199 %401 %246
%403 = OpFAdd %199 %402 %251
%404 = OpFAdd %199 %403 %259
%405 = OpFAdd %199 %404 %275
%406 = OpFAdd %199 %405 %289
%407 = OpFAdd %199 %406 %350
%408 = OpFAdd %199 %407 %363
%409 = OpArrayLength %5 %92 0
%410 = OpIMul %5 %409 %234
%411 = OpConvertUToF %199 %410
%412 = OpFAdd %199 %391 %411
%413 = OpConvertFToU %5 %412
%414 = OpConvertFToU %5 %392
%415 = OpConvertFToU %5 %397
%416 = OpConvertFToU %5 %408
%417 = OpShiftLeftLogical %5 %134 %76
%418 = OpFunctionCall %5 %189 %134 %419
%420 = OpCompositeConstruct %53 %413 %414 %415 %416
%422 = OpAccessChain %421 %105 %133 %418
OpStore %422 %420
OpReturn
OpFunctionEnd
%189 = OpFunction %5 None %186
%187 = OpFunctionParameter %5
%188 = OpFunctionParameter %5
%190 = OpLabel
%191 = OpUDiv %5 %192 %188
%193 = OpBitwiseAnd %5 %187 %191
OpReturnValue %193
OpFunctionEnd
#endif
