#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_KHR_shader_subgroup_ballot : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 15, binding = 0, std430) restrict readonly buffer SSBO_Offsets
{
    uvec2 _m0[];
} _13;

layout(set = 1, binding = 0, std430) restrict readonly buffer SSBO
{
    uvec2 _m0[];
} _18[];

layout(set = 1, binding = 0, std430) restrict readonly buffer _21_24
{
    uvec4 _m0[];
} _24[];

layout(set = 4, binding = 0, std430) writeonly buffer _26_29
{
    uvec2 _m0[];
} _29[];

layout(set = 4, binding = 0, std430) writeonly buffer _31_34
{
    uvec4 _m0[];
} _34[];

layout(set = 4, binding = 0, std430) buffer _36_39
{
    uint _m0[];
} _39[];

layout(push_constant, std430) uniform RootConstants
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
    uint _m5;
    uint _m6;
    uint _m7;
    uint _m8;
    uint _m9;
    uint _m10;
    uint _m11;
    uint _m12;
    uint _m13;
    uint _m14;
    uint _m15;
} registers;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uvec2 _52 = _13._m0[subgroupBroadcastFirst(registers._m4)] >> uvec2(2u);
    uint _57 = registers._m4 + 1u;
    uvec2 _64 = _13._m0[subgroupBroadcastFirst(_57)] >> uvec2(4u);
    uvec2 _73 = _13._m0[subgroupBroadcastFirst(registers._m4)] >> uvec2(3u);
    uint _77 = registers._m1 + 1u;
    uvec2 _83 = _13._m0[subgroupBroadcastFirst(_77)] >> uvec2(4u);
    uvec2 _91 = _13._m0[subgroupBroadcastFirst(registers._m1)] >> uvec2(3u);
    vec2 _112 = uintBitsToFloat(_18[registers._m1]._m0[(gl_GlobalInvocationID.x < _91.y) ? (gl_GlobalInvocationID.x + _91.x) : 536870911u]);
    _29[registers._m4]._m0[(gl_GlobalInvocationID.x < _73.y) ? (gl_GlobalInvocationID.x + _73.x) : 536870911u] = uvec2(floatBitsToUint(_112.x), floatBitsToUint(_112.y));
    uint _134 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _149 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    _34[_57]._m0[(_149 < _64.y) ? (_149 + _64.x) : 268435455u] = uvec4(_24[_77]._m0[(_134 < _83.y) ? (_134 + _83.x) : 268435455u]);
    vec2 _164 = uintBitsToFloat(_18[registers._m1]._m0[(gl_GlobalInvocationID.x < _91.y) ? (gl_GlobalInvocationID.x + _91.x) : 536870911u]);
    _29[registers._m4]._m0[(gl_GlobalInvocationID.x < _73.y) ? (gl_GlobalInvocationID.x + _73.x) : 536870911u] = uvec2(floatBitsToUint(_164.x), floatBitsToUint(_164.y));
    uint _176 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _188 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    _34[_57]._m0[(_188 < _64.y) ? (_188 + _64.x) : 268435455u] = uvec4(_24[_77]._m0[(_176 < _83.y) ? (_176 + _83.x) : 268435455u]);
    uint _199 = registers._m1 + (gl_WorkGroupID.x + 2u);
    uvec2 _204 = _13._m0[subgroupBroadcastFirst(_199)] >> uvec2(3u);
    vec2 _212 = uintBitsToFloat(_18[_199]._m0[(gl_GlobalInvocationID.x < _204.y) ? (gl_GlobalInvocationID.x + _204.x) : 536870911u]);
    uint _218 = registers._m4 + (gl_WorkGroupID.x + 0u);
    uvec2 _223 = _13._m0[subgroupBroadcastFirst(_218)] >> uvec2(3u);
    _29[_218]._m0[(gl_GlobalInvocationID.x < _223.y) ? (gl_GlobalInvocationID.x + _223.x) : 536870911u] = uvec2(floatBitsToUint(_212.x), floatBitsToUint(_212.y));
    uint _236 = registers._m1 + (gl_GlobalInvocationID.x + 2u);
    uvec2 _240 = _13._m0[_236] >> uvec2(3u);
    vec2 _248 = uintBitsToFloat(_18[nonuniformEXT(_236)]._m0[(gl_GlobalInvocationID.x < _240.y) ? (gl_GlobalInvocationID.x + _240.x) : 536870911u]);
    uint _254 = registers._m4 + (gl_GlobalInvocationID.x + 0u);
    uvec2 _258 = _13._m0[_254] >> uvec2(3u);
    _29[nonuniformEXT(_254)]._m0[(gl_GlobalInvocationID.x < _258.y) ? (gl_GlobalInvocationID.x + _258.x) : 536870911u] = uvec2(floatBitsToUint(_248.x), floatBitsToUint(_248.y));
    uint _271 = registers._m1 + (gl_WorkGroupID.x + 3u);
    uvec2 _276 = _13._m0[subgroupBroadcastFirst(_271)] >> uvec2(4u);
    uint _277 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _292 = registers._m4 + (gl_WorkGroupID.x + 1u);
    uvec2 _297 = _13._m0[subgroupBroadcastFirst(_292)] >> uvec2(4u);
    uint _298 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    _34[_292]._m0[(_298 < _297.y) ? (_298 + _297.x) : 268435455u] = uvec4(_24[_271]._m0[(_277 < _276.y) ? (_277 + _276.x) : 268435455u]);
    uint _309 = registers._m1 + (gl_GlobalInvocationID.x + 3u);
    uvec2 _313 = _13._m0[_309] >> uvec2(4u);
    uint _314 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _329 = registers._m4 + (gl_GlobalInvocationID.x + 1u);
    uvec2 _333 = _13._m0[_329] >> uvec2(4u);
    uint _334 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    _34[nonuniformEXT(_329)]._m0[(_334 < _333.y) ? (_334 + _333.x) : 268435455u] = uvec4(_24[nonuniformEXT(_309)]._m0[(_314 < _313.y) ? (_314 + _313.x) : 268435455u]);
    uint _343 = (gl_GlobalInvocationID.x * 2u) + 1u;
    uint _352 = atomicAdd(_39[registers._m4]._m0[(_343 < _52.y) ? (_343 + _52.x) : 1073741820u], 1u);
    uint _355 = gl_GlobalInvocationID.x * 2u;
    uint _362 = atomicAdd(_39[registers._m4]._m0[(_355 < _52.y) ? (_355 + _52.x) : 1073741820u], _73.y / 1u);
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 365
; Schema: 0
OpCapability Shader
OpCapability StorageBufferArrayDynamicIndexing
OpCapability ImageQuery
OpCapability GroupNonUniformBallot
OpCapability RuntimeDescriptorArray
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability PhysicalStorageBufferAddresses
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_physical_storage_buffer"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %94 %98
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %11 "SSBO_Offsets"
OpName %15 "SSBO"
OpName %21 "SSBO"
OpName %26 "SSBO"
OpName %31 "SSBO"
OpName %36 "SSBO"
OpName %128 "ByteAddressMask"
OpName %126 "index"
OpName %127 "stride"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpMemberDecorate %6 8 Offset 32
OpMemberDecorate %6 9 Offset 36
OpMemberDecorate %6 10 Offset 40
OpMemberDecorate %6 11 Offset 44
OpMemberDecorate %6 12 Offset 48
OpMemberDecorate %6 13 Offset 52
OpMemberDecorate %6 14 Offset 56
OpMemberDecorate %6 15 Offset 60
OpDecorate %10 ArrayStride 8
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 15
OpDecorate %13 Binding 0
OpDecorate %13 NonWritable
OpDecorate %13 Restrict
OpDecorate %14 ArrayStride 8
OpMemberDecorate %15 0 Offset 0
OpDecorate %15 Block
OpDecorate %18 DescriptorSet 1
OpDecorate %18 Binding 0
OpDecorate %18 NonWritable
OpDecorate %18 Restrict
OpDecorate %20 ArrayStride 16
OpMemberDecorate %21 0 Offset 0
OpDecorate %21 Block
OpDecorate %24 DescriptorSet 1
OpDecorate %24 Binding 0
OpDecorate %24 NonWritable
OpDecorate %24 Restrict
OpDecorate %25 ArrayStride 8
OpMemberDecorate %26 0 Offset 0
OpDecorate %26 Block
OpDecorate %29 DescriptorSet 4
OpDecorate %29 Binding 0
OpDecorate %29 NonReadable
OpDecorate %30 ArrayStride 16
OpMemberDecorate %31 0 Offset 0
OpDecorate %31 Block
OpDecorate %34 DescriptorSet 4
OpDecorate %34 Binding 0
OpDecorate %34 NonReadable
OpDecorate %35 ArrayStride 4
OpMemberDecorate %36 0 Offset 0
OpDecorate %36 Block
OpDecorate %39 DescriptorSet 4
OpDecorate %39 Binding 0
OpDecorate %94 BuiltIn GlobalInvocationId
OpDecorate %98 BuiltIn WorkgroupId
OpDecorate %236 NonUniform
OpDecorate %237 NonUniform
OpDecorate %246 NonUniform
OpDecorate %254 NonUniform
OpDecorate %255 NonUniform
OpDecorate %267 NonUniform
OpDecorate %309 NonUniform
OpDecorate %310 NonUniform
OpDecorate %320 NonUniform
OpDecorate %329 NonUniform
OpDecorate %330 NonUniform
OpDecorate %341 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeVector %5 2
%10 = OpTypeRuntimeArray %9
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeRuntimeArray %9
%15 = OpTypeStruct %14
%16 = OpTypeRuntimeArray %15
%17 = OpTypePointer StorageBuffer %16
%18 = OpVariable %17 StorageBuffer
%19 = OpTypeVector %5 4
%20 = OpTypeRuntimeArray %19
%21 = OpTypeStruct %20
%22 = OpTypeRuntimeArray %21
%23 = OpTypePointer StorageBuffer %22
%24 = OpVariable %23 StorageBuffer
%25 = OpTypeRuntimeArray %9
%26 = OpTypeStruct %25
%27 = OpTypeRuntimeArray %26
%28 = OpTypePointer StorageBuffer %27
%29 = OpVariable %28 StorageBuffer
%30 = OpTypeRuntimeArray %19
%31 = OpTypeStruct %30
%32 = OpTypeRuntimeArray %31
%33 = OpTypePointer StorageBuffer %32
%34 = OpVariable %33 StorageBuffer
%35 = OpTypeRuntimeArray %5
%36 = OpTypeStruct %35
%37 = OpTypeRuntimeArray %36
%38 = OpTypePointer StorageBuffer %37
%39 = OpVariable %38 StorageBuffer
%40 = OpTypePointer PushConstant %5
%42 = OpConstant %5 4
%44 = OpTypePointer StorageBuffer %36
%47 = OpConstant %5 3
%48 = OpTypePointer StorageBuffer %9
%50 = OpConstant %5 0
%53 = OpConstant %5 2
%54 = OpConstantComposite %9 %53 %53
%58 = OpConstant %5 1
%59 = OpTypePointer StorageBuffer %31
%65 = OpConstantComposite %9 %42 %42
%68 = OpTypePointer StorageBuffer %26
%74 = OpConstantComposite %9 %47 %47
%78 = OpTypePointer StorageBuffer %21
%86 = OpTypePointer StorageBuffer %15
%92 = OpTypeVector %5 3
%93 = OpTypePointer Input %92
%94 = OpVariable %93 Input
%95 = OpTypePointer Input %5
%98 = OpVariable %93 Input
%104 = OpTypeBool
%107 = OpConstant %5 536870911
%110 = OpTypeFloat 32
%111 = OpTypeVector %110 2
%125 = OpTypeFunction %5 %5 %5
%131 = OpConstant %5 4294967295
%135 = OpConstant %5 16
%141 = OpConstant %5 268435455
%142 = OpTypePointer StorageBuffer %19
%349 = OpConstant %5 1073741820
%350 = OpTypePointer StorageBuffer %5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %363
%363 = OpLabel
%41 = OpAccessChain %40 %8 %42
%43 = OpLoad %5 %41
%45 = OpAccessChain %44 %39 %43
%46 = OpGroupNonUniformBroadcastFirst %5 %47 %43
%49 = OpAccessChain %48 %13 %50 %46
%51 = OpLoad %9 %49
%52 = OpShiftRightLogical %9 %51 %54
%55 = OpAccessChain %40 %8 %42
%56 = OpLoad %5 %55
%57 = OpIAdd %5 %56 %58
%60 = OpAccessChain %59 %34 %57
%61 = OpGroupNonUniformBroadcastFirst %5 %47 %57
%62 = OpAccessChain %48 %13 %50 %61
%63 = OpLoad %9 %62
%64 = OpShiftRightLogical %9 %63 %65
%66 = OpAccessChain %40 %8 %42
%67 = OpLoad %5 %66
%69 = OpAccessChain %68 %29 %67
%70 = OpGroupNonUniformBroadcastFirst %5 %47 %67
%71 = OpAccessChain %48 %13 %50 %70
%72 = OpLoad %9 %71
%73 = OpShiftRightLogical %9 %72 %74
%75 = OpAccessChain %40 %8 %58
%76 = OpLoad %5 %75
%77 = OpIAdd %5 %76 %58
%79 = OpAccessChain %78 %24 %77
%80 = OpGroupNonUniformBroadcastFirst %5 %47 %77
%81 = OpAccessChain %48 %13 %50 %80
%82 = OpLoad %9 %81
%83 = OpShiftRightLogical %9 %82 %65
%84 = OpAccessChain %40 %8 %58
%85 = OpLoad %5 %84
%87 = OpAccessChain %86 %18 %85
%88 = OpGroupNonUniformBroadcastFirst %5 %47 %85
%89 = OpAccessChain %48 %13 %50 %88
%90 = OpLoad %9 %89
%91 = OpShiftRightLogical %9 %90 %74
%96 = OpAccessChain %95 %94 %50
%97 = OpLoad %5 %96
%99 = OpAccessChain %95 %98 %50
%100 = OpLoad %5 %99
%101 = OpCompositeExtract %5 %91 0
%102 = OpCompositeExtract %5 %91 1
%103 = OpIAdd %5 %97 %101
%105 = OpULessThan %104 %97 %102
%106 = OpSelect %5 %105 %103 %107
%108 = OpAccessChain %48 %87 %50 %106
%109 = OpLoad %9 %108
%112 = OpBitcast %111 %109
%113 = OpCompositeExtract %110 %112 0
%114 = OpCompositeExtract %110 %112 1
%115 = OpCompositeExtract %5 %73 0
%116 = OpCompositeExtract %5 %73 1
%117 = OpIAdd %5 %97 %115
%118 = OpULessThan %104 %97 %116
%119 = OpSelect %5 %118 %117 %107
%120 = OpBitcast %5 %113
%121 = OpBitcast %5 %114
%122 = OpCompositeConstruct %9 %120 %121
%123 = OpAccessChain %48 %69 %50 %119
OpStore %123 %122
%124 = OpShiftLeftLogical %5 %97 %42
%134 = OpFunctionCall %5 %128 %97 %135
%136 = OpCompositeExtract %5 %83 0
%137 = OpCompositeExtract %5 %83 1
%138 = OpIAdd %5 %134 %136
%139 = OpULessThan %104 %134 %137
%140 = OpSelect %5 %139 %138 %141
%143 = OpAccessChain %142 %79 %50 %140
%144 = OpLoad %19 %143
%145 = OpCompositeExtract %5 %144 0
%146 = OpCompositeExtract %5 %144 1
%147 = OpCompositeExtract %5 %144 2
%148 = OpCompositeExtract %5 %144 3
%149 = OpFunctionCall %5 %128 %97 %135
%150 = OpCompositeExtract %5 %64 0
%151 = OpCompositeExtract %5 %64 1
%152 = OpIAdd %5 %149 %150
%153 = OpULessThan %104 %149 %151
%154 = OpSelect %5 %153 %152 %141
%155 = OpCompositeConstruct %19 %145 %146 %147 %148
%156 = OpAccessChain %142 %60 %50 %154
OpStore %156 %155
%157 = OpCompositeExtract %5 %91 0
%158 = OpCompositeExtract %5 %91 1
%159 = OpIAdd %5 %97 %157
%160 = OpULessThan %104 %97 %158
%161 = OpSelect %5 %160 %159 %107
%162 = OpAccessChain %48 %87 %50 %161
%163 = OpLoad %9 %162
%164 = OpBitcast %111 %163
%165 = OpCompositeExtract %110 %164 0
%166 = OpCompositeExtract %110 %164 1
%167 = OpCompositeExtract %5 %73 0
%168 = OpCompositeExtract %5 %73 1
%169 = OpIAdd %5 %97 %167
%170 = OpULessThan %104 %97 %168
%171 = OpSelect %5 %170 %169 %107
%172 = OpBitcast %5 %165
%173 = OpBitcast %5 %166
%174 = OpCompositeConstruct %9 %172 %173
%175 = OpAccessChain %48 %69 %50 %171
OpStore %175 %174
%176 = OpFunctionCall %5 %128 %97 %135
%177 = OpCompositeExtract %5 %83 0
%178 = OpCompositeExtract %5 %83 1
%179 = OpIAdd %5 %176 %177
%180 = OpULessThan %104 %176 %178
%181 = OpSelect %5 %180 %179 %141
%182 = OpAccessChain %142 %79 %50 %181
%183 = OpLoad %19 %182
%184 = OpCompositeExtract %5 %183 0
%185 = OpCompositeExtract %5 %183 1
%186 = OpCompositeExtract %5 %183 2
%187 = OpCompositeExtract %5 %183 3
%188 = OpFunctionCall %5 %128 %97 %135
%189 = OpCompositeExtract %5 %64 0
%190 = OpCompositeExtract %5 %64 1
%191 = OpIAdd %5 %188 %189
%192 = OpULessThan %104 %188 %190
%193 = OpSelect %5 %192 %191 %141
%194 = OpCompositeConstruct %19 %184 %185 %186 %187
%195 = OpAccessChain %142 %60 %50 %193
OpStore %195 %194
%196 = OpIAdd %5 %100 %53
%197 = OpAccessChain %40 %8 %58
%198 = OpLoad %5 %197
%199 = OpIAdd %5 %198 %196
%200 = OpAccessChain %86 %18 %199
%201 = OpGroupNonUniformBroadcastFirst %5 %47 %199
%202 = OpAccessChain %48 %13 %50 %201
%203 = OpLoad %9 %202
%204 = OpShiftRightLogical %9 %203 %74
%205 = OpCompositeExtract %5 %204 0
%206 = OpCompositeExtract %5 %204 1
%207 = OpIAdd %5 %97 %205
%208 = OpULessThan %104 %97 %206
%209 = OpSelect %5 %208 %207 %107
%210 = OpAccessChain %48 %200 %50 %209
%211 = OpLoad %9 %210
%212 = OpBitcast %111 %211
%213 = OpCompositeExtract %110 %212 0
%214 = OpCompositeExtract %110 %212 1
%215 = OpIAdd %5 %100 %50
%216 = OpAccessChain %40 %8 %42
%217 = OpLoad %5 %216
%218 = OpIAdd %5 %217 %215
%219 = OpAccessChain %68 %29 %218
%220 = OpGroupNonUniformBroadcastFirst %5 %47 %218
%221 = OpAccessChain %48 %13 %50 %220
%222 = OpLoad %9 %221
%223 = OpShiftRightLogical %9 %222 %74
%224 = OpCompositeExtract %5 %223 0
%225 = OpCompositeExtract %5 %223 1
%226 = OpIAdd %5 %97 %224
%227 = OpULessThan %104 %97 %225
%228 = OpSelect %5 %227 %226 %107
%229 = OpBitcast %5 %213
%230 = OpBitcast %5 %214
%231 = OpCompositeConstruct %9 %229 %230
%232 = OpAccessChain %48 %219 %50 %228
OpStore %232 %231
%233 = OpIAdd %5 %97 %53
%234 = OpAccessChain %40 %8 %58
%235 = OpLoad %5 %234
%236 = OpIAdd %5 %235 %233
%237 = OpAccessChain %86 %18 %236
%238 = OpAccessChain %48 %13 %50 %236
%239 = OpLoad %9 %238
%240 = OpShiftRightLogical %9 %239 %74
%241 = OpCompositeExtract %5 %240 0
%242 = OpCompositeExtract %5 %240 1
%243 = OpIAdd %5 %97 %241
%244 = OpULessThan %104 %97 %242
%245 = OpSelect %5 %244 %243 %107
%246 = OpAccessChain %48 %237 %50 %245
%247 = OpLoad %9 %246
%248 = OpBitcast %111 %247
%249 = OpCompositeExtract %110 %248 0
%250 = OpCompositeExtract %110 %248 1
%251 = OpIAdd %5 %97 %50
%252 = OpAccessChain %40 %8 %42
%253 = OpLoad %5 %252
%254 = OpIAdd %5 %253 %251
%255 = OpAccessChain %68 %29 %254
%256 = OpAccessChain %48 %13 %50 %254
%257 = OpLoad %9 %256
%258 = OpShiftRightLogical %9 %257 %74
%259 = OpCompositeExtract %5 %258 0
%260 = OpCompositeExtract %5 %258 1
%261 = OpIAdd %5 %97 %259
%262 = OpULessThan %104 %97 %260
%263 = OpSelect %5 %262 %261 %107
%264 = OpBitcast %5 %249
%265 = OpBitcast %5 %250
%266 = OpCompositeConstruct %9 %264 %265
%267 = OpAccessChain %48 %255 %50 %263
OpStore %267 %266
%268 = OpIAdd %5 %100 %47
%269 = OpAccessChain %40 %8 %58
%270 = OpLoad %5 %269
%271 = OpIAdd %5 %270 %268
%272 = OpAccessChain %78 %24 %271
%273 = OpGroupNonUniformBroadcastFirst %5 %47 %271
%274 = OpAccessChain %48 %13 %50 %273
%275 = OpLoad %9 %274
%276 = OpShiftRightLogical %9 %275 %65
%277 = OpFunctionCall %5 %128 %97 %135
%278 = OpCompositeExtract %5 %276 0
%279 = OpCompositeExtract %5 %276 1
%280 = OpIAdd %5 %277 %278
%281 = OpULessThan %104 %277 %279
%282 = OpSelect %5 %281 %280 %141
%283 = OpAccessChain %142 %272 %50 %282
%284 = OpLoad %19 %283
%285 = OpCompositeExtract %5 %284 0
%286 = OpCompositeExtract %5 %284 1
%287 = OpCompositeExtract %5 %284 2
%288 = OpCompositeExtract %5 %284 3
%289 = OpIAdd %5 %100 %58
%290 = OpAccessChain %40 %8 %42
%291 = OpLoad %5 %290
%292 = OpIAdd %5 %291 %289
%293 = OpAccessChain %59 %34 %292
%294 = OpGroupNonUniformBroadcastFirst %5 %47 %292
%295 = OpAccessChain %48 %13 %50 %294
%296 = OpLoad %9 %295
%297 = OpShiftRightLogical %9 %296 %65
%298 = OpFunctionCall %5 %128 %97 %135
%299 = OpCompositeExtract %5 %297 0
%300 = OpCompositeExtract %5 %297 1
%301 = OpIAdd %5 %298 %299
%302 = OpULessThan %104 %298 %300
%303 = OpSelect %5 %302 %301 %141
%304 = OpCompositeConstruct %19 %285 %286 %287 %288
%305 = OpAccessChain %142 %293 %50 %303
OpStore %305 %304
%306 = OpIAdd %5 %97 %47
%307 = OpAccessChain %40 %8 %58
%308 = OpLoad %5 %307
%309 = OpIAdd %5 %308 %306
%310 = OpAccessChain %78 %24 %309
%311 = OpAccessChain %48 %13 %50 %309
%312 = OpLoad %9 %311
%313 = OpShiftRightLogical %9 %312 %65
%314 = OpFunctionCall %5 %128 %97 %135
%315 = OpCompositeExtract %5 %313 0
%316 = OpCompositeExtract %5 %313 1
%317 = OpIAdd %5 %314 %315
%318 = OpULessThan %104 %314 %316
%319 = OpSelect %5 %318 %317 %141
%320 = OpAccessChain %142 %310 %50 %319
%321 = OpLoad %19 %320
%322 = OpCompositeExtract %5 %321 0
%323 = OpCompositeExtract %5 %321 1
%324 = OpCompositeExtract %5 %321 2
%325 = OpCompositeExtract %5 %321 3
%326 = OpIAdd %5 %97 %58
%327 = OpAccessChain %40 %8 %42
%328 = OpLoad %5 %327
%329 = OpIAdd %5 %328 %326
%330 = OpAccessChain %59 %34 %329
%331 = OpAccessChain %48 %13 %50 %329
%332 = OpLoad %9 %331
%333 = OpShiftRightLogical %9 %332 %65
%334 = OpFunctionCall %5 %128 %97 %135
%335 = OpCompositeExtract %5 %333 0
%336 = OpCompositeExtract %5 %333 1
%337 = OpIAdd %5 %334 %335
%338 = OpULessThan %104 %334 %336
%339 = OpSelect %5 %338 %337 %141
%340 = OpCompositeConstruct %19 %322 %323 %324 %325
%341 = OpAccessChain %142 %330 %50 %339
OpStore %341 %340
%342 = OpIMul %5 %97 %53
%343 = OpIAdd %5 %342 %58
%344 = OpCompositeExtract %5 %52 0
%345 = OpCompositeExtract %5 %52 1
%346 = OpIAdd %5 %343 %344
%347 = OpULessThan %104 %343 %345
%348 = OpSelect %5 %347 %346 %349
%351 = OpAccessChain %350 %45 %50 %348
%352 = OpAtomicIAdd %5 %351 %58 %50 %58
%353 = OpCompositeExtract %5 %73 1
%354 = OpUDiv %5 %353 %58
%355 = OpIMul %5 %97 %53
%356 = OpCompositeExtract %5 %52 0
%357 = OpCompositeExtract %5 %52 1
%358 = OpIAdd %5 %355 %356
%359 = OpULessThan %104 %355 %357
%360 = OpSelect %5 %359 %358 %349
%361 = OpAccessChain %350 %45 %50 %360
%362 = OpAtomicIAdd %5 %361 %58 %50 %354
OpReturn
OpFunctionEnd
%128 = OpFunction %5 None %125
%126 = OpFunctionParameter %5
%127 = OpFunctionParameter %5
%129 = OpLabel
%130 = OpUDiv %5 %131 %127
%132 = OpBitwiseAnd %5 %126 %130
OpReturnValue %132
OpFunctionEnd
#endif
