#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_EXT_shader_explicit_arithmetic_types_float16)
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#else
#error No extension available for FP16.
#endif
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_KHR_shader_subgroup_ballot : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 15, binding = 0, std430) restrict readonly buffer SSBO_Offsets
{
    uvec2 _m0[];
} _13;

layout(set = 4, binding = 0, std430) buffer SSBO
{
    uint16_t _m0[];
} _19[];

layout(set = 4, binding = 0, std430) buffer _22_25
{
    u16vec2 _m0[];
} _25[];

layout(set = 4, binding = 0, std430) buffer _28_31
{
    u16vec4 _m0[];
} _31[];

layout(set = 4, binding = 0, std430) buffer _33_36
{
    uint16_t _m0[];
} _36[];

layout(set = 4, binding = 0, std430) buffer _38_41
{
    u16vec2 _m0[];
} _41[];

layout(set = 4, binding = 0, std430) buffer _43_46
{
    u16vec4 _m0[];
} _46[];

layout(set = 4, binding = 0, std430) buffer _48_51
{
    uint _m0[];
} _51[];

layout(set = 4, binding = 0, std430) buffer _54_57
{
    uvec4 _m0[];
} _57[];

layout(set = 4, binding = 0, std430) writeonly buffer _59_62
{
    uint16_t _m0[];
} _62[];

layout(set = 4, binding = 0, std430) writeonly buffer _64_67
{
    u16vec2 _m0[];
} _67[];

layout(set = 4, binding = 0, std430) writeonly buffer _69_72
{
    u16vec4 _m0[];
} _72[];

layout(push_constant, std430) uniform RootConstants
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
    uint _m5;
    uint _m6;
    uint _m7;
} registers;

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _77 = registers._m4 + 6u;
    uint _85 = subgroupBroadcastFirst(_77);
    uint _93 = registers._m4 + 5u;
    uint _98 = subgroupBroadcastFirst(_93);
    uint _103 = registers._m4 + 4u;
    uint _114 = subgroupBroadcastFirst(_103);
    uint _119 = registers._m4 + 3u;
    uvec2 _125 = _13._m0[subgroupBroadcastFirst(_119)] >> uvec2(3u);
    uint _129 = registers._m4 + 2u;
    uvec2 _136 = _13._m0[subgroupBroadcastFirst(_129)] >> uvec2(1u);
    uint _141 = registers._m4 + 1u;
    uvec2 _147 = _13._m0[subgroupBroadcastFirst(_141)] >> uvec2(2u);
    uvec2 _155 = _13._m0[subgroupBroadcastFirst(registers._m4)] >> uvec2(1u);
    _19[registers._m4]._m0[(gl_GlobalInvocationID.x < _155.y) ? (gl_GlobalInvocationID.x + _155.x) : 2147483644u] = float16BitsToUint16(uint16BitsToFloat16(_19[registers._m4]._m0[(gl_GlobalInvocationID.x < _155.y) ? (gl_GlobalInvocationID.x + _155.x) : 2147483644u]) + float16_t(1.0));
    uint _187 = (gl_GlobalInvocationID.x < _147.y) ? (gl_GlobalInvocationID.x + _147.x) : 1073741823u;
    _25[_141]._m0[(gl_GlobalInvocationID.x < _147.y) ? (gl_GlobalInvocationID.x + _147.x) : 1073741823u] = u16vec2(_25[_141]._m0[_187].x + 2us, _25[_141]._m0[_187].y + 2us);
    uint _204 = gl_GlobalInvocationID.x * 3u;
    uint _209 = (_204 < _136.y) ? (_204 + _136.x) : 2147483644u;
    uint16_t _211 = _19[_129]._m0[_209];
    uint16_t _214 = _19[_129]._m0[_209 + 1u];
    uint16_t _217 = _19[_129]._m0[_209 + 2u];
    f16vec3 _221 = uint16BitsToFloat16(u16vec3(_211, _214, _217));
    uint _229 = gl_GlobalInvocationID.x * 3u;
    uint _234 = (_229 < _136.y) ? (_229 + _136.x) : 2147483644u;
    _19[_129]._m0[_234] = float16BitsToUint16(_221.x + float16_t(3.0));
    _19[_129]._m0[_234 + 1u] = float16BitsToUint16(_221.y + float16_t(3.0));
    _19[_129]._m0[_234 + 2u] = float16BitsToUint16(_221.z + float16_t(3.0));
    uint _247 = (gl_GlobalInvocationID.x < _125.y) ? (gl_GlobalInvocationID.x + _125.x) : 536870911u;
    _31[_119]._m0[(gl_GlobalInvocationID.x < _125.y) ? (gl_GlobalInvocationID.x + _125.x) : 536870911u] = u16vec4(_31[_119]._m0[_247].x + 4us, _31[_119]._m0[_247].y + 4us, _31[_119]._m0[_247].z + 4us, _31[_119]._m0[_247].w + 4us);
    uint _278 = ByteAddressMask(gl_GlobalInvocationID.x, 2u);
    uvec2 _279 = _13._m0[_114] >> uvec2(1u);
    uint16_t _286 = _36[_103]._m0[(_278 < _279.y) ? (_278 + _279.x) : 2147483644u];
    float _289 = float(uint16BitsToFloat16(_286));
    uint _291 = ByteAddressMask(gl_GlobalInvocationID.x, 4u);
    uvec2 _292 = _13._m0[_114] >> uvec2(2u);
    u16vec2 _299 = _41[_103]._m0[(_291 < _292.y) ? (_291 + _292.x) : 1073741823u];
    f16vec2 _301 = uint16BitsToFloat16(_299);
    float _305 = float(_301.y);
    uint _309 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 2u);
    uvec2 _310 = _13._m0[_114] >> uvec2(1u);
    uint _315 = (_309 < _310.y) ? (_309 + _310.x) : 2147483644u;
    uint16_t _317 = _36[_103]._m0[_315];
    uint16_t _320 = _36[_103]._m0[_315 + 1u];
    uint16_t _323 = _36[_103]._m0[_315 + 2u];
    f16vec3 _325 = uint16BitsToFloat16(u16vec3(_317, _320, _323));
    float _329 = float(_325.x);
    uint _334 = ByteAddressMask(gl_GlobalInvocationID.x, 8u);
    uvec2 _336 = _13._m0[_114] >> uvec2(3u);
    u16vec4 _343 = _46[_103]._m0[(_334 < _336.y) ? (_334 + _336.x) : 536870911u];
    f16vec4 _345 = uint16BitsToFloat16(_343);
    uint _355 = ByteAddressMask(gl_GlobalInvocationID.x, 2u);
    uvec2 _356 = _13._m0[_114] >> uvec2(1u);
    uint16_t _363 = _36[_103]._m0[(_355 < _356.y) ? (_355 + _356.x) : 2147483644u];
    float _364 = float(_363);
    uint _366 = ByteAddressMask(gl_GlobalInvocationID.x, 4u);
    uvec2 _367 = _13._m0[_114] >> uvec2(2u);
    uint _372 = (_366 < _367.y) ? (_366 + _367.x) : 1073741823u;
    u16vec2 _374 = _41[_103]._m0[_372];
    float _378 = float(_374.y);
    uint _381 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 2u);
    uvec2 _382 = _13._m0[_114] >> uvec2(1u);
    uint _387 = (_381 < _382.y) ? (_381 + _382.x) : 2147483644u;
    uint16_t _389 = _36[_103]._m0[_387];
    uint16_t _392 = _36[_103]._m0[_387 + 1u];
    uint16_t _395 = _36[_103]._m0[_387 + 2u];
    u16vec3 _396 = u16vec3(_389, _392, _395);
    float _400 = float(_396.x);
    uint _404 = ByteAddressMask(gl_GlobalInvocationID.x, 8u);
    uvec2 _405 = _13._m0[_114] >> uvec2(3u);
    uint _410 = (_404 < _405.y) ? (_404 + _405.x) : 536870911u;
    u16vec4 _412 = _46[_103]._m0[_410];
    uint _422 = ByteAddressMask(gl_GlobalInvocationID.x, 2u);
    uvec2 _423 = _13._m0[_98] >> uvec2(1u);
    _62[_93]._m0[(_422 < _423.y) ? (_422 + _423.x) : 2147483644u] = float16BitsToUint16(float16_t(1.0));
    uint _431 = ByteAddressMask(gl_GlobalInvocationID.x, 4u);
    uvec2 _432 = _13._m0[_98] >> uvec2(2u);
    _67[_93]._m0[(_431 < _432.y) ? (_431 + _432.x) : 1073741823u] = u16vec2(float16BitsToUint16(float16_t(2.0)), float16BitsToUint16(float16_t(4.0)));
    uint _445 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 2u);
    uvec2 _446 = _13._m0[_98] >> uvec2(1u);
    uint _451 = (_445 < _446.y) ? (_445 + _446.x) : 2147483644u;
    _62[_93]._m0[_451] = float16BitsToUint16(float16_t(4.0));
    _62[_93]._m0[_451 + 1u] = float16BitsToUint16(float16_t(5.0));
    _62[_93]._m0[_451 + 2u] = float16BitsToUint16(float16_t(6.0));
    uint _462 = ByteAddressMask(gl_GlobalInvocationID.x, 8u);
    uvec2 _463 = _13._m0[_98] >> uvec2(3u);
    _72[_93]._m0[(_462 < _463.y) ? (_462 + _463.x) : 536870911u] = u16vec4(float16BitsToUint16(float16_t(7.0)), float16BitsToUint16(float16_t(8.0)), float16BitsToUint16(float16_t(9.0)), float16BitsToUint16(float16_t(10.0)));
    uint _479 = ByteAddressMask(gl_GlobalInvocationID.x, 2u);
    uvec2 _480 = _13._m0[_85] >> uvec2(1u);
    _62[_77]._m0[(_479 < _480.y) ? (_479 + _480.x) : 2147483644u] = 1us;
    uint _488 = ByteAddressMask(gl_GlobalInvocationID.x, 4u);
    uvec2 _489 = _13._m0[_85] >> uvec2(2u);
    _67[_77]._m0[(_488 < _489.y) ? (_488 + _489.x) : 1073741823u] = u16vec2(2us, 4us);
    uint _498 = ByteAddressMask(gl_GlobalInvocationID.x * 3u, 2u);
    uvec2 _499 = _13._m0[_85] >> uvec2(1u);
    uint _504 = (_498 < _499.y) ? (_498 + _499.x) : 2147483644u;
    _62[_77]._m0[_504] = 4us;
    _62[_77]._m0[_504 + 1u] = 5us;
    _62[_77]._m0[_504 + 2u] = 6us;
    uint _512 = ByteAddressMask(gl_GlobalInvocationID.x, 8u);
    uvec2 _513 = _13._m0[_85] >> uvec2(3u);
    _72[_77]._m0[(_512 < _513.y) ? (_512 + _513.x) : 536870911u] = u16vec4(7us, 8us, 9us, 10us);
    uint _525 = ByteAddressMask(gl_GlobalInvocationID.x, 4u);
    uvec2 _526 = _13._m0[_114] >> uvec2(2u);
    uint _535 = _51[_103]._m0[(_525 < _526.y) ? (_525 + _526.x) : 1073741820u];
    float _536 = uintBitsToFloat(_535);
    uint _541 = registers._m4 + (gl_GlobalInvocationID.x + 0u);
    uint _547 = ByteAddressMask(gl_GlobalInvocationID.x * 2u, 2u);
    uvec2 _548 = _13._m0[_541] >> uvec2(1u);
    uint16_t _555 = _36[nonuniformEXT(_541)]._m0[(_547 < _548.y) ? (_547 + _548.x) : 2147483644u];
    float _557 = float(uint16BitsToFloat16(_555));
    float _560 = ((float(_301.x) + _289) + _364) + float(_374.x);
    float _566 = (((((_560 + _329) + float(_345.x)) + _400) + float(_412.x)) + _536) + _557;
    float _572 = (((((_560 + float(_325.y)) + float(_345.y)) + float(_396.y)) + float(_412.y)) + _536) + _557;
    uint _577 = ByteAddressMask(gl_GlobalInvocationID.x * 2u, 4u);
    uvec2 _578 = _13._m0[_541] >> uvec2(2u);
    _41[nonuniformEXT(_541)]._m0[(_577 < _578.y) ? (_577 + _578.x) : 1073741823u] = u16vec2(float16BitsToUint16(float16_t(_566)), float16BitsToUint16(float16_t(_572)));
    uint _618 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uvec2 _620 = _13._m0[_114] >> uvec2(4u);
    _57[_103]._m0[(_618 < _620.y) ? (_618 + _620.x) : 268435455u] = uvec4(uint((float(_155.y / 1u) + _566) + float(_13._m0[_98].y * 8u)), uint(_572 + 2.0), uint((((((((((_305 + _289) + float(_325.z)) + float(_345.z)) + _364) + _378) + float(_396.z)) + float(_412.z)) + _536) + _557) + float(_125.y / 1u)), uint((((((((((_289 + 8.0) + _305) + _329) + float(_345.w)) + _364) + _378) + _400) + float(_412.w)) + _536) + _557));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 633
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability Int16
OpCapability StorageBufferArrayDynamicIndexing
OpCapability ImageQuery
OpCapability GroupNonUniformBallot
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpCapability RuntimeDescriptorArray
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability PhysicalStorageBufferAddresses
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_KHR_physical_storage_buffer"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %158
OpExecutionMode %3 LocalSize 64 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %11 "SSBO_Offsets"
OpName %16 "SSBO"
OpName %22 "SSBO"
OpName %28 "SSBO"
OpName %33 "SSBO"
OpName %38 "SSBO"
OpName %43 "SSBO"
OpName %48 "SSBO"
OpName %54 "SSBO"
OpName %59 "SSBO"
OpName %64 "SSBO"
OpName %69 "SSBO"
OpName %272 "ByteAddressMask"
OpName %270 "index"
OpName %271 "stride"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpDecorate %10 ArrayStride 8
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 15
OpDecorate %13 Binding 0
OpDecorate %13 NonWritable
OpDecorate %13 Restrict
OpDecorate %15 ArrayStride 2
OpMemberDecorate %16 0 Offset 0
OpDecorate %16 Block
OpDecorate %19 DescriptorSet 4
OpDecorate %19 Binding 0
OpDecorate %21 ArrayStride 4
OpMemberDecorate %22 0 Offset 0
OpDecorate %22 Block
OpDecorate %25 DescriptorSet 4
OpDecorate %25 Binding 0
OpDecorate %27 ArrayStride 8
OpMemberDecorate %28 0 Offset 0
OpDecorate %28 Block
OpDecorate %31 DescriptorSet 4
OpDecorate %31 Binding 0
OpDecorate %32 ArrayStride 2
OpMemberDecorate %33 0 Offset 0
OpDecorate %33 Block
OpDecorate %36 DescriptorSet 4
OpDecorate %36 Binding 0
OpDecorate %36 Aliased
OpDecorate %37 ArrayStride 4
OpMemberDecorate %38 0 Offset 0
OpDecorate %38 Block
OpDecorate %41 DescriptorSet 4
OpDecorate %41 Binding 0
OpDecorate %41 Aliased
OpDecorate %42 ArrayStride 8
OpMemberDecorate %43 0 Offset 0
OpDecorate %43 Block
OpDecorate %46 DescriptorSet 4
OpDecorate %46 Binding 0
OpDecorate %46 Aliased
OpDecorate %47 ArrayStride 4
OpMemberDecorate %48 0 Offset 0
OpDecorate %48 Block
OpDecorate %51 DescriptorSet 4
OpDecorate %51 Binding 0
OpDecorate %51 Aliased
OpDecorate %53 ArrayStride 16
OpMemberDecorate %54 0 Offset 0
OpDecorate %54 Block
OpDecorate %57 DescriptorSet 4
OpDecorate %57 Binding 0
OpDecorate %57 Aliased
OpDecorate %58 ArrayStride 2
OpMemberDecorate %59 0 Offset 0
OpDecorate %59 Block
OpDecorate %62 DescriptorSet 4
OpDecorate %62 Binding 0
OpDecorate %62 NonReadable
OpDecorate %62 Aliased
OpDecorate %63 ArrayStride 4
OpMemberDecorate %64 0 Offset 0
OpDecorate %64 Block
OpDecorate %67 DescriptorSet 4
OpDecorate %67 Binding 0
OpDecorate %67 NonReadable
OpDecorate %67 Aliased
OpDecorate %68 ArrayStride 8
OpMemberDecorate %69 0 Offset 0
OpDecorate %69 Block
OpDecorate %72 DescriptorSet 4
OpDecorate %72 Binding 0
OpDecorate %72 NonReadable
OpDecorate %72 Aliased
OpDecorate %158 BuiltIn GlobalInvocationId
OpDecorate %541 NonUniform
OpDecorate %542 NonUniform
OpDecorate %543 NonUniform
OpDecorate %554 NonUniform
OpDecorate %587 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeVector %5 2
%10 = OpTypeRuntimeArray %9
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeInt 16 0
%15 = OpTypeRuntimeArray %14
%16 = OpTypeStruct %15
%17 = OpTypeRuntimeArray %16
%18 = OpTypePointer StorageBuffer %17
%19 = OpVariable %18 StorageBuffer
%20 = OpTypeVector %14 2
%21 = OpTypeRuntimeArray %20
%22 = OpTypeStruct %21
%23 = OpTypeRuntimeArray %22
%24 = OpTypePointer StorageBuffer %23
%25 = OpVariable %24 StorageBuffer
%26 = OpTypeVector %14 4
%27 = OpTypeRuntimeArray %26
%28 = OpTypeStruct %27
%29 = OpTypeRuntimeArray %28
%30 = OpTypePointer StorageBuffer %29
%31 = OpVariable %30 StorageBuffer
%32 = OpTypeRuntimeArray %14
%33 = OpTypeStruct %32
%34 = OpTypeRuntimeArray %33
%35 = OpTypePointer StorageBuffer %34
%36 = OpVariable %35 StorageBuffer
%37 = OpTypeRuntimeArray %20
%38 = OpTypeStruct %37
%39 = OpTypeRuntimeArray %38
%40 = OpTypePointer StorageBuffer %39
%41 = OpVariable %40 StorageBuffer
%42 = OpTypeRuntimeArray %26
%43 = OpTypeStruct %42
%44 = OpTypeRuntimeArray %43
%45 = OpTypePointer StorageBuffer %44
%46 = OpVariable %45 StorageBuffer
%47 = OpTypeRuntimeArray %5
%48 = OpTypeStruct %47
%49 = OpTypeRuntimeArray %48
%50 = OpTypePointer StorageBuffer %49
%51 = OpVariable %50 StorageBuffer
%52 = OpTypeVector %5 4
%53 = OpTypeRuntimeArray %52
%54 = OpTypeStruct %53
%55 = OpTypeRuntimeArray %54
%56 = OpTypePointer StorageBuffer %55
%57 = OpVariable %56 StorageBuffer
%58 = OpTypeRuntimeArray %14
%59 = OpTypeStruct %58
%60 = OpTypeRuntimeArray %59
%61 = OpTypePointer StorageBuffer %60
%62 = OpVariable %61 StorageBuffer
%63 = OpTypeRuntimeArray %20
%64 = OpTypeStruct %63
%65 = OpTypeRuntimeArray %64
%66 = OpTypePointer StorageBuffer %65
%67 = OpVariable %66 StorageBuffer
%68 = OpTypeRuntimeArray %26
%69 = OpTypeStruct %68
%70 = OpTypeRuntimeArray %69
%71 = OpTypePointer StorageBuffer %70
%72 = OpVariable %71 StorageBuffer
%73 = OpTypePointer PushConstant %5
%75 = OpConstant %5 4
%78 = OpConstant %5 6
%79 = OpTypePointer StorageBuffer %59
%81 = OpTypePointer StorageBuffer %64
%83 = OpTypePointer StorageBuffer %69
%86 = OpConstant %5 3
%87 = OpTypePointer StorageBuffer %9
%89 = OpConstant %5 0
%94 = OpConstant %5 5
%104 = OpTypePointer StorageBuffer %33
%106 = OpTypePointer StorageBuffer %38
%108 = OpTypePointer StorageBuffer %43
%110 = OpTypePointer StorageBuffer %48
%112 = OpTypePointer StorageBuffer %54
%120 = OpTypePointer StorageBuffer %28
%126 = OpConstantComposite %9 %86 %86
%130 = OpConstant %5 2
%131 = OpTypePointer StorageBuffer %16
%137 = OpConstant %5 1
%138 = OpConstantComposite %9 %137 %137
%142 = OpTypePointer StorageBuffer %22
%148 = OpConstantComposite %9 %130 %130
%156 = OpTypeVector %5 3
%157 = OpTypePointer Input %156
%158 = OpVariable %157 Input
%159 = OpTypePointer Input %5
%165 = OpTypeBool
%168 = OpConstant %5 2147483644
%169 = OpTypePointer StorageBuffer %14
%172 = OpTypeFloat 16
%175 = OpConstant %172 0x1p+0
%188 = OpConstant %5 1073741823
%189 = OpTypePointer StorageBuffer %20
%195 = OpConstant %14 2
%218 = OpTypeVector %14 3
%220 = OpTypeVector %172 3
%226 = OpConstant %172 0x1.8p+1
%248 = OpConstant %5 536870911
%249 = OpTypePointer StorageBuffer %26
%257 = OpConstant %14 4
%269 = OpTypeFunction %5 %5 %5
%275 = OpConstant %5 4294967295
%288 = OpTypeFloat 32
%300 = OpTypeVector %172 2
%335 = OpConstant %5 8
%344 = OpTypeVector %172 4
%438 = OpConstant %172 0x1p+1
%440 = OpConstant %172 0x1p+2
%453 = OpConstant %172 0x1.4p+2
%455 = OpConstant %172 0x1.8p+2
%469 = OpConstant %172 0x1.cp+2
%471 = OpConstant %172 0x1p+3
%473 = OpConstant %172 0x1.2p+3
%475 = OpConstant %172 0x1.4p+3
%486 = OpConstant %14 1
%505 = OpConstant %14 5
%506 = OpConstant %14 6
%519 = OpConstant %14 7
%520 = OpConstant %14 8
%521 = OpConstant %14 9
%522 = OpConstant %14 10
%532 = OpConstant %5 1073741820
%533 = OpTypePointer StorageBuffer %5
%593 = OpConstant %288 2
%599 = OpConstant %288 8
%619 = OpConstant %5 16
%621 = OpConstantComposite %9 %75 %75
%627 = OpConstant %5 268435455
%629 = OpTypePointer StorageBuffer %52
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %631
%631 = OpLabel
%74 = OpAccessChain %73 %8 %75
%76 = OpLoad %5 %74
%77 = OpIAdd %5 %76 %78
%80 = OpAccessChain %79 %62 %77
%82 = OpAccessChain %81 %67 %77
%84 = OpAccessChain %83 %72 %77
%85 = OpGroupNonUniformBroadcastFirst %5 %86 %77
%88 = OpAccessChain %87 %13 %89 %85
%90 = OpLoad %9 %88
%91 = OpAccessChain %73 %8 %75
%92 = OpLoad %5 %91
%93 = OpIAdd %5 %92 %94
%95 = OpAccessChain %79 %62 %93
%96 = OpAccessChain %81 %67 %93
%97 = OpAccessChain %83 %72 %93
%98 = OpGroupNonUniformBroadcastFirst %5 %86 %93
%99 = OpAccessChain %87 %13 %89 %98
%100 = OpLoad %9 %99
%101 = OpAccessChain %73 %8 %75
%102 = OpLoad %5 %101
%103 = OpIAdd %5 %102 %75
%105 = OpAccessChain %104 %36 %103
%107 = OpAccessChain %106 %41 %103
%109 = OpAccessChain %108 %46 %103
%111 = OpAccessChain %110 %51 %103
%113 = OpAccessChain %112 %57 %103
%114 = OpGroupNonUniformBroadcastFirst %5 %86 %103
%115 = OpAccessChain %87 %13 %89 %114
%116 = OpLoad %9 %115
%117 = OpAccessChain %73 %8 %75
%118 = OpLoad %5 %117
%119 = OpIAdd %5 %118 %86
%121 = OpAccessChain %120 %31 %119
%122 = OpGroupNonUniformBroadcastFirst %5 %86 %119
%123 = OpAccessChain %87 %13 %89 %122
%124 = OpLoad %9 %123
%125 = OpShiftRightLogical %9 %124 %126
%127 = OpAccessChain %73 %8 %75
%128 = OpLoad %5 %127
%129 = OpIAdd %5 %128 %130
%132 = OpAccessChain %131 %19 %129
%133 = OpGroupNonUniformBroadcastFirst %5 %86 %129
%134 = OpAccessChain %87 %13 %89 %133
%135 = OpLoad %9 %134
%136 = OpShiftRightLogical %9 %135 %138
%139 = OpAccessChain %73 %8 %75
%140 = OpLoad %5 %139
%141 = OpIAdd %5 %140 %137
%143 = OpAccessChain %142 %25 %141
%144 = OpGroupNonUniformBroadcastFirst %5 %86 %141
%145 = OpAccessChain %87 %13 %89 %144
%146 = OpLoad %9 %145
%147 = OpShiftRightLogical %9 %146 %148
%149 = OpAccessChain %73 %8 %75
%150 = OpLoad %5 %149
%151 = OpAccessChain %131 %19 %150
%152 = OpGroupNonUniformBroadcastFirst %5 %86 %150
%153 = OpAccessChain %87 %13 %89 %152
%154 = OpLoad %9 %153
%155 = OpShiftRightLogical %9 %154 %138
%160 = OpAccessChain %159 %158 %89
%161 = OpLoad %5 %160
%162 = OpCompositeExtract %5 %155 0
%163 = OpCompositeExtract %5 %155 1
%164 = OpIAdd %5 %161 %162
%166 = OpULessThan %165 %161 %163
%167 = OpSelect %5 %166 %164 %168
%170 = OpAccessChain %169 %151 %89 %167
%171 = OpLoad %14 %170
%173 = OpBitcast %172 %171
%174 = OpFAdd %172 %173 %175
%176 = OpCompositeExtract %5 %155 0
%177 = OpCompositeExtract %5 %155 1
%178 = OpIAdd %5 %161 %176
%179 = OpULessThan %165 %161 %177
%180 = OpSelect %5 %179 %178 %168
%181 = OpBitcast %14 %174
%182 = OpAccessChain %169 %151 %89 %180
OpStore %182 %181
%183 = OpCompositeExtract %5 %147 0
%184 = OpCompositeExtract %5 %147 1
%185 = OpIAdd %5 %161 %183
%186 = OpULessThan %165 %161 %184
%187 = OpSelect %5 %186 %185 %188
%190 = OpAccessChain %189 %143 %89 %187
%191 = OpLoad %20 %190
%192 = OpCompositeExtract %14 %191 0
%193 = OpCompositeExtract %14 %191 1
%194 = OpIAdd %14 %192 %195
%196 = OpIAdd %14 %193 %195
%197 = OpCompositeExtract %5 %147 0
%198 = OpCompositeExtract %5 %147 1
%199 = OpIAdd %5 %161 %197
%200 = OpULessThan %165 %161 %198
%201 = OpSelect %5 %200 %199 %188
%202 = OpCompositeConstruct %20 %194 %196
%203 = OpAccessChain %189 %143 %89 %201
OpStore %203 %202
%204 = OpIMul %5 %161 %86
%205 = OpCompositeExtract %5 %136 0
%206 = OpCompositeExtract %5 %136 1
%207 = OpIAdd %5 %204 %205
%208 = OpULessThan %165 %204 %206
%209 = OpSelect %5 %208 %207 %168
%210 = OpAccessChain %169 %132 %89 %209
%211 = OpLoad %14 %210
%213 = OpIAdd %5 %209 %137
%212 = OpAccessChain %169 %132 %89 %213
%214 = OpLoad %14 %212
%216 = OpIAdd %5 %209 %130
%215 = OpAccessChain %169 %132 %89 %216
%217 = OpLoad %14 %215
%219 = OpCompositeConstruct %218 %211 %214 %217
%221 = OpBitcast %220 %219
%222 = OpCompositeExtract %172 %221 0
%223 = OpCompositeExtract %172 %221 1
%224 = OpCompositeExtract %172 %221 2
%225 = OpFAdd %172 %222 %226
%227 = OpFAdd %172 %223 %226
%228 = OpFAdd %172 %224 %226
%229 = OpIMul %5 %161 %86
%230 = OpCompositeExtract %5 %136 0
%231 = OpCompositeExtract %5 %136 1
%232 = OpIAdd %5 %229 %230
%233 = OpULessThan %165 %229 %231
%234 = OpSelect %5 %233 %232 %168
%235 = OpBitcast %14 %225
%236 = OpBitcast %14 %227
%237 = OpBitcast %14 %228
%238 = OpAccessChain %169 %132 %89 %234
OpStore %238 %235
%240 = OpIAdd %5 %234 %137
%239 = OpAccessChain %169 %132 %89 %240
OpStore %239 %236
%242 = OpIAdd %5 %234 %130
%241 = OpAccessChain %169 %132 %89 %242
OpStore %241 %237
%243 = OpCompositeExtract %5 %125 0
%244 = OpCompositeExtract %5 %125 1
%245 = OpIAdd %5 %161 %243
%246 = OpULessThan %165 %161 %244
%247 = OpSelect %5 %246 %245 %248
%250 = OpAccessChain %249 %121 %89 %247
%251 = OpLoad %26 %250
%252 = OpCompositeExtract %14 %251 0
%253 = OpCompositeExtract %14 %251 1
%254 = OpCompositeExtract %14 %251 2
%255 = OpCompositeExtract %14 %251 3
%256 = OpIAdd %14 %252 %257
%258 = OpIAdd %14 %253 %257
%259 = OpIAdd %14 %254 %257
%260 = OpIAdd %14 %255 %257
%261 = OpCompositeExtract %5 %125 0
%262 = OpCompositeExtract %5 %125 1
%263 = OpIAdd %5 %161 %261
%264 = OpULessThan %165 %161 %262
%265 = OpSelect %5 %264 %263 %248
%266 = OpCompositeConstruct %26 %256 %258 %259 %260
%267 = OpAccessChain %249 %121 %89 %265
OpStore %267 %266
%268 = OpShiftLeftLogical %5 %161 %137
%278 = OpFunctionCall %5 %272 %161 %130
%279 = OpShiftRightLogical %9 %116 %138
%280 = OpCompositeExtract %5 %279 0
%281 = OpCompositeExtract %5 %279 1
%282 = OpIAdd %5 %278 %280
%283 = OpULessThan %165 %278 %281
%284 = OpSelect %5 %283 %282 %168
%285 = OpAccessChain %169 %105 %89 %284
%286 = OpLoad %14 %285
%287 = OpBitcast %172 %286
%289 = OpFConvert %288 %287
%290 = OpShiftLeftLogical %5 %161 %130
%291 = OpFunctionCall %5 %272 %161 %75
%292 = OpShiftRightLogical %9 %116 %148
%293 = OpCompositeExtract %5 %292 0
%294 = OpCompositeExtract %5 %292 1
%295 = OpIAdd %5 %291 %293
%296 = OpULessThan %165 %291 %294
%297 = OpSelect %5 %296 %295 %188
%298 = OpAccessChain %189 %107 %89 %297
%299 = OpLoad %20 %298
%301 = OpBitcast %300 %299
%302 = OpCompositeExtract %172 %301 0
%303 = OpCompositeExtract %172 %301 1
%304 = OpFConvert %288 %302
%305 = OpFConvert %288 %303
%306 = OpFAdd %288 %305 %289
%307 = OpIMul %5 %161 %78
%308 = OpIMul %5 %161 %86
%309 = OpFunctionCall %5 %272 %308 %130
%310 = OpShiftRightLogical %9 %116 %138
%311 = OpCompositeExtract %5 %310 0
%312 = OpCompositeExtract %5 %310 1
%313 = OpIAdd %5 %309 %311
%314 = OpULessThan %165 %309 %312
%315 = OpSelect %5 %314 %313 %168
%316 = OpAccessChain %169 %105 %89 %315
%317 = OpLoad %14 %316
%319 = OpIAdd %5 %315 %137
%318 = OpAccessChain %169 %105 %89 %319
%320 = OpLoad %14 %318
%322 = OpIAdd %5 %315 %130
%321 = OpAccessChain %169 %105 %89 %322
%323 = OpLoad %14 %321
%324 = OpCompositeConstruct %218 %317 %320 %323
%325 = OpBitcast %220 %324
%326 = OpCompositeExtract %172 %325 0
%327 = OpCompositeExtract %172 %325 1
%328 = OpCompositeExtract %172 %325 2
%329 = OpFConvert %288 %326
%330 = OpFConvert %288 %327
%331 = OpFConvert %288 %328
%332 = OpFAdd %288 %306 %331
%333 = OpShiftLeftLogical %5 %161 %86
%334 = OpFunctionCall %5 %272 %161 %335
%336 = OpShiftRightLogical %9 %116 %126
%337 = OpCompositeExtract %5 %336 0
%338 = OpCompositeExtract %5 %336 1
%339 = OpIAdd %5 %334 %337
%340 = OpULessThan %165 %334 %338
%341 = OpSelect %5 %340 %339 %248
%342 = OpAccessChain %249 %109 %89 %341
%343 = OpLoad %26 %342
%345 = OpBitcast %344 %343
%346 = OpCompositeExtract %172 %345 0
%347 = OpCompositeExtract %172 %345 1
%348 = OpCompositeExtract %172 %345 2
%349 = OpCompositeExtract %172 %345 3
%350 = OpFConvert %288 %346
%351 = OpFConvert %288 %347
%352 = OpFConvert %288 %348
%353 = OpFConvert %288 %349
%354 = OpFAdd %288 %332 %352
%355 = OpFunctionCall %5 %272 %161 %130
%356 = OpShiftRightLogical %9 %116 %138
%357 = OpCompositeExtract %5 %356 0
%358 = OpCompositeExtract %5 %356 1
%359 = OpIAdd %5 %355 %357
%360 = OpULessThan %165 %355 %358
%361 = OpSelect %5 %360 %359 %168
%362 = OpAccessChain %169 %105 %89 %361
%363 = OpLoad %14 %362
%364 = OpConvertUToF %288 %363
%365 = OpFAdd %288 %354 %364
%366 = OpFunctionCall %5 %272 %161 %75
%367 = OpShiftRightLogical %9 %116 %148
%368 = OpCompositeExtract %5 %367 0
%369 = OpCompositeExtract %5 %367 1
%370 = OpIAdd %5 %366 %368
%371 = OpULessThan %165 %366 %369
%372 = OpSelect %5 %371 %370 %188
%373 = OpAccessChain %189 %107 %89 %372
%374 = OpLoad %20 %373
%375 = OpCompositeExtract %14 %374 0
%376 = OpCompositeExtract %14 %374 1
%377 = OpConvertUToF %288 %375
%378 = OpConvertUToF %288 %376
%379 = OpFAdd %288 %365 %378
%380 = OpIMul %5 %161 %86
%381 = OpFunctionCall %5 %272 %380 %130
%382 = OpShiftRightLogical %9 %116 %138
%383 = OpCompositeExtract %5 %382 0
%384 = OpCompositeExtract %5 %382 1
%385 = OpIAdd %5 %381 %383
%386 = OpULessThan %165 %381 %384
%387 = OpSelect %5 %386 %385 %168
%388 = OpAccessChain %169 %105 %89 %387
%389 = OpLoad %14 %388
%391 = OpIAdd %5 %387 %137
%390 = OpAccessChain %169 %105 %89 %391
%392 = OpLoad %14 %390
%394 = OpIAdd %5 %387 %130
%393 = OpAccessChain %169 %105 %89 %394
%395 = OpLoad %14 %393
%396 = OpCompositeConstruct %218 %389 %392 %395
%397 = OpCompositeExtract %14 %396 0
%398 = OpCompositeExtract %14 %396 1
%399 = OpCompositeExtract %14 %396 2
%400 = OpConvertUToF %288 %397
%401 = OpConvertUToF %288 %398
%402 = OpConvertUToF %288 %399
%403 = OpFAdd %288 %379 %402
%404 = OpFunctionCall %5 %272 %161 %335
%405 = OpShiftRightLogical %9 %116 %126
%406 = OpCompositeExtract %5 %405 0
%407 = OpCompositeExtract %5 %405 1
%408 = OpIAdd %5 %404 %406
%409 = OpULessThan %165 %404 %407
%410 = OpSelect %5 %409 %408 %248
%411 = OpAccessChain %249 %109 %89 %410
%412 = OpLoad %26 %411
%413 = OpCompositeExtract %14 %412 0
%414 = OpCompositeExtract %14 %412 1
%415 = OpCompositeExtract %14 %412 2
%416 = OpCompositeExtract %14 %412 3
%417 = OpConvertUToF %288 %413
%418 = OpConvertUToF %288 %414
%419 = OpConvertUToF %288 %415
%420 = OpConvertUToF %288 %416
%421 = OpFAdd %288 %403 %419
%422 = OpFunctionCall %5 %272 %161 %130
%423 = OpShiftRightLogical %9 %100 %138
%424 = OpCompositeExtract %5 %423 0
%425 = OpCompositeExtract %5 %423 1
%426 = OpIAdd %5 %422 %424
%427 = OpULessThan %165 %422 %425
%428 = OpSelect %5 %427 %426 %168
%429 = OpBitcast %14 %175
%430 = OpAccessChain %169 %95 %89 %428
OpStore %430 %429
%431 = OpFunctionCall %5 %272 %161 %75
%432 = OpShiftRightLogical %9 %100 %148
%433 = OpCompositeExtract %5 %432 0
%434 = OpCompositeExtract %5 %432 1
%435 = OpIAdd %5 %431 %433
%436 = OpULessThan %165 %431 %434
%437 = OpSelect %5 %436 %435 %188
%439 = OpBitcast %14 %438
%441 = OpBitcast %14 %440
%442 = OpCompositeConstruct %20 %439 %441
%443 = OpAccessChain %189 %96 %89 %437
OpStore %443 %442
%444 = OpIMul %5 %161 %86
%445 = OpFunctionCall %5 %272 %444 %130
%446 = OpShiftRightLogical %9 %100 %138
%447 = OpCompositeExtract %5 %446 0
%448 = OpCompositeExtract %5 %446 1
%449 = OpIAdd %5 %445 %447
%450 = OpULessThan %165 %445 %448
%451 = OpSelect %5 %450 %449 %168
%452 = OpBitcast %14 %440
%454 = OpBitcast %14 %453
%456 = OpBitcast %14 %455
%457 = OpAccessChain %169 %95 %89 %451
OpStore %457 %452
%459 = OpIAdd %5 %451 %137
%458 = OpAccessChain %169 %95 %89 %459
OpStore %458 %454
%461 = OpIAdd %5 %451 %130
%460 = OpAccessChain %169 %95 %89 %461
OpStore %460 %456
%462 = OpFunctionCall %5 %272 %161 %335
%463 = OpShiftRightLogical %9 %100 %126
%464 = OpCompositeExtract %5 %463 0
%465 = OpCompositeExtract %5 %463 1
%466 = OpIAdd %5 %462 %464
%467 = OpULessThan %165 %462 %465
%468 = OpSelect %5 %467 %466 %248
%470 = OpBitcast %14 %469
%472 = OpBitcast %14 %471
%474 = OpBitcast %14 %473
%476 = OpBitcast %14 %475
%477 = OpCompositeConstruct %26 %470 %472 %474 %476
%478 = OpAccessChain %249 %97 %89 %468
OpStore %478 %477
%479 = OpFunctionCall %5 %272 %161 %130
%480 = OpShiftRightLogical %9 %90 %138
%481 = OpCompositeExtract %5 %480 0
%482 = OpCompositeExtract %5 %480 1
%483 = OpIAdd %5 %479 %481
%484 = OpULessThan %165 %479 %482
%485 = OpSelect %5 %484 %483 %168
%487 = OpAccessChain %169 %80 %89 %485
OpStore %487 %486
%488 = OpFunctionCall %5 %272 %161 %75
%489 = OpShiftRightLogical %9 %90 %148
%490 = OpCompositeExtract %5 %489 0
%491 = OpCompositeExtract %5 %489 1
%492 = OpIAdd %5 %488 %490
%493 = OpULessThan %165 %488 %491
%494 = OpSelect %5 %493 %492 %188
%495 = OpCompositeConstruct %20 %195 %257
%496 = OpAccessChain %189 %82 %89 %494
OpStore %496 %495
%497 = OpIMul %5 %161 %86
%498 = OpFunctionCall %5 %272 %497 %130
%499 = OpShiftRightLogical %9 %90 %138
%500 = OpCompositeExtract %5 %499 0
%501 = OpCompositeExtract %5 %499 1
%502 = OpIAdd %5 %498 %500
%503 = OpULessThan %165 %498 %501
%504 = OpSelect %5 %503 %502 %168
%507 = OpAccessChain %169 %80 %89 %504
OpStore %507 %257
%509 = OpIAdd %5 %504 %137
%508 = OpAccessChain %169 %80 %89 %509
OpStore %508 %505
%511 = OpIAdd %5 %504 %130
%510 = OpAccessChain %169 %80 %89 %511
OpStore %510 %506
%512 = OpFunctionCall %5 %272 %161 %335
%513 = OpShiftRightLogical %9 %90 %126
%514 = OpCompositeExtract %5 %513 0
%515 = OpCompositeExtract %5 %513 1
%516 = OpIAdd %5 %512 %514
%517 = OpULessThan %165 %512 %515
%518 = OpSelect %5 %517 %516 %248
%523 = OpCompositeConstruct %26 %519 %520 %521 %522
%524 = OpAccessChain %249 %84 %89 %518
OpStore %524 %523
%525 = OpFunctionCall %5 %272 %161 %75
%526 = OpShiftRightLogical %9 %116 %148
%527 = OpCompositeExtract %5 %526 0
%528 = OpCompositeExtract %5 %526 1
%529 = OpIAdd %5 %525 %527
%530 = OpULessThan %165 %525 %528
%531 = OpSelect %5 %530 %529 %532
%534 = OpAccessChain %533 %111 %89 %531
%535 = OpLoad %5 %534
%536 = OpBitcast %288 %535
%537 = OpFAdd %288 %421 %536
%538 = OpIAdd %5 %161 %89
%539 = OpAccessChain %73 %8 %75
%540 = OpLoad %5 %539
%541 = OpIAdd %5 %540 %538
%542 = OpAccessChain %104 %36 %541
%543 = OpAccessChain %106 %41 %541
%544 = OpAccessChain %87 %13 %89 %541
%545 = OpLoad %9 %544
%546 = OpIMul %5 %161 %130
%547 = OpFunctionCall %5 %272 %546 %130
%548 = OpShiftRightLogical %9 %545 %138
%549 = OpCompositeExtract %5 %548 0
%550 = OpCompositeExtract %5 %548 1
%551 = OpIAdd %5 %547 %549
%552 = OpULessThan %165 %547 %550
%553 = OpSelect %5 %552 %551 %168
%554 = OpAccessChain %169 %542 %89 %553
%555 = OpLoad %14 %554
%556 = OpBitcast %172 %555
%557 = OpFConvert %288 %556
%558 = OpFAdd %288 %304 %289
%559 = OpFAdd %288 %558 %364
%560 = OpFAdd %288 %559 %377
%561 = OpFAdd %288 %560 %329
%562 = OpFAdd %288 %561 %350
%563 = OpFAdd %288 %562 %400
%564 = OpFAdd %288 %563 %417
%565 = OpFAdd %288 %564 %536
%566 = OpFAdd %288 %565 %557
%567 = OpFAdd %288 %560 %330
%568 = OpFAdd %288 %567 %351
%569 = OpFAdd %288 %568 %401
%570 = OpFAdd %288 %569 %418
%571 = OpFAdd %288 %570 %536
%572 = OpFAdd %288 %571 %557
%573 = OpFAdd %288 %537 %557
%574 = OpFConvert %172 %566
%575 = OpFConvert %172 %572
%576 = OpIMul %5 %161 %130
%577 = OpFunctionCall %5 %272 %576 %75
%578 = OpShiftRightLogical %9 %545 %148
%579 = OpCompositeExtract %5 %578 0
%580 = OpCompositeExtract %5 %578 1
%581 = OpIAdd %5 %577 %579
%582 = OpULessThan %165 %577 %580
%583 = OpSelect %5 %582 %581 %188
%584 = OpBitcast %14 %574
%585 = OpBitcast %14 %575
%586 = OpCompositeConstruct %20 %584 %585
%587 = OpAccessChain %189 %543 %89 %583
OpStore %587 %586
%588 = OpCompositeExtract %5 %155 1
%589 = OpUDiv %5 %588 %137
%590 = OpConvertUToF %288 %589
%591 = OpFAdd %288 %590 %566
%592 = OpFAdd %288 %572 %593
%594 = OpCompositeExtract %5 %125 1
%595 = OpUDiv %5 %594 %137
%596 = OpConvertUToF %288 %595
%597 = OpFAdd %288 %573 %596
%598 = OpFAdd %288 %289 %599
%600 = OpFAdd %288 %598 %305
%601 = OpFAdd %288 %600 %329
%602 = OpFAdd %288 %601 %353
%603 = OpFAdd %288 %602 %364
%604 = OpFAdd %288 %603 %378
%605 = OpFAdd %288 %604 %400
%606 = OpFAdd %288 %605 %420
%607 = OpFAdd %288 %606 %536
%608 = OpFAdd %288 %607 %557
%609 = OpCompositeExtract %5 %100 1
%610 = OpIMul %5 %609 %335
%611 = OpConvertUToF %288 %610
%612 = OpFAdd %288 %591 %611
%613 = OpConvertFToU %5 %612
%614 = OpConvertFToU %5 %592
%615 = OpConvertFToU %5 %597
%616 = OpConvertFToU %5 %608
%617 = OpShiftLeftLogical %5 %161 %75
%618 = OpFunctionCall %5 %272 %161 %619
%620 = OpShiftRightLogical %9 %116 %621
%622 = OpCompositeExtract %5 %620 0
%623 = OpCompositeExtract %5 %620 1
%624 = OpIAdd %5 %618 %622
%625 = OpULessThan %165 %618 %623
%626 = OpSelect %5 %625 %624 %627
%628 = OpCompositeConstruct %52 %613 %614 %615 %616
%630 = OpAccessChain %629 %113 %89 %626
OpStore %630 %628
OpReturn
OpFunctionEnd
%272 = OpFunction %5 None %269
%270 = OpFunctionParameter %5
%271 = OpFunctionParameter %5
%273 = OpLabel
%274 = OpUDiv %5 %275 %271
%276 = OpBitwiseAnd %5 %270 %274
OpReturnValue %276
OpFunctionEnd
#endif
