#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 7, binding = 0, std430) buffer AtomicCounters
{
    uint counter;
} _16[];

layout(push_constant, std430) uniform RootConstants
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
    uint _m5;
    uint _m6;
    uint _m7;
    uint _m8;
    uint _m9;
    uint _m10;
    uint _m11;
    uint _m12;
    uint _m13;
    uint _m14;
    uint _m15;
} registers;

layout(set = 4, binding = 0, r32ui) uniform readonly writeonly uimageBuffer _12[];

void main()
{
    uint _38 = atomicAdd(_16[nonuniformEXT(registers._m4 + (gl_GlobalInvocationID.x + 2u))].counter, 1u);
    uint _49 = atomicAdd(_16[nonuniformEXT(registers._m4 + ((gl_GlobalInvocationID.x ^ 1u) + 2u))].counter, 1u);
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 52
; Schema: 0
OpCapability Shader
OpCapability StorageBufferArrayDynamicIndexing
OpCapability ImageBuffer
OpCapability RuntimeDescriptorArray
OpCapability StorageTexelBufferArrayDynamicIndexing
OpCapability StorageTexelBufferArrayNonUniformIndexing
OpCapability PhysicalStorageBufferAddresses
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_physical_storage_buffer"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %19
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %13 "AtomicCounters"
OpMemberName %13 0 "counter"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpMemberDecorate %6 8 Offset 32
OpMemberDecorate %6 9 Offset 36
OpMemberDecorate %6 10 Offset 40
OpMemberDecorate %6 11 Offset 44
OpMemberDecorate %6 12 Offset 48
OpMemberDecorate %6 13 Offset 52
OpMemberDecorate %6 14 Offset 56
OpMemberDecorate %6 15 Offset 60
OpDecorate %12 DescriptorSet 4
OpDecorate %12 Binding 0
OpDecorate %12 NonReadable
OpDecorate %12 NonWritable
OpDecorate %13 Block
OpMemberDecorate %13 0 Offset 0
OpDecorate %16 DescriptorSet 7
OpDecorate %16 Binding 0
OpDecorate %19 BuiltIn GlobalInvocationId
OpDecorate %30 NonUniform
OpDecorate %33 NonUniform
OpDecorate %37 NonUniform
OpDecorate %44 NonUniform
OpDecorate %46 NonUniform
OpDecorate %48 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%10 = OpTypeRuntimeArray %9
%11 = OpTypePointer UniformConstant %10
%12 = OpVariable %11 UniformConstant
%13 = OpTypeStruct %5
%14 = OpTypeRuntimeArray %13
%15 = OpTypePointer StorageBuffer %14
%16 = OpVariable %15 StorageBuffer
%17 = OpTypeVector %5 3
%18 = OpTypePointer Input %17
%19 = OpVariable %18 Input
%20 = OpTypePointer Input %5
%22 = OpConstant %5 0
%25 = OpConstant %5 2
%26 = OpTypePointer PushConstant %5
%28 = OpConstant %5 4
%31 = OpTypePointer UniformConstant %9
%34 = OpTypePointer StorageBuffer %13
%36 = OpTypePointer StorageBuffer %5
%39 = OpConstant %5 1
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %50
%50 = OpLabel
%21 = OpAccessChain %20 %19 %22
%23 = OpLoad %5 %21
%24 = OpIAdd %5 %23 %25
%27 = OpAccessChain %26 %8 %28
%29 = OpLoad %5 %27
%30 = OpIAdd %5 %29 %24
%32 = OpAccessChain %31 %12 %30
%33 = OpLoad %9 %32
%35 = OpAccessChain %34 %16 %30
%37 = OpAccessChain %36 %35 %22
%38 = OpAtomicIAdd %5 %37 %39 %22 %39
%40 = OpBitwiseXor %5 %23 %39
%41 = OpIAdd %5 %40 %25
%42 = OpAccessChain %26 %8 %28
%43 = OpLoad %5 %42
%44 = OpIAdd %5 %43 %41
%45 = OpAccessChain %31 %12 %44
%46 = OpLoad %9 %45
%47 = OpAccessChain %34 %16 %44
%48 = OpAccessChain %36 %47 %22
%49 = OpAtomicIAdd %5 %48 %39 %22 %39
OpReturn
OpFunctionEnd
#endif
