#version 460
#extension GL_EXT_nonuniform_qualifier : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(push_constant, std430) uniform RootConstants
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
    uint _m5;
    uint _m6;
    uint _m7;
    uint _m8;
    uint _m9;
    uint _m10;
    uint _m11;
    uint _m12;
    uint _m13;
    uint _m14;
    uint _m15;
} registers;

layout(set = 4, binding = 0, r32ui) uniform readonly writeonly uimageBuffer _12[];
layout(set = 7, binding = 0, r32ui) uniform uimageBuffer _15[];

void main()
{
    uint _36 = imageAtomicAdd(_15[nonuniformEXT(registers._m4 + (gl_GlobalInvocationID.x + 2u))], int(0u), 1u);
    uint _47 = imageAtomicAdd(_15[nonuniformEXT(registers._m4 + ((gl_GlobalInvocationID.x ^ 1u) + 2u))], int(0u), 1u);
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 50
; Schema: 0
OpCapability Shader
OpCapability ImageBuffer
OpCapability RuntimeDescriptorArray
OpCapability StorageTexelBufferArrayDynamicIndexing
OpCapability StorageTexelBufferArrayNonUniformIndexing
OpExtension "SPV_EXT_descriptor_indexing"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %18
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpMemberDecorate %6 8 Offset 32
OpMemberDecorate %6 9 Offset 36
OpMemberDecorate %6 10 Offset 40
OpMemberDecorate %6 11 Offset 44
OpMemberDecorate %6 12 Offset 48
OpMemberDecorate %6 13 Offset 52
OpMemberDecorate %6 14 Offset 56
OpMemberDecorate %6 15 Offset 60
OpDecorate %12 DescriptorSet 4
OpDecorate %12 Binding 0
OpDecorate %12 NonReadable
OpDecorate %12 NonWritable
OpDecorate %15 DescriptorSet 7
OpDecorate %15 Binding 0
OpDecorate %18 BuiltIn GlobalInvocationId
OpDecorate %29 NonUniform
OpDecorate %32 NonUniform
OpDecorate %35 NonUniform
OpDecorate %42 NonUniform
OpDecorate %44 NonUniform
OpDecorate %46 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%10 = OpTypeRuntimeArray %9
%11 = OpTypePointer UniformConstant %10
%12 = OpVariable %11 UniformConstant
%13 = OpTypeRuntimeArray %9
%14 = OpTypePointer UniformConstant %13
%15 = OpVariable %14 UniformConstant
%16 = OpTypeVector %5 3
%17 = OpTypePointer Input %16
%18 = OpVariable %17 Input
%19 = OpTypePointer Input %5
%21 = OpConstant %5 0
%24 = OpConstant %5 2
%25 = OpTypePointer PushConstant %5
%27 = OpConstant %5 4
%30 = OpTypePointer UniformConstant %9
%34 = OpTypePointer Image %5
%37 = OpConstant %5 1
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %48
%48 = OpLabel
%20 = OpAccessChain %19 %18 %21
%22 = OpLoad %5 %20
%23 = OpIAdd %5 %22 %24
%26 = OpAccessChain %25 %8 %27
%28 = OpLoad %5 %26
%29 = OpIAdd %5 %28 %23
%31 = OpAccessChain %30 %12 %29
%32 = OpLoad %9 %31
%33 = OpAccessChain %30 %15 %29
%35 = OpImageTexelPointer %34 %33 %21 %21
%36 = OpAtomicIAdd %5 %35 %37 %21 %37
%38 = OpBitwiseXor %5 %22 %37
%39 = OpIAdd %5 %38 %24
%40 = OpAccessChain %25 %8 %27
%41 = OpLoad %5 %40
%42 = OpIAdd %5 %41 %39
%43 = OpAccessChain %30 %12 %42
%44 = OpLoad %9 %43
%45 = OpAccessChain %30 %15 %42
%46 = OpImageTexelPointer %34 %45 %21 %21
%47 = OpAtomicIAdd %5 %46 %37 %21 %37
OpReturn
OpFunctionEnd
#endif
