; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 125
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability GroupNonUniformBallot
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpCapability UntypedPointersKHR
OpCapability RuntimeDescriptorArray
OpCapability PhysicalStorageBufferAddresses
OpCapability AtomicFloat16VectorNV
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_KHR_physical_storage_buffer"
OpExtension "SPV_KHR_untyped_pointers"
OpExtension "SPV_NV_shader_atomic_fp16_vector"
%50 = OpExtInstImport "GLSL.std.450"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main"
OpExecutionMode %3 LocalSize 32 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %11 "SSBO_Offsets"
OpName %15 "SSBO"
OpName %20 "SSBO"
OpName %73 "ssbo"
OpName %93 "ssbo"
OpName %111 "ssbo"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpDecorate %10 ArrayStride 8
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 15
OpDecorate %13 Binding 0
OpDecorate %13 NonWritable
OpDecorate %13 Restrict
OpDecorate %14 ArrayStride 4
OpMemberDecorate %15 0 Offset 0
OpDecorate %15 Block
OpDecorate %18 DescriptorSet 4
OpDecorate %18 Binding 0
OpDecorate %19 ArrayStride 4
OpMemberDecorate %20 0 Offset 0
OpDecorate %20 Block
OpDecorate %23 DescriptorSet 4
OpDecorate %23 Binding 0
OpDecorate %23 NonReadable
OpDecorate %72 ArrayStride 4
OpDecorate %73 Block
OpMemberDecorate %73 0 Offset 0
OpDecorate %92 ArrayStride 4
OpDecorate %93 Block
OpMemberDecorate %93 0 Offset 0
OpDecorate %110 ArrayStride 4
OpDecorate %111 Block
OpMemberDecorate %111 0 Offset 0
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeVector %5 2
%10 = OpTypeRuntimeArray %9
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeRuntimeArray %5
%15 = OpTypeStruct %14
%16 = OpTypeRuntimeArray %15
%17 = OpTypePointer StorageBuffer %16
%18 = OpVariable %17 StorageBuffer
%19 = OpTypeRuntimeArray %5
%20 = OpTypeStruct %19
%21 = OpTypeRuntimeArray %20
%22 = OpTypePointer StorageBuffer %21
%23 = OpVariable %22 StorageBuffer
%24 = OpTypePointer PushConstant %5
%26 = OpConstant %5 4
%29 = OpConstant %5 1
%30 = OpTypePointer StorageBuffer %20
%33 = OpConstant %5 3
%34 = OpTypePointer StorageBuffer %9
%36 = OpConstant %5 0
%39 = OpConstant %5 2
%40 = OpConstantComposite %9 %39 %39
%43 = OpTypePointer StorageBuffer %15
%51 = OpTypeFloat 32
%52 = OpConstant %51 46.5
%54 = OpConstant %51 0
%55 = OpTypeVector %51 2
%58 = OpConstant %5 16
%59 = OpConstant %51 45.5
%63 = OpTypeFloat 16
%64 = OpTypeVector %63 2
%68 = OpTypeBool
%71 = OpConstant %5 1073741820
%72 = OpTypeRuntimeArray %64
%73 = OpTypeStruct %72
%74 = OpTypeUntypedPointerKHR StorageBuffer
%79 = OpConstant %5 100
%85 = OpTypePointer StorageBuffer %5
%92 = OpTypeRuntimeArray %64
%93 = OpTypeStruct %92
%98 = OpConstant %5 101
%110 = OpTypeRuntimeArray %64
%111 = OpTypeStruct %110
%116 = OpConstant %5 102
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %123
%123 = OpLabel
%25 = OpAccessChain %24 %8 %26
%27 = OpLoad %5 %25
%28 = OpIAdd %5 %27 %29
%31 = OpAccessChain %30 %23 %28
%32 = OpGroupNonUniformBroadcastFirst %5 %33 %28
%35 = OpAccessChain %34 %13 %36 %32
%37 = OpLoad %9 %35
%38 = OpShiftRightLogical %9 %37 %40
%41 = OpAccessChain %24 %8 %26
%42 = OpLoad %5 %41
%44 = OpAccessChain %43 %18 %42
%45 = OpGroupNonUniformBroadcastFirst %5 %33 %42
%46 = OpAccessChain %34 %13 %36 %45
%47 = OpLoad %9 %46
%48 = OpShiftRightLogical %9 %47 %40
%56 = OpCompositeConstruct %55 %52 %54
%53 = OpExtInst %5 %50 PackHalf2x16 %56
%57 = OpShiftLeftLogical %5 %53 %58
%61 = OpCompositeConstruct %55 %59 %54
%60 = OpExtInst %5 %50 PackHalf2x16 %61
%62 = OpBitwiseOr %5 %57 %60
%65 = OpCompositeExtract %5 %48 0
%66 = OpCompositeExtract %5 %48 1
%67 = OpIAdd %5 %39 %65
%69 = OpULessThan %68 %39 %66
%70 = OpSelect %5 %69 %67 %71
%75 = OpUntypedAccessChainKHR %74 %73 %44 %36 %70
%76 = OpBitcast %64 %62
%77 = OpAtomicFAddEXT %64 %75 %29 %36 %76
%78 = OpBitcast %5 %77
%80 = OpCompositeExtract %5 %38 0
%81 = OpCompositeExtract %5 %38 1
%82 = OpIAdd %5 %79 %80
%83 = OpULessThan %68 %79 %81
%84 = OpSelect %5 %83 %82 %71
%86 = OpAccessChain %85 %31 %36 %84
OpStore %86 %78
%87 = OpCompositeExtract %5 %48 0
%88 = OpCompositeExtract %5 %48 1
%89 = OpIAdd %5 %39 %87
%90 = OpULessThan %68 %39 %88
%91 = OpSelect %5 %90 %89 %71
%94 = OpUntypedAccessChainKHR %74 %93 %44 %36 %91
%95 = OpBitcast %64 %62
%96 = OpAtomicFMinEXT %64 %94 %29 %36 %95
%97 = OpBitcast %5 %96
%99 = OpCompositeExtract %5 %38 0
%100 = OpCompositeExtract %5 %38 1
%101 = OpIAdd %5 %98 %99
%102 = OpULessThan %68 %98 %100
%103 = OpSelect %5 %102 %101 %71
%104 = OpAccessChain %85 %31 %36 %103
OpStore %104 %97
%105 = OpCompositeExtract %5 %48 0
%106 = OpCompositeExtract %5 %48 1
%107 = OpIAdd %5 %39 %105
%108 = OpULessThan %68 %39 %106
%109 = OpSelect %5 %108 %107 %71
%112 = OpUntypedAccessChainKHR %74 %111 %44 %36 %109
%113 = OpBitcast %64 %62
%114 = OpAtomicFMaxEXT %64 %112 %29 %36 %113
%115 = OpBitcast %5 %114
%117 = OpCompositeExtract %5 %38 0
%118 = OpCompositeExtract %5 %38 1
%119 = OpIAdd %5 %116 %117
%120 = OpULessThan %68 %116 %118
%121 = OpSelect %5 %120 %119 %71
%122 = OpAccessChain %85 %31 %36 %121
OpStore %122 %115
OpReturn
OpFunctionEnd

