; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 70
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpCapability PhysicalStorageBufferAddresses
OpCapability AtomicFloat16VectorNV
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_KHR_physical_storage_buffer"
OpExtension "SPV_NV_shader_atomic_fp16_vector"
%18 = OpExtInstImport "GLSL.std.450"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main"
OpExecutionMode %3 LocalSize 32 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %7 "RootConstants"
OpName %9 "registers"
OpName %35 "PhysicalPointerHalf2Array"
OpMemberName %35 0 "value"
OpName %46 "PhysicalPointerUintArray"
OpMemberName %46 0 "value"
OpDecorate %7 Block
OpMemberDecorate %7 0 Offset 0
OpMemberDecorate %7 1 Offset 8
OpMemberDecorate %7 2 Offset 16
OpMemberDecorate %7 3 Offset 24
OpDecorate %34 ArrayStride 4
OpMemberDecorate %35 0 Offset 0
OpDecorate %35 Block
OpDecorate %45 ArrayStride 4
OpMemberDecorate %46 0 Offset 0
OpDecorate %46 Block
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 2
%7 = OpTypeStruct %6 %6 %6 %6
%8 = OpTypePointer PushConstant %7
%9 = OpVariable %8 PushConstant
%10 = OpTypePointer PushConstant %6
%12 = OpConstant %5 3
%15 = OpConstant %5 2
%19 = OpTypeFloat 32
%20 = OpConstant %19 46.5
%22 = OpConstant %19 0
%23 = OpTypeVector %19 2
%26 = OpConstant %5 16
%27 = OpConstant %19 45.5
%31 = OpTypeFloat 16
%32 = OpTypeVector %31 2
%33 = OpConstant %5 1
%34 = OpTypeRuntimeArray %32
%35 = OpTypeStruct %34
%36 = OpTypePointer PhysicalStorageBuffer %35
%38 = OpTypePointer PhysicalStorageBuffer %32
%40 = OpConstant %5 0
%44 = OpConstant %5 100
%45 = OpTypeRuntimeArray %5
%46 = OpTypeStruct %45
%47 = OpTypePointer PhysicalStorageBuffer %46
%49 = OpTypePointer PhysicalStorageBuffer %5
%57 = OpConstant %5 101
%65 = OpConstant %5 102
%3 = OpFunction %1 None %2
%4 = OpLabel
%51 = OpUndef %5
OpBranch %68
%68 = OpLabel
%11 = OpAccessChain %10 %9 %12
%13 = OpLoad %6 %11
%14 = OpAccessChain %10 %9 %15
%16 = OpLoad %6 %14
%24 = OpCompositeConstruct %23 %20 %22
%21 = OpExtInst %5 %18 PackHalf2x16 %24
%25 = OpShiftLeftLogical %5 %21 %26
%29 = OpCompositeConstruct %23 %27 %22
%28 = OpExtInst %5 %18 PackHalf2x16 %29
%30 = OpBitwiseOr %5 %25 %28
%37 = OpBitcast %36 %16
%39 = OpAccessChain %38 %37 %40 %33
%41 = OpBitcast %32 %30
%42 = OpAtomicFAddEXT %32 %39 %33 %40 %41
%43 = OpBitcast %5 %42
%48 = OpBitcast %47 %13
%50 = OpInBoundsAccessChain %49 %48 %40 %44
OpStore %50 %43 Aligned 4
%52 = OpBitcast %36 %16
%53 = OpAccessChain %38 %52 %40 %33
%54 = OpBitcast %32 %30
%55 = OpAtomicFMinEXT %32 %53 %33 %40 %54
%56 = OpBitcast %5 %55
%58 = OpBitcast %47 %13
%59 = OpInBoundsAccessChain %49 %58 %40 %57
OpStore %59 %56 Aligned 4
%60 = OpBitcast %36 %16
%61 = OpAccessChain %38 %60 %40 %33
%62 = OpBitcast %32 %30
%63 = OpAtomicFMaxEXT %32 %61 %33 %40 %62
%64 = OpBitcast %5 %63
%66 = OpBitcast %47 %13
%67 = OpInBoundsAccessChain %49 %66 %40 %65
OpStore %67 %64 Aligned 4
OpReturn
OpFunctionEnd

