; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 61
; Schema: 0
OpCapability Shader
OpCapability Float16
OpCapability StorageBufferArrayDynamicIndexing
OpCapability StorageBuffer16BitAccess
OpCapability DenormPreserve
OpCapability UntypedPointersKHR
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability AtomicFloat16VectorNV
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_float_controls"
OpExtension "SPV_KHR_untyped_pointers"
OpExtension "SPV_NV_shader_atomic_fp16_vector"
%33 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %19
OpExecutionMode %3 LocalSize 32 1 1
OpExecutionMode %3 DenormPreserve 16
OpName %3 "main"
OpName %7 "SSBO"
OpName %13 "SSBO"
OpName %50 "ssbo"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 0
OpDecorate %12 ArrayStride 4
OpMemberDecorate %13 0 Offset 0
OpDecorate %13 Block
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 4
OpDecorate %15 NonReadable
OpDecorate %19 BuiltIn GlobalInvocationId
OpDecorate %30 NonUniform
OpDecorate %32 NonUniform
OpDecorate %49 ArrayStride 4
OpDecorate %50 Block
OpMemberDecorate %50 0 Offset 0
OpDecorate %52 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpConstant %5 4
%9 = OpTypeArray %7 %8
%10 = OpTypePointer StorageBuffer %9
%11 = OpVariable %10 StorageBuffer
%12 = OpTypeRuntimeArray %5
%13 = OpTypeStruct %12
%14 = OpTypePointer StorageBuffer %13
%15 = OpVariable %14 StorageBuffer
%17 = OpTypeVector %5 3
%18 = OpTypePointer Input %17
%19 = OpVariable %18 Input
%20 = OpTypePointer Input %5
%22 = OpConstant %5 0
%25 = OpConstant %5 2
%27 = OpConstant %5 28
%29 = OpConstant %5 3
%31 = OpTypePointer StorageBuffer %7
%34 = OpTypeFloat 32
%35 = OpConstant %34 2
%37 = OpConstant %34 0
%38 = OpTypeVector %34 2
%41 = OpConstant %5 16
%42 = OpConstant %34 1
%46 = OpTypeFloat 16
%47 = OpTypeVector %46 2
%49 = OpTypeRuntimeArray %47
%50 = OpTypeStruct %49
%51 = OpTypeUntypedPointerKHR StorageBuffer
%55 = OpConstant %5 1
%57 = OpTypePointer StorageBuffer %5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %59
%59 = OpLabel
%21 = OpAccessChain %20 %19 %22
%23 = OpLoad %5 %21
%24 = OpShiftLeftLogical %5 %23 %25
%26 = OpBitwiseAnd %5 %24 %27
%28 = OpBitwiseAnd %5 %23 %29
%30 = OpIAdd %5 %28 %22
%32 = OpAccessChain %31 %11 %30
%39 = OpCompositeConstruct %38 %35 %37
%36 = OpExtInst %5 %33 PackHalf2x16 %39
%40 = OpShiftLeftLogical %5 %36 %41
%44 = OpCompositeConstruct %38 %42 %37
%43 = OpExtInst %5 %33 PackHalf2x16 %44
%45 = OpBitwiseOr %5 %40 %43
%48 = OpShiftRightLogical %5 %26 %25
%52 = OpUntypedAccessChainKHR %51 %50 %32 %22 %48
%53 = OpBitcast %47 %45
%54 = OpAtomicFAddEXT %47 %52 %55 %22 %53
%56 = OpBitcast %5 %54
%58 = OpAccessChain %57 %15 %22 %23
OpStore %58 %56
OpReturn
OpFunctionEnd

