; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 87
; Schema: 0
OpCapability Shader
OpCapability GroupNonUniformBallot
OpCapability UntypedPointersKHR
OpCapability RuntimeDescriptorArray
OpCapability PhysicalStorageBufferAddresses
OpCapability AtomicFloat32AddEXT
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_EXT_shader_atomic_float_add"
OpExtension "SPV_KHR_physical_storage_buffer"
OpExtension "SPV_KHR_untyped_pointers"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %52
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %11 "SSBO_Offsets"
OpName %15 "SSBO"
OpName %20 "SSBO"
OpName %69 "ssbo"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpDecorate %10 ArrayStride 8
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 15
OpDecorate %13 Binding 0
OpDecorate %13 NonWritable
OpDecorate %13 Restrict
OpDecorate %14 ArrayStride 4
OpMemberDecorate %15 0 Offset 0
OpDecorate %15 Block
OpDecorate %18 DescriptorSet 4
OpDecorate %18 Binding 0
OpDecorate %18 NonReadable
OpDecorate %19 ArrayStride 4
OpMemberDecorate %20 0 Offset 0
OpDecorate %20 Block
OpDecorate %23 DescriptorSet 4
OpDecorate %23 Binding 0
OpDecorate %23 NonReadable
OpDecorate %52 BuiltIn GlobalInvocationId
OpDecorate %68 ArrayStride 4
OpDecorate %69 Block
OpMemberDecorate %69 0 Offset 0
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeVector %5 2
%10 = OpTypeRuntimeArray %9
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeRuntimeArray %5
%15 = OpTypeStruct %14
%16 = OpTypeRuntimeArray %15
%17 = OpTypePointer StorageBuffer %16
%18 = OpVariable %17 StorageBuffer
%19 = OpTypeRuntimeArray %5
%20 = OpTypeStruct %19
%21 = OpTypeRuntimeArray %20
%22 = OpTypePointer StorageBuffer %21
%23 = OpVariable %22 StorageBuffer
%24 = OpTypePointer PushConstant %5
%26 = OpConstant %5 4
%29 = OpConstant %5 1
%30 = OpTypePointer StorageBuffer %20
%33 = OpConstant %5 3
%34 = OpTypePointer StorageBuffer %9
%36 = OpConstant %5 0
%39 = OpConstant %5 2
%40 = OpConstantComposite %9 %39 %39
%43 = OpTypePointer StorageBuffer %15
%50 = OpTypeVector %5 3
%51 = OpTypePointer Input %50
%52 = OpVariable %51 Input
%53 = OpTypePointer Input %5
%56 = OpTypeFloat 32
%59 = OpConstant %56 45.5
%64 = OpTypeBool
%67 = OpConstant %5 1073741820
%68 = OpTypeRuntimeArray %56
%69 = OpTypeStruct %68
%70 = OpTypeUntypedPointerKHR StorageBuffer
%76 = OpConstant %5 100
%83 = OpTypePointer StorageBuffer %5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %85
%85 = OpLabel
%25 = OpAccessChain %24 %8 %26
%27 = OpLoad %5 %25
%28 = OpIAdd %5 %27 %29
%31 = OpAccessChain %30 %23 %28
%32 = OpGroupNonUniformBroadcastFirst %5 %33 %28
%35 = OpAccessChain %34 %13 %36 %32
%37 = OpLoad %9 %35
%38 = OpShiftRightLogical %9 %37 %40
%41 = OpAccessChain %24 %8 %26
%42 = OpLoad %5 %41
%44 = OpAccessChain %43 %18 %42
%45 = OpGroupNonUniformBroadcastFirst %5 %33 %42
%46 = OpAccessChain %34 %13 %36 %45
%47 = OpLoad %9 %46
%48 = OpShiftRightLogical %9 %47 %40
%54 = OpAccessChain %53 %52 %36
%55 = OpLoad %5 %54
%57 = OpConvertUToF %56 %55
%58 = OpFAdd %56 %57 %59
%60 = OpBitcast %5 %58
%61 = OpCompositeExtract %5 %48 0
%62 = OpCompositeExtract %5 %48 1
%63 = OpIAdd %5 %29 %61
%65 = OpULessThan %64 %29 %62
%66 = OpSelect %5 %65 %63 %67
%71 = OpUntypedAccessChainKHR %70 %69 %44 %36 %66
%72 = OpBitcast %56 %60
%73 = OpAtomicFAddEXT %56 %71 %29 %36 %72
%74 = OpBitcast %5 %73
%75 = OpBitcast %56 %74
%77 = OpCompositeExtract %5 %38 0
%78 = OpCompositeExtract %5 %38 1
%79 = OpIAdd %5 %76 %77
%80 = OpULessThan %64 %76 %78
%81 = OpSelect %5 %80 %79 %67
%82 = OpBitcast %5 %75
%84 = OpAccessChain %83 %31 %36 %81
OpStore %84 %82
OpReturn
OpFunctionEnd

