; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 47
; Schema: 0
OpCapability Shader
OpCapability PhysicalStorageBufferAddresses
OpCapability AtomicFloat32AddEXT
OpExtension "SPV_EXT_shader_atomic_float_add"
OpExtension "SPV_KHR_physical_storage_buffer"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %20
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %7 "RootConstants"
OpName %9 "registers"
OpName %31 "PhysicalPointerFloatArray"
OpMemberName %31 0 "value"
OpDecorate %7 Block
OpMemberDecorate %7 0 Offset 0
OpMemberDecorate %7 1 Offset 8
OpMemberDecorate %7 2 Offset 16
OpMemberDecorate %7 3 Offset 24
OpDecorate %20 BuiltIn GlobalInvocationId
OpDecorate %30 ArrayStride 4
OpMemberDecorate %31 0 Offset 0
OpDecorate %31 Block
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 2
%7 = OpTypeStruct %6 %6 %6 %6
%8 = OpTypePointer PushConstant %7
%9 = OpVariable %8 PushConstant
%10 = OpTypePointer PushConstant %6
%12 = OpConstant %5 3
%15 = OpConstant %5 2
%18 = OpTypeVector %5 3
%19 = OpTypePointer Input %18
%20 = OpVariable %19 Input
%21 = OpTypePointer Input %5
%23 = OpConstant %5 0
%25 = OpTypeFloat 32
%28 = OpConstant %25 45.5
%30 = OpTypeRuntimeArray %25
%31 = OpTypeStruct %30
%32 = OpTypePointer PhysicalStorageBuffer %31
%34 = OpTypePointer PhysicalStorageBuffer %25
%38 = OpConstant %5 1
%41 = OpConstant %5 100
%3 = OpFunction %1 None %2
%4 = OpLabel
%44 = OpUndef %25
OpBranch %45
%45 = OpLabel
%11 = OpAccessChain %10 %9 %12
%13 = OpLoad %6 %11
%14 = OpAccessChain %10 %9 %15
%16 = OpLoad %6 %14
%22 = OpAccessChain %21 %20 %23
%24 = OpLoad %5 %22
%26 = OpConvertUToF %25 %24
%27 = OpFAdd %25 %26 %28
%29 = OpBitcast %5 %27
%33 = OpBitcast %32 %16
%35 = OpAccessChain %34 %33 %23 %15
%36 = OpBitcast %25 %29
%37 = OpAtomicFAddEXT %25 %35 %38 %23 %36
%39 = OpBitcast %5 %37
%40 = OpBitcast %25 %39
%42 = OpBitcast %32 %13
%43 = OpInBoundsAccessChain %34 %42 %23 %41
OpStore %43 %40 Aligned 4
OpReturn
OpFunctionEnd

