; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 48
; Schema: 0
OpCapability Shader
OpCapability StorageBufferArrayDynamicIndexing
OpCapability UntypedPointersKHR
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability AtomicFloat32AddEXT
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_EXT_shader_atomic_float_add"
OpExtension "SPV_KHR_untyped_pointers"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %19
OpExecutionMode %3 LocalSize 32 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %13 "SSBO"
OpName %36 "ssbo"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 0
OpDecorate %12 ArrayStride 4
OpMemberDecorate %13 0 Offset 0
OpDecorate %13 Block
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 4
OpDecorate %15 NonReadable
OpDecorate %19 BuiltIn GlobalInvocationId
OpDecorate %30 NonUniform
OpDecorate %32 NonUniform
OpDecorate %35 ArrayStride 4
OpDecorate %36 Block
OpMemberDecorate %36 0 Offset 0
OpDecorate %38 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpConstant %5 4
%9 = OpTypeArray %7 %8
%10 = OpTypePointer StorageBuffer %9
%11 = OpVariable %10 StorageBuffer
%12 = OpTypeRuntimeArray %5
%13 = OpTypeStruct %12
%14 = OpTypePointer StorageBuffer %13
%15 = OpVariable %14 StorageBuffer
%17 = OpTypeVector %5 3
%18 = OpTypePointer Input %17
%19 = OpVariable %18 Input
%20 = OpTypePointer Input %5
%22 = OpConstant %5 0
%25 = OpConstant %5 2
%27 = OpConstant %5 28
%29 = OpConstant %5 3
%31 = OpTypePointer StorageBuffer %7
%33 = OpTypeFloat 32
%35 = OpTypeRuntimeArray %33
%36 = OpTypeStruct %35
%37 = OpTypeUntypedPointerKHR StorageBuffer
%39 = OpConstant %5 1065353216
%42 = OpConstant %5 1
%44 = OpTypePointer StorageBuffer %5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %46
%46 = OpLabel
%21 = OpAccessChain %20 %19 %22
%23 = OpLoad %5 %21
%24 = OpShiftLeftLogical %5 %23 %25
%26 = OpBitwiseAnd %5 %24 %27
%28 = OpBitwiseAnd %5 %23 %29
%30 = OpIAdd %5 %28 %22
%32 = OpAccessChain %31 %11 %30
%34 = OpShiftRightLogical %5 %26 %25
%38 = OpUntypedAccessChainKHR %37 %36 %32 %22 %34
%40 = OpBitcast %33 %39
%41 = OpAtomicFAddEXT %33 %38 %42 %22 %40
%43 = OpBitcast %5 %41
%45 = OpAccessChain %44 %15 %22 %23
OpStore %45 %43
OpReturn
OpFunctionEnd

