#version 460
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uint _m0[];
} _9;

layout(set = 0, binding = 1, std430) restrict readonly buffer _11_15
{
    uint _m0[];
} _15[2];

layout(set = 0, binding = 0, std430) buffer _21_23
{
    uint _m0[];
} _23;

layout(set = 0, binding = 0, std140) uniform _27_29
{
    vec4 _m0[1024];
} _29;

layout(set = 0, binding = 1, std140) uniform _31_34
{
    vec4 _m0[1024];
} _34[2];

layout(set = 0, binding = 3) uniform samplerBuffer _19;

void main()
{
    uint _56 = atomicAdd(_23._m0[0u], floatBitsToUint(_29._m0[1u]).x);
    uint _64 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x));
    uint _71 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_34[0u]._m0[1u]).x));
    uint _78 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_34[0u]._m0[gl_GlobalInvocationID.x]).x));
    uint _82 = atomicAdd(_23._m0[0u], _9._m0[1u]);
    uint _87 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(_9._m0[gl_GlobalInvocationID.x]));
    uint _94 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(_15[0u]._m0[1u]));
    uint _99 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(_23._m0[2u]));
    uint _106 = atomicAdd(_23._m0[1u], uint(subgroupBroadcastFirst(texelFetch(_19, int(0u)).x)));
    uint _108 = atomicAdd(_23._m0[0u], gl_WorkGroupID.x);
    uint _111 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(gl_GlobalInvocationID.x));
    uint _118 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(floatBitsToUint(_29._m0[1u]).x));
    uint _126 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(subgroupAdd(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x)));
    uint _134 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(subgroupOr(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x)));
    uint _144 = atomicAdd(_23._m0[0u], uint(subgroupBroadcastFirst(subgroupAllEqual(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x))));
    uint _154 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(subgroupBallot(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x != 0u).x));
    uint _164 = atomicAdd(_23._m0[0u], uint(subgroupBroadcastFirst(subgroupAny(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _174 = atomicAdd(_23._m0[0u], uint(subgroupBroadcastFirst(subgroupAll(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _182 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(subgroupExclusiveAdd(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x)));
}


#if 0
// SPIR-V disassembly
// HeuristicWaveSize(32)
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 185
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability StorageBufferArrayDynamicIndexing
OpCapability SampledBuffer
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %40 %44
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %21 "SSBO"
OpName %27 ""
OpName %31 ""
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 1
OpDecorate %15 NonWritable
OpDecorate %15 Restrict
OpDecorate %19 DescriptorSet 0
OpDecorate %19 Binding 3
OpDecorate %20 ArrayStride 4
OpMemberDecorate %21 0 Offset 0
OpDecorate %21 Block
OpDecorate %23 DescriptorSet 0
OpDecorate %23 Binding 0
OpDecorate %26 ArrayStride 16
OpMemberDecorate %27 0 Offset 0
OpDecorate %27 Block
OpDecorate %29 DescriptorSet 0
OpDecorate %29 Binding 0
OpDecorate %30 ArrayStride 16
OpMemberDecorate %31 0 Offset 0
OpDecorate %31 Block
OpDecorate %34 DescriptorSet 0
OpDecorate %34 Binding 1
OpDecorate %40 BuiltIn GlobalInvocationId
OpDecorate %44 BuiltIn WorkgroupId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpConstant %5 2
%13 = OpTypeArray %11 %12
%14 = OpTypePointer StorageBuffer %13
%15 = OpVariable %14 StorageBuffer
%16 = OpTypeFloat 32
%17 = OpTypeImage %16 Buffer 0 0 0 1 Unknown
%18 = OpTypePointer UniformConstant %17
%19 = OpVariable %18 UniformConstant
%20 = OpTypeRuntimeArray %5
%21 = OpTypeStruct %20
%22 = OpTypePointer StorageBuffer %21
%23 = OpVariable %22 StorageBuffer
%24 = OpConstant %5 1024
%25 = OpTypeVector %16 4
%26 = OpTypeArray %25 %24
%27 = OpTypeStruct %26
%28 = OpTypePointer Uniform %27
%29 = OpVariable %28 Uniform
%30 = OpTypeArray %25 %24
%31 = OpTypeStruct %30
%32 = OpTypeArray %31 %12
%33 = OpTypePointer Uniform %32
%34 = OpVariable %33 Uniform
%35 = OpConstant %5 0
%36 = OpTypePointer Uniform %31
%38 = OpTypeVector %5 3
%39 = OpTypePointer Input %38
%40 = OpVariable %39 Input
%41 = OpTypePointer Input %5
%44 = OpVariable %39 Input
%47 = OpConstant %5 1
%48 = OpTypePointer Uniform %25
%51 = OpTypeVector %5 4
%54 = OpTypePointer StorageBuffer %5
%62 = OpConstant %5 3
%88 = OpTypePointer StorageBuffer %11
%139 = OpTypeBool
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %183
%183 = OpLabel
%37 = OpAccessChain %36 %34 %35
%42 = OpAccessChain %41 %40 %35
%43 = OpLoad %5 %42
%45 = OpAccessChain %41 %44 %35
%46 = OpLoad %5 %45
%49 = OpAccessChain %48 %29 %35 %47
%50 = OpLoad %25 %49
%52 = OpBitcast %51 %50
%53 = OpCompositeExtract %5 %52 0
%55 = OpAccessChain %54 %23 %35 %35
%56 = OpAtomicIAdd %5 %55 %47 %35 %53
%57 = OpAccessChain %48 %29 %35 %43
%58 = OpLoad %25 %57
%59 = OpBitcast %51 %58
%60 = OpCompositeExtract %5 %59 0
%61 = OpGroupNonUniformBroadcastFirst %5 %62 %60
%63 = OpAccessChain %54 %23 %35 %47
%64 = OpAtomicIAdd %5 %63 %47 %35 %61
%65 = OpAccessChain %48 %37 %35 %47
%66 = OpLoad %25 %65
%67 = OpBitcast %51 %66
%68 = OpCompositeExtract %5 %67 0
%69 = OpGroupNonUniformBroadcastFirst %5 %62 %68
%70 = OpAccessChain %54 %23 %35 %47
%71 = OpAtomicIAdd %5 %70 %47 %35 %69
%72 = OpAccessChain %48 %37 %35 %43
%73 = OpLoad %25 %72
%74 = OpBitcast %51 %73
%75 = OpCompositeExtract %5 %74 0
%76 = OpGroupNonUniformBroadcastFirst %5 %62 %75
%77 = OpAccessChain %54 %23 %35 %47
%78 = OpAtomicIAdd %5 %77 %47 %35 %76
%79 = OpAccessChain %54 %9 %35 %47
%80 = OpLoad %5 %79
%81 = OpAccessChain %54 %23 %35 %35
%82 = OpAtomicIAdd %5 %81 %47 %35 %80
%83 = OpAccessChain %54 %9 %35 %43
%84 = OpLoad %5 %83
%85 = OpGroupNonUniformBroadcastFirst %5 %62 %84
%86 = OpAccessChain %54 %23 %35 %47
%87 = OpAtomicIAdd %5 %86 %47 %35 %85
%89 = OpAccessChain %88 %15 %35
%90 = OpAccessChain %54 %89 %35 %47
%91 = OpLoad %5 %90
%92 = OpGroupNonUniformBroadcastFirst %5 %62 %91
%93 = OpAccessChain %54 %23 %35 %47
%94 = OpAtomicIAdd %5 %93 %47 %35 %92
%95 = OpAccessChain %54 %23 %35 %12
%96 = OpLoad %5 %95
%97 = OpGroupNonUniformBroadcastFirst %5 %62 %96
%98 = OpAccessChain %54 %23 %35 %47
%99 = OpAtomicIAdd %5 %98 %47 %35 %97
%100 = OpLoad %17 %19
%101 = OpImageFetch %25 %100 %35
%102 = OpCompositeExtract %16 %101 0
%103 = OpGroupNonUniformBroadcastFirst %16 %62 %102
%104 = OpConvertFToU %5 %103
%105 = OpAccessChain %54 %23 %35 %47
%106 = OpAtomicIAdd %5 %105 %47 %35 %104
%107 = OpAccessChain %54 %23 %35 %35
%108 = OpAtomicIAdd %5 %107 %47 %35 %46
%109 = OpGroupNonUniformBroadcastFirst %5 %62 %43
%110 = OpAccessChain %54 %23 %35 %47
%111 = OpAtomicIAdd %5 %110 %47 %35 %109
%112 = OpAccessChain %48 %29 %35 %47
%113 = OpLoad %25 %112
%114 = OpBitcast %51 %113
%115 = OpCompositeExtract %5 %114 0
%116 = OpGroupNonUniformBroadcastFirst %5 %62 %115
%117 = OpAccessChain %54 %23 %35 %35
%118 = OpAtomicIAdd %5 %117 %47 %35 %116
%119 = OpAccessChain %48 %29 %35 %43
%120 = OpLoad %25 %119
%121 = OpBitcast %51 %120
%122 = OpCompositeExtract %5 %121 0
%123 = OpGroupNonUniformIAdd %5 %62 Reduce %122
%124 = OpGroupNonUniformBroadcastFirst %5 %62 %123
%125 = OpAccessChain %54 %23 %35 %35
%126 = OpAtomicIAdd %5 %125 %47 %35 %124
%127 = OpAccessChain %48 %29 %35 %43
%128 = OpLoad %25 %127
%129 = OpBitcast %51 %128
%130 = OpCompositeExtract %5 %129 0
%131 = OpGroupNonUniformBitwiseOr %5 %62 Reduce %130
%132 = OpGroupNonUniformBroadcastFirst %5 %62 %131
%133 = OpAccessChain %54 %23 %35 %35
%134 = OpAtomicIAdd %5 %133 %47 %35 %132
%135 = OpAccessChain %48 %29 %35 %43
%136 = OpLoad %25 %135
%137 = OpBitcast %51 %136
%138 = OpCompositeExtract %5 %137 0
%140 = OpGroupNonUniformAllEqual %139 %62 %138
%141 = OpGroupNonUniformBroadcastFirst %139 %62 %140
%142 = OpSelect %5 %141 %47 %35
%143 = OpAccessChain %54 %23 %35 %35
%144 = OpAtomicIAdd %5 %143 %47 %35 %142
%145 = OpAccessChain %48 %29 %35 %43
%146 = OpLoad %25 %145
%147 = OpBitcast %51 %146
%148 = OpCompositeExtract %5 %147 0
%149 = OpINotEqual %139 %148 %35
%150 = OpGroupNonUniformBallot %51 %62 %149
%151 = OpCompositeExtract %5 %150 0
%152 = OpGroupNonUniformBroadcastFirst %5 %62 %151
%153 = OpAccessChain %54 %23 %35 %35
%154 = OpAtomicIAdd %5 %153 %47 %35 %152
%155 = OpAccessChain %48 %29 %35 %43
%156 = OpLoad %25 %155
%157 = OpBitcast %51 %156
%158 = OpCompositeExtract %5 %157 0
%159 = OpINotEqual %139 %158 %35
%160 = OpGroupNonUniformAny %139 %62 %159
%161 = OpGroupNonUniformBroadcastFirst %139 %62 %160
%162 = OpSelect %5 %161 %47 %35
%163 = OpAccessChain %54 %23 %35 %35
%164 = OpAtomicIAdd %5 %163 %47 %35 %162
%165 = OpAccessChain %48 %29 %35 %43
%166 = OpLoad %25 %165
%167 = OpBitcast %51 %166
%168 = OpCompositeExtract %5 %167 0
%169 = OpINotEqual %139 %168 %35
%170 = OpGroupNonUniformAll %139 %62 %169
%171 = OpGroupNonUniformBroadcastFirst %139 %62 %170
%172 = OpSelect %5 %171 %47 %35
%173 = OpAccessChain %54 %23 %35 %35
%174 = OpAtomicIAdd %5 %173 %47 %35 %172
%175 = OpAccessChain %48 %29 %35 %43
%176 = OpLoad %25 %175
%177 = OpBitcast %51 %176
%178 = OpCompositeExtract %5 %177 0
%179 = OpGroupNonUniformIAdd %5 %62 ExclusiveScan %178
%180 = OpGroupNonUniformBroadcastFirst %5 %62 %179
%181 = OpAccessChain %54 %23 %35 %47
%182 = OpAtomicIAdd %5 %181 %47 %35 %180
OpReturn
OpFunctionEnd
#endif
