#version 460
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uint _m0[];
} _9;

layout(set = 0, binding = 1, std430) restrict readonly buffer _11_15
{
    uint _m0[];
} _15[2];

layout(set = 0, binding = 0, std430) buffer _21_23
{
    uint _m0[];
} _23;

layout(set = 0, binding = 0, std140) uniform _27_29
{
    vec4 _m0[1024];
} _29;

layout(set = 0, binding = 1, std140) uniform _31_34
{
    vec4 _m0[1024];
} _34[2];

layout(set = 0, binding = 3) uniform samplerBuffer _19;

void main()
{
    uint _57 = atomicAdd(_23._m0[0u], floatBitsToUint(_29._m0[1u]).x);
    uint _65 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x));
    uint _72 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_34[0u]._m0[1u]).x));
    uint _79 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_34[0u]._m0[gl_GlobalInvocationID.x]).x));
    uint _83 = atomicAdd(_23._m0[0u], _9._m0[1u]);
    uint _88 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(_9._m0[gl_GlobalInvocationID.x]));
    uint _95 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(_15[0u]._m0[1u]));
    uint _100 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(_23._m0[2u]));
    uint _106 = atomicAdd(_23._m0[1u], uint(subgroupBroadcastFirst(texelFetch(_19, int(0u)).x)));
    uint _108 = atomicAdd(_23._m0[0u], gl_WorkGroupID.x);
    uint _111 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(gl_GlobalInvocationID.x));
    uint _118 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(floatBitsToUint(_29._m0[1u]).x));
    uint _126 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(subgroupAdd(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x)));
    uint _134 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(subgroupOr(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x)));
    uint _144 = atomicAdd(_23._m0[0u], uint(subgroupBroadcastFirst(subgroupAllEqual(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x))));
    uint _154 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(subgroupBallot(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x != 0u).x));
    uint _164 = atomicAdd(_23._m0[0u], uint(subgroupBroadcastFirst(subgroupAny(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _174 = atomicAdd(_23._m0[0u], uint(subgroupBroadcastFirst(subgroupAll(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _182 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(subgroupExclusiveAdd(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x)));
}


#if 0
// SPIR-V disassembly
// HeuristicWaveSize(32)
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 185
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability StorageBufferArrayDynamicIndexing
OpCapability SampledBuffer
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %41 %45
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %21 "SSBO"
OpName %27 ""
OpName %31 ""
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 1
OpDecorate %15 NonWritable
OpDecorate %15 Restrict
OpDecorate %19 DescriptorSet 0
OpDecorate %19 Binding 3
OpDecorate %20 ArrayStride 4
OpMemberDecorate %21 0 Offset 0
OpDecorate %21 Block
OpDecorate %23 DescriptorSet 0
OpDecorate %23 Binding 0
OpDecorate %26 ArrayStride 16
OpMemberDecorate %27 0 Offset 0
OpDecorate %27 Block
OpDecorate %29 DescriptorSet 0
OpDecorate %29 Binding 0
OpDecorate %30 ArrayStride 16
OpMemberDecorate %31 0 Offset 0
OpDecorate %31 Block
OpDecorate %34 DescriptorSet 0
OpDecorate %34 Binding 1
OpDecorate %41 BuiltIn GlobalInvocationId
OpDecorate %45 BuiltIn WorkgroupId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpConstant %5 2
%13 = OpTypeArray %11 %12
%14 = OpTypePointer StorageBuffer %13
%15 = OpVariable %14 StorageBuffer
%16 = OpTypeFloat 32
%17 = OpTypeImage %16 Buffer 0 0 0 1 Unknown
%18 = OpTypePointer UniformConstant %17
%19 = OpVariable %18 UniformConstant
%20 = OpTypeRuntimeArray %5
%21 = OpTypeStruct %20
%22 = OpTypePointer StorageBuffer %21
%23 = OpVariable %22 StorageBuffer
%24 = OpConstant %5 1024
%25 = OpTypeVector %16 4
%26 = OpTypeArray %25 %24
%27 = OpTypeStruct %26
%28 = OpTypePointer Uniform %27
%29 = OpVariable %28 Uniform
%30 = OpTypeArray %25 %24
%31 = OpTypeStruct %30
%32 = OpTypeArray %31 %12
%33 = OpTypePointer Uniform %32
%34 = OpVariable %33 Uniform
%36 = OpConstant %5 0
%37 = OpTypePointer Uniform %31
%39 = OpTypeVector %5 3
%40 = OpTypePointer Input %39
%41 = OpVariable %40 Input
%42 = OpTypePointer Input %5
%45 = OpVariable %40 Input
%48 = OpConstant %5 1
%49 = OpTypePointer Uniform %25
%52 = OpTypeVector %5 4
%55 = OpTypePointer StorageBuffer %5
%63 = OpConstant %5 3
%89 = OpTypePointer StorageBuffer %11
%139 = OpTypeBool
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %183
%183 = OpLabel
%35 = OpLoad %17 %19
%38 = OpAccessChain %37 %34 %36
%43 = OpAccessChain %42 %41 %36
%44 = OpLoad %5 %43
%46 = OpAccessChain %42 %45 %36
%47 = OpLoad %5 %46
%50 = OpAccessChain %49 %29 %36 %48
%51 = OpLoad %25 %50
%53 = OpBitcast %52 %51
%54 = OpCompositeExtract %5 %53 0
%56 = OpAccessChain %55 %23 %36 %36
%57 = OpAtomicIAdd %5 %56 %48 %36 %54
%58 = OpAccessChain %49 %29 %36 %44
%59 = OpLoad %25 %58
%60 = OpBitcast %52 %59
%61 = OpCompositeExtract %5 %60 0
%62 = OpGroupNonUniformBroadcastFirst %5 %63 %61
%64 = OpAccessChain %55 %23 %36 %48
%65 = OpAtomicIAdd %5 %64 %48 %36 %62
%66 = OpAccessChain %49 %38 %36 %48
%67 = OpLoad %25 %66
%68 = OpBitcast %52 %67
%69 = OpCompositeExtract %5 %68 0
%70 = OpGroupNonUniformBroadcastFirst %5 %63 %69
%71 = OpAccessChain %55 %23 %36 %48
%72 = OpAtomicIAdd %5 %71 %48 %36 %70
%73 = OpAccessChain %49 %38 %36 %44
%74 = OpLoad %25 %73
%75 = OpBitcast %52 %74
%76 = OpCompositeExtract %5 %75 0
%77 = OpGroupNonUniformBroadcastFirst %5 %63 %76
%78 = OpAccessChain %55 %23 %36 %48
%79 = OpAtomicIAdd %5 %78 %48 %36 %77
%80 = OpAccessChain %55 %9 %36 %48
%81 = OpLoad %5 %80
%82 = OpAccessChain %55 %23 %36 %36
%83 = OpAtomicIAdd %5 %82 %48 %36 %81
%84 = OpAccessChain %55 %9 %36 %44
%85 = OpLoad %5 %84
%86 = OpGroupNonUniformBroadcastFirst %5 %63 %85
%87 = OpAccessChain %55 %23 %36 %48
%88 = OpAtomicIAdd %5 %87 %48 %36 %86
%90 = OpAccessChain %89 %15 %36
%91 = OpAccessChain %55 %90 %36 %48
%92 = OpLoad %5 %91
%93 = OpGroupNonUniformBroadcastFirst %5 %63 %92
%94 = OpAccessChain %55 %23 %36 %48
%95 = OpAtomicIAdd %5 %94 %48 %36 %93
%96 = OpAccessChain %55 %23 %36 %12
%97 = OpLoad %5 %96
%98 = OpGroupNonUniformBroadcastFirst %5 %63 %97
%99 = OpAccessChain %55 %23 %36 %48
%100 = OpAtomicIAdd %5 %99 %48 %36 %98
%101 = OpImageFetch %25 %35 %36
%102 = OpCompositeExtract %16 %101 0
%103 = OpGroupNonUniformBroadcastFirst %16 %63 %102
%104 = OpConvertFToU %5 %103
%105 = OpAccessChain %55 %23 %36 %48
%106 = OpAtomicIAdd %5 %105 %48 %36 %104
%107 = OpAccessChain %55 %23 %36 %36
%108 = OpAtomicIAdd %5 %107 %48 %36 %47
%109 = OpGroupNonUniformBroadcastFirst %5 %63 %44
%110 = OpAccessChain %55 %23 %36 %48
%111 = OpAtomicIAdd %5 %110 %48 %36 %109
%112 = OpAccessChain %49 %29 %36 %48
%113 = OpLoad %25 %112
%114 = OpBitcast %52 %113
%115 = OpCompositeExtract %5 %114 0
%116 = OpGroupNonUniformBroadcastFirst %5 %63 %115
%117 = OpAccessChain %55 %23 %36 %36
%118 = OpAtomicIAdd %5 %117 %48 %36 %116
%119 = OpAccessChain %49 %29 %36 %44
%120 = OpLoad %25 %119
%121 = OpBitcast %52 %120
%122 = OpCompositeExtract %5 %121 0
%123 = OpGroupNonUniformIAdd %5 %63 Reduce %122
%124 = OpGroupNonUniformBroadcastFirst %5 %63 %123
%125 = OpAccessChain %55 %23 %36 %36
%126 = OpAtomicIAdd %5 %125 %48 %36 %124
%127 = OpAccessChain %49 %29 %36 %44
%128 = OpLoad %25 %127
%129 = OpBitcast %52 %128
%130 = OpCompositeExtract %5 %129 0
%131 = OpGroupNonUniformBitwiseOr %5 %63 Reduce %130
%132 = OpGroupNonUniformBroadcastFirst %5 %63 %131
%133 = OpAccessChain %55 %23 %36 %36
%134 = OpAtomicIAdd %5 %133 %48 %36 %132
%135 = OpAccessChain %49 %29 %36 %44
%136 = OpLoad %25 %135
%137 = OpBitcast %52 %136
%138 = OpCompositeExtract %5 %137 0
%140 = OpGroupNonUniformAllEqual %139 %63 %138
%141 = OpGroupNonUniformBroadcastFirst %139 %63 %140
%142 = OpSelect %5 %141 %48 %36
%143 = OpAccessChain %55 %23 %36 %36
%144 = OpAtomicIAdd %5 %143 %48 %36 %142
%145 = OpAccessChain %49 %29 %36 %44
%146 = OpLoad %25 %145
%147 = OpBitcast %52 %146
%148 = OpCompositeExtract %5 %147 0
%149 = OpINotEqual %139 %148 %36
%150 = OpGroupNonUniformBallot %52 %63 %149
%151 = OpCompositeExtract %5 %150 0
%152 = OpGroupNonUniformBroadcastFirst %5 %63 %151
%153 = OpAccessChain %55 %23 %36 %36
%154 = OpAtomicIAdd %5 %153 %48 %36 %152
%155 = OpAccessChain %49 %29 %36 %44
%156 = OpLoad %25 %155
%157 = OpBitcast %52 %156
%158 = OpCompositeExtract %5 %157 0
%159 = OpINotEqual %139 %158 %36
%160 = OpGroupNonUniformAny %139 %63 %159
%161 = OpGroupNonUniformBroadcastFirst %139 %63 %160
%162 = OpSelect %5 %161 %48 %36
%163 = OpAccessChain %55 %23 %36 %36
%164 = OpAtomicIAdd %5 %163 %48 %36 %162
%165 = OpAccessChain %49 %29 %36 %44
%166 = OpLoad %25 %165
%167 = OpBitcast %52 %166
%168 = OpCompositeExtract %5 %167 0
%169 = OpINotEqual %139 %168 %36
%170 = OpGroupNonUniformAll %139 %63 %169
%171 = OpGroupNonUniformBroadcastFirst %139 %63 %170
%172 = OpSelect %5 %171 %48 %36
%173 = OpAccessChain %55 %23 %36 %36
%174 = OpAtomicIAdd %5 %173 %48 %36 %172
%175 = OpAccessChain %49 %29 %36 %44
%176 = OpLoad %25 %175
%177 = OpBitcast %52 %176
%178 = OpCompositeExtract %5 %177 0
%179 = OpGroupNonUniformIAdd %5 %63 ExclusiveScan %178
%180 = OpGroupNonUniformBroadcastFirst %5 %63 %179
%181 = OpAccessChain %55 %23 %36 %48
%182 = OpAtomicIAdd %5 %181 %48 %36 %180
OpReturn
OpFunctionEnd
#endif
