#version 460
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std140) uniform _23_25
{
    vec4 _m0[1024];
} _25;

layout(set = 0, binding = 1, std140) uniform _27_30
{
    vec4 _m0[1024];
} _30[2];

layout(set = 0, binding = 0) uniform usamplerBuffer _8;
layout(set = 0, binding = 1) uniform usamplerBuffer _12[2];
layout(set = 0, binding = 3) uniform samplerBuffer _16;
layout(set = 0, binding = 0, r32ui) uniform uimageBuffer _19;

void main()
{
    uint _55 = imageAtomicAdd(_19, int(0u), floatBitsToUint(_25._m0[1u]).x);
    uint _63 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x));
    uint _70 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(floatBitsToUint(_30[0u]._m0[1u]).x));
    uint _77 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(floatBitsToUint(_30[0u]._m0[gl_GlobalInvocationID.x]).x));
    uint _82 = imageAtomicAdd(_19, int(0u), subgroupBroadcastFirst(texelFetch(_8, int(1u)).x));
    uint _87 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(texelFetch(_8, int(gl_GlobalInvocationID.x)).x));
    uint _94 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(texelFetch(_12[0u], int(1u)).x));
    uint _99 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(imageLoad(_19, int(2u)).x));
    uint _105 = imageAtomicAdd(_19, int(1u), uint(subgroupBroadcastFirst(texelFetch(_16, int(0u)).x)));
    uint _107 = imageAtomicAdd(_19, int(0u), gl_WorkGroupID.x);
    uint _110 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(gl_GlobalInvocationID.x));
    uint _117 = imageAtomicAdd(_19, int(0u), subgroupBroadcastFirst(floatBitsToUint(_25._m0[1u]).x));
    uint _125 = imageAtomicAdd(_19, int(0u), subgroupBroadcastFirst(subgroupAdd(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x)));
    uint _133 = imageAtomicAdd(_19, int(0u), subgroupBroadcastFirst(subgroupOr(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x)));
    uint _143 = imageAtomicAdd(_19, int(0u), uint(subgroupBroadcastFirst(subgroupAllEqual(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x))));
    uint _153 = imageAtomicAdd(_19, int(0u), subgroupBroadcastFirst(subgroupBallot(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x != 0u).x));
    uint _163 = imageAtomicAdd(_19, int(0u), uint(subgroupBroadcastFirst(subgroupAny(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _173 = imageAtomicAdd(_19, int(0u), uint(subgroupBroadcastFirst(subgroupAll(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _181 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(subgroupExclusiveAdd(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x)));
}


#if 0
// SPIR-V disassembly
// HeuristicWaveSize(32)
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 184
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability SampledBuffer
OpCapability ImageBuffer
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpCapability UniformTexelBufferArrayDynamicIndexing
OpExtension "SPV_EXT_descriptor_indexing"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %39 %43
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %23 ""
OpName %27 ""
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %12 DescriptorSet 0
OpDecorate %12 Binding 1
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 3
OpDecorate %19 DescriptorSet 0
OpDecorate %19 Binding 0
OpDecorate %22 ArrayStride 16
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %25 DescriptorSet 0
OpDecorate %25 Binding 0
OpDecorate %26 ArrayStride 16
OpMemberDecorate %27 0 Offset 0
OpDecorate %27 Block
OpDecorate %30 DescriptorSet 0
OpDecorate %30 Binding 1
OpDecorate %39 BuiltIn GlobalInvocationId
OpDecorate %43 BuiltIn WorkgroupId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeImage %5 Buffer 0 0 0 1 Unknown
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpConstant %5 2
%10 = OpTypeArray %6 %9
%11 = OpTypePointer UniformConstant %10
%12 = OpVariable %11 UniformConstant
%13 = OpTypeFloat 32
%14 = OpTypeImage %13 Buffer 0 0 0 1 Unknown
%15 = OpTypePointer UniformConstant %14
%16 = OpVariable %15 UniformConstant
%17 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%18 = OpTypePointer UniformConstant %17
%19 = OpVariable %18 UniformConstant
%20 = OpConstant %5 1024
%21 = OpTypeVector %13 4
%22 = OpTypeArray %21 %20
%23 = OpTypeStruct %22
%24 = OpTypePointer Uniform %23
%25 = OpVariable %24 Uniform
%26 = OpTypeArray %21 %20
%27 = OpTypeStruct %26
%28 = OpTypeArray %27 %9
%29 = OpTypePointer Uniform %28
%30 = OpVariable %29 Uniform
%34 = OpConstant %5 0
%35 = OpTypePointer Uniform %27
%37 = OpTypeVector %5 3
%38 = OpTypePointer Input %37
%39 = OpVariable %38 Input
%40 = OpTypePointer Input %5
%43 = OpVariable %38 Input
%46 = OpConstant %5 1
%47 = OpTypePointer Uniform %21
%50 = OpTypeVector %5 4
%53 = OpTypePointer Image %5
%61 = OpConstant %5 3
%138 = OpTypeBool
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %182
%182 = OpLabel
%31 = OpLoad %17 %19
%32 = OpLoad %14 %16
%33 = OpLoad %6 %8
%36 = OpAccessChain %35 %30 %34
%41 = OpAccessChain %40 %39 %34
%42 = OpLoad %5 %41
%44 = OpAccessChain %40 %43 %34
%45 = OpLoad %5 %44
%48 = OpAccessChain %47 %25 %34 %46
%49 = OpLoad %21 %48
%51 = OpBitcast %50 %49
%52 = OpCompositeExtract %5 %51 0
%54 = OpImageTexelPointer %53 %19 %34 %34
%55 = OpAtomicIAdd %5 %54 %46 %34 %52
%56 = OpAccessChain %47 %25 %34 %42
%57 = OpLoad %21 %56
%58 = OpBitcast %50 %57
%59 = OpCompositeExtract %5 %58 0
%60 = OpGroupNonUniformBroadcastFirst %5 %61 %59
%62 = OpImageTexelPointer %53 %19 %46 %34
%63 = OpAtomicIAdd %5 %62 %46 %34 %60
%64 = OpAccessChain %47 %36 %34 %46
%65 = OpLoad %21 %64
%66 = OpBitcast %50 %65
%67 = OpCompositeExtract %5 %66 0
%68 = OpGroupNonUniformBroadcastFirst %5 %61 %67
%69 = OpImageTexelPointer %53 %19 %46 %34
%70 = OpAtomicIAdd %5 %69 %46 %34 %68
%71 = OpAccessChain %47 %36 %34 %42
%72 = OpLoad %21 %71
%73 = OpBitcast %50 %72
%74 = OpCompositeExtract %5 %73 0
%75 = OpGroupNonUniformBroadcastFirst %5 %61 %74
%76 = OpImageTexelPointer %53 %19 %46 %34
%77 = OpAtomicIAdd %5 %76 %46 %34 %75
%78 = OpImageFetch %50 %33 %46
%79 = OpCompositeExtract %5 %78 0
%80 = OpGroupNonUniformBroadcastFirst %5 %61 %79
%81 = OpImageTexelPointer %53 %19 %34 %34
%82 = OpAtomicIAdd %5 %81 %46 %34 %80
%83 = OpImageFetch %50 %33 %42
%84 = OpCompositeExtract %5 %83 0
%85 = OpGroupNonUniformBroadcastFirst %5 %61 %84
%86 = OpImageTexelPointer %53 %19 %46 %34
%87 = OpAtomicIAdd %5 %86 %46 %34 %85
%88 = OpAccessChain %7 %12 %34
%89 = OpLoad %6 %88
%90 = OpImageFetch %50 %89 %46
%91 = OpCompositeExtract %5 %90 0
%92 = OpGroupNonUniformBroadcastFirst %5 %61 %91
%93 = OpImageTexelPointer %53 %19 %46 %34
%94 = OpAtomicIAdd %5 %93 %46 %34 %92
%95 = OpImageRead %50 %31 %9
%96 = OpCompositeExtract %5 %95 0
%97 = OpGroupNonUniformBroadcastFirst %5 %61 %96
%98 = OpImageTexelPointer %53 %19 %46 %34
%99 = OpAtomicIAdd %5 %98 %46 %34 %97
%100 = OpImageFetch %21 %32 %34
%101 = OpCompositeExtract %13 %100 0
%102 = OpGroupNonUniformBroadcastFirst %13 %61 %101
%103 = OpConvertFToU %5 %102
%104 = OpImageTexelPointer %53 %19 %46 %34
%105 = OpAtomicIAdd %5 %104 %46 %34 %103
%106 = OpImageTexelPointer %53 %19 %34 %34
%107 = OpAtomicIAdd %5 %106 %46 %34 %45
%108 = OpGroupNonUniformBroadcastFirst %5 %61 %42
%109 = OpImageTexelPointer %53 %19 %46 %34
%110 = OpAtomicIAdd %5 %109 %46 %34 %108
%111 = OpAccessChain %47 %25 %34 %46
%112 = OpLoad %21 %111
%113 = OpBitcast %50 %112
%114 = OpCompositeExtract %5 %113 0
%115 = OpGroupNonUniformBroadcastFirst %5 %61 %114
%116 = OpImageTexelPointer %53 %19 %34 %34
%117 = OpAtomicIAdd %5 %116 %46 %34 %115
%118 = OpAccessChain %47 %25 %34 %42
%119 = OpLoad %21 %118
%120 = OpBitcast %50 %119
%121 = OpCompositeExtract %5 %120 0
%122 = OpGroupNonUniformIAdd %5 %61 Reduce %121
%123 = OpGroupNonUniformBroadcastFirst %5 %61 %122
%124 = OpImageTexelPointer %53 %19 %34 %34
%125 = OpAtomicIAdd %5 %124 %46 %34 %123
%126 = OpAccessChain %47 %25 %34 %42
%127 = OpLoad %21 %126
%128 = OpBitcast %50 %127
%129 = OpCompositeExtract %5 %128 0
%130 = OpGroupNonUniformBitwiseOr %5 %61 Reduce %129
%131 = OpGroupNonUniformBroadcastFirst %5 %61 %130
%132 = OpImageTexelPointer %53 %19 %34 %34
%133 = OpAtomicIAdd %5 %132 %46 %34 %131
%134 = OpAccessChain %47 %25 %34 %42
%135 = OpLoad %21 %134
%136 = OpBitcast %50 %135
%137 = OpCompositeExtract %5 %136 0
%139 = OpGroupNonUniformAllEqual %138 %61 %137
%140 = OpGroupNonUniformBroadcastFirst %138 %61 %139
%141 = OpSelect %5 %140 %46 %34
%142 = OpImageTexelPointer %53 %19 %34 %34
%143 = OpAtomicIAdd %5 %142 %46 %34 %141
%144 = OpAccessChain %47 %25 %34 %42
%145 = OpLoad %21 %144
%146 = OpBitcast %50 %145
%147 = OpCompositeExtract %5 %146 0
%148 = OpINotEqual %138 %147 %34
%149 = OpGroupNonUniformBallot %50 %61 %148
%150 = OpCompositeExtract %5 %149 0
%151 = OpGroupNonUniformBroadcastFirst %5 %61 %150
%152 = OpImageTexelPointer %53 %19 %34 %34
%153 = OpAtomicIAdd %5 %152 %46 %34 %151
%154 = OpAccessChain %47 %25 %34 %42
%155 = OpLoad %21 %154
%156 = OpBitcast %50 %155
%157 = OpCompositeExtract %5 %156 0
%158 = OpINotEqual %138 %157 %34
%159 = OpGroupNonUniformAny %138 %61 %158
%160 = OpGroupNonUniformBroadcastFirst %138 %61 %159
%161 = OpSelect %5 %160 %46 %34
%162 = OpImageTexelPointer %53 %19 %34 %34
%163 = OpAtomicIAdd %5 %162 %46 %34 %161
%164 = OpAccessChain %47 %25 %34 %42
%165 = OpLoad %21 %164
%166 = OpBitcast %50 %165
%167 = OpCompositeExtract %5 %166 0
%168 = OpINotEqual %138 %167 %34
%169 = OpGroupNonUniformAll %138 %61 %168
%170 = OpGroupNonUniformBroadcastFirst %138 %61 %169
%171 = OpSelect %5 %170 %46 %34
%172 = OpImageTexelPointer %53 %19 %34 %34
%173 = OpAtomicIAdd %5 %172 %46 %34 %171
%174 = OpAccessChain %47 %25 %34 %42
%175 = OpLoad %21 %174
%176 = OpBitcast %50 %175
%177 = OpCompositeExtract %5 %176 0
%178 = OpGroupNonUniformIAdd %5 %61 ExclusiveScan %177
%179 = OpGroupNonUniformBroadcastFirst %5 %61 %178
%180 = OpImageTexelPointer %53 %19 %46 %34
%181 = OpAtomicIAdd %5 %180 %46 %34 %179
OpReturn
OpFunctionEnd
#endif
