#version 460
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std140) uniform _23_25
{
    vec4 _m0[1024];
} _25;

layout(set = 0, binding = 1, std140) uniform _27_30
{
    vec4 _m0[1024];
} _30[2];

layout(set = 0, binding = 0) uniform usamplerBuffer _8;
layout(set = 0, binding = 1) uniform usamplerBuffer _12[2];
layout(set = 0, binding = 3) uniform samplerBuffer _16;
layout(set = 0, binding = 0, r32ui) uniform uimageBuffer _19;

void main()
{
    uint _55 = imageAtomicAdd(_19, int(0u), floatBitsToUint(_25._m0[1u]).x);
    uint _63 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x));
    uint _70 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(floatBitsToUint(_30[0u]._m0[1u]).x));
    uint _77 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(floatBitsToUint(_30[0u]._m0[gl_GlobalInvocationID.x]).x));
    uint _82 = imageAtomicAdd(_19, int(0u), subgroupBroadcastFirst(texelFetch(_8, int(1u)).x));
    uint _87 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(texelFetch(_8, int(gl_GlobalInvocationID.x)).x));
    uint _94 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(texelFetch(_12[0u], int(1u)).x));
    uint _99 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(imageLoad(_19, int(2u)).x));
    uint _105 = imageAtomicAdd(_19, int(1u), uint(subgroupBroadcastFirst(texelFetch(_16, int(0u)).x)));
    uint _107 = imageAtomicAdd(_19, int(0u), gl_WorkGroupID.x);
    uint _110 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(gl_GlobalInvocationID.x));
    uint _116 = imageAtomicAdd(_19, int(0u), floatBitsToUint(_25._m0[1u]).x);
    uint _124 = imageAtomicAdd(_19, int(0u), subgroupBroadcastFirst(subgroupAdd(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x)));
    uint _132 = imageAtomicAdd(_19, int(0u), subgroupBroadcastFirst(subgroupOr(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x)));
    uint _142 = imageAtomicAdd(_19, int(0u), uint(subgroupBroadcastFirst(subgroupAllEqual(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x))));
    uint _152 = imageAtomicAdd(_19, int(0u), subgroupBroadcastFirst(subgroupBallot(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x != 0u).x));
    uint _162 = imageAtomicAdd(_19, int(0u), uint(subgroupBroadcastFirst(subgroupAny(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _172 = imageAtomicAdd(_19, int(0u), uint(subgroupBroadcastFirst(subgroupAll(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _180 = imageAtomicAdd(_19, int(1u), subgroupBroadcastFirst(subgroupExclusiveAdd(floatBitsToUint(_25._m0[gl_GlobalInvocationID.x]).x)));
}


#if 0
// SPIR-V disassembly
// HeuristicWaveSize(32)
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 183
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability SampledBuffer
OpCapability ImageBuffer
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpCapability UniformTexelBufferArrayDynamicIndexing
OpExtension "SPV_EXT_descriptor_indexing"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %39 %43
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %23 ""
OpName %27 ""
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %12 DescriptorSet 0
OpDecorate %12 Binding 1
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 3
OpDecorate %19 DescriptorSet 0
OpDecorate %19 Binding 0
OpDecorate %22 ArrayStride 16
OpMemberDecorate %23 0 Offset 0
OpDecorate %23 Block
OpDecorate %25 DescriptorSet 0
OpDecorate %25 Binding 0
OpDecorate %26 ArrayStride 16
OpMemberDecorate %27 0 Offset 0
OpDecorate %27 Block
OpDecorate %30 DescriptorSet 0
OpDecorate %30 Binding 1
OpDecorate %39 BuiltIn GlobalInvocationId
OpDecorate %43 BuiltIn WorkgroupId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeImage %5 Buffer 0 0 0 1 Unknown
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpConstant %5 2
%10 = OpTypeArray %6 %9
%11 = OpTypePointer UniformConstant %10
%12 = OpVariable %11 UniformConstant
%13 = OpTypeFloat 32
%14 = OpTypeImage %13 Buffer 0 0 0 1 Unknown
%15 = OpTypePointer UniformConstant %14
%16 = OpVariable %15 UniformConstant
%17 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%18 = OpTypePointer UniformConstant %17
%19 = OpVariable %18 UniformConstant
%20 = OpConstant %5 1024
%21 = OpTypeVector %13 4
%22 = OpTypeArray %21 %20
%23 = OpTypeStruct %22
%24 = OpTypePointer Uniform %23
%25 = OpVariable %24 Uniform
%26 = OpTypeArray %21 %20
%27 = OpTypeStruct %26
%28 = OpTypeArray %27 %9
%29 = OpTypePointer Uniform %28
%30 = OpVariable %29 Uniform
%34 = OpConstant %5 0
%35 = OpTypePointer Uniform %27
%37 = OpTypeVector %5 3
%38 = OpTypePointer Input %37
%39 = OpVariable %38 Input
%40 = OpTypePointer Input %5
%43 = OpVariable %38 Input
%46 = OpConstant %5 1
%47 = OpTypePointer Uniform %21
%50 = OpTypeVector %5 4
%53 = OpTypePointer Image %5
%61 = OpConstant %5 3
%137 = OpTypeBool
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %181
%181 = OpLabel
%31 = OpLoad %17 %19
%32 = OpLoad %14 %16
%33 = OpLoad %6 %8
%36 = OpAccessChain %35 %30 %34
%41 = OpAccessChain %40 %39 %34
%42 = OpLoad %5 %41
%44 = OpAccessChain %40 %43 %34
%45 = OpLoad %5 %44
%48 = OpAccessChain %47 %25 %34 %46
%49 = OpLoad %21 %48
%51 = OpBitcast %50 %49
%52 = OpCompositeExtract %5 %51 0
%54 = OpImageTexelPointer %53 %19 %34 %34
%55 = OpAtomicIAdd %5 %54 %46 %34 %52
%56 = OpAccessChain %47 %25 %34 %42
%57 = OpLoad %21 %56
%58 = OpBitcast %50 %57
%59 = OpCompositeExtract %5 %58 0
%60 = OpGroupNonUniformBroadcastFirst %5 %61 %59
%62 = OpImageTexelPointer %53 %19 %46 %34
%63 = OpAtomicIAdd %5 %62 %46 %34 %60
%64 = OpAccessChain %47 %36 %34 %46
%65 = OpLoad %21 %64
%66 = OpBitcast %50 %65
%67 = OpCompositeExtract %5 %66 0
%68 = OpGroupNonUniformBroadcastFirst %5 %61 %67
%69 = OpImageTexelPointer %53 %19 %46 %34
%70 = OpAtomicIAdd %5 %69 %46 %34 %68
%71 = OpAccessChain %47 %36 %34 %42
%72 = OpLoad %21 %71
%73 = OpBitcast %50 %72
%74 = OpCompositeExtract %5 %73 0
%75 = OpGroupNonUniformBroadcastFirst %5 %61 %74
%76 = OpImageTexelPointer %53 %19 %46 %34
%77 = OpAtomicIAdd %5 %76 %46 %34 %75
%78 = OpImageFetch %50 %33 %46
%79 = OpCompositeExtract %5 %78 0
%80 = OpGroupNonUniformBroadcastFirst %5 %61 %79
%81 = OpImageTexelPointer %53 %19 %34 %34
%82 = OpAtomicIAdd %5 %81 %46 %34 %80
%83 = OpImageFetch %50 %33 %42
%84 = OpCompositeExtract %5 %83 0
%85 = OpGroupNonUniformBroadcastFirst %5 %61 %84
%86 = OpImageTexelPointer %53 %19 %46 %34
%87 = OpAtomicIAdd %5 %86 %46 %34 %85
%88 = OpAccessChain %7 %12 %34
%89 = OpLoad %6 %88
%90 = OpImageFetch %50 %89 %46
%91 = OpCompositeExtract %5 %90 0
%92 = OpGroupNonUniformBroadcastFirst %5 %61 %91
%93 = OpImageTexelPointer %53 %19 %46 %34
%94 = OpAtomicIAdd %5 %93 %46 %34 %92
%95 = OpImageRead %50 %31 %9
%96 = OpCompositeExtract %5 %95 0
%97 = OpGroupNonUniformBroadcastFirst %5 %61 %96
%98 = OpImageTexelPointer %53 %19 %46 %34
%99 = OpAtomicIAdd %5 %98 %46 %34 %97
%100 = OpImageFetch %21 %32 %34
%101 = OpCompositeExtract %13 %100 0
%102 = OpGroupNonUniformBroadcastFirst %13 %61 %101
%103 = OpConvertFToU %5 %102
%104 = OpImageTexelPointer %53 %19 %46 %34
%105 = OpAtomicIAdd %5 %104 %46 %34 %103
%106 = OpImageTexelPointer %53 %19 %34 %34
%107 = OpAtomicIAdd %5 %106 %46 %34 %45
%108 = OpGroupNonUniformBroadcastFirst %5 %61 %42
%109 = OpImageTexelPointer %53 %19 %46 %34
%110 = OpAtomicIAdd %5 %109 %46 %34 %108
%111 = OpAccessChain %47 %25 %34 %46
%112 = OpLoad %21 %111
%113 = OpBitcast %50 %112
%114 = OpCompositeExtract %5 %113 0
%115 = OpImageTexelPointer %53 %19 %34 %34
%116 = OpAtomicIAdd %5 %115 %46 %34 %114
%117 = OpAccessChain %47 %25 %34 %42
%118 = OpLoad %21 %117
%119 = OpBitcast %50 %118
%120 = OpCompositeExtract %5 %119 0
%121 = OpGroupNonUniformIAdd %5 %61 Reduce %120
%122 = OpGroupNonUniformBroadcastFirst %5 %61 %121
%123 = OpImageTexelPointer %53 %19 %34 %34
%124 = OpAtomicIAdd %5 %123 %46 %34 %122
%125 = OpAccessChain %47 %25 %34 %42
%126 = OpLoad %21 %125
%127 = OpBitcast %50 %126
%128 = OpCompositeExtract %5 %127 0
%129 = OpGroupNonUniformBitwiseOr %5 %61 Reduce %128
%130 = OpGroupNonUniformBroadcastFirst %5 %61 %129
%131 = OpImageTexelPointer %53 %19 %34 %34
%132 = OpAtomicIAdd %5 %131 %46 %34 %130
%133 = OpAccessChain %47 %25 %34 %42
%134 = OpLoad %21 %133
%135 = OpBitcast %50 %134
%136 = OpCompositeExtract %5 %135 0
%138 = OpGroupNonUniformAllEqual %137 %61 %136
%139 = OpGroupNonUniformBroadcastFirst %137 %61 %138
%140 = OpSelect %5 %139 %46 %34
%141 = OpImageTexelPointer %53 %19 %34 %34
%142 = OpAtomicIAdd %5 %141 %46 %34 %140
%143 = OpAccessChain %47 %25 %34 %42
%144 = OpLoad %21 %143
%145 = OpBitcast %50 %144
%146 = OpCompositeExtract %5 %145 0
%147 = OpINotEqual %137 %146 %34
%148 = OpGroupNonUniformBallot %50 %61 %147
%149 = OpCompositeExtract %5 %148 0
%150 = OpGroupNonUniformBroadcastFirst %5 %61 %149
%151 = OpImageTexelPointer %53 %19 %34 %34
%152 = OpAtomicIAdd %5 %151 %46 %34 %150
%153 = OpAccessChain %47 %25 %34 %42
%154 = OpLoad %21 %153
%155 = OpBitcast %50 %154
%156 = OpCompositeExtract %5 %155 0
%157 = OpINotEqual %137 %156 %34
%158 = OpGroupNonUniformAny %137 %61 %157
%159 = OpGroupNonUniformBroadcastFirst %137 %61 %158
%160 = OpSelect %5 %159 %46 %34
%161 = OpImageTexelPointer %53 %19 %34 %34
%162 = OpAtomicIAdd %5 %161 %46 %34 %160
%163 = OpAccessChain %47 %25 %34 %42
%164 = OpLoad %21 %163
%165 = OpBitcast %50 %164
%166 = OpCompositeExtract %5 %165 0
%167 = OpINotEqual %137 %166 %34
%168 = OpGroupNonUniformAll %137 %61 %167
%169 = OpGroupNonUniformBroadcastFirst %137 %61 %168
%170 = OpSelect %5 %169 %46 %34
%171 = OpImageTexelPointer %53 %19 %34 %34
%172 = OpAtomicIAdd %5 %171 %46 %34 %170
%173 = OpAccessChain %47 %25 %34 %42
%174 = OpLoad %21 %173
%175 = OpBitcast %50 %174
%176 = OpCompositeExtract %5 %175 0
%177 = OpGroupNonUniformIAdd %5 %61 ExclusiveScan %176
%178 = OpGroupNonUniformBroadcastFirst %5 %61 %177
%179 = OpImageTexelPointer %53 %19 %46 %34
%180 = OpAtomicIAdd %5 %179 %46 %34 %178
OpReturn
OpFunctionEnd
#endif
