#version 460
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std140) uniform BindlessCBV
{
    vec4 _m0[4096];
} _13[];

layout(set = 0, binding = 0, std140) uniform _29_31
{
    vec4 _m0[1024];
} _31;

layout(set = 0, binding = 1, std140) uniform _33_36
{
    vec4 _m0[1024];
} _36[2];

layout(set = 0, binding = 0) uniform usamplerBuffer _16;
layout(set = 0, binding = 1) uniform usamplerBuffer _20[2];
layout(set = 0, binding = 3) uniform samplerBuffer _23;
layout(set = 0, binding = 0, r32ui) uniform uimageBuffer _26;

void main()
{
    uint _63 = imageAtomicAdd(_26, int(1u), subgroupBroadcastFirst(floatBitsToUint(_13[0u]._m0[0u]).x));
    uint _70 = imageAtomicAdd(_26, int(0u), floatBitsToUint(_31._m0[1u]).x);
    uint _78 = imageAtomicAdd(_26, int(1u), subgroupBroadcastFirst(floatBitsToUint(_31._m0[gl_GlobalInvocationID.x]).x));
    uint _86 = imageAtomicAdd(_26, int(1u), subgroupBroadcastFirst(floatBitsToUint(_36[0u]._m0[1u]).x));
    uint _94 = imageAtomicAdd(_26, int(1u), subgroupBroadcastFirst(floatBitsToUint(_36[0u]._m0[gl_GlobalInvocationID.x]).x));
    uint _101 = imageAtomicAdd(_26, int(0u), subgroupBroadcastFirst(texelFetch(_16, int(1u)).x));
    uint _108 = imageAtomicAdd(_26, int(1u), subgroupBroadcastFirst(texelFetch(_16, int(gl_GlobalInvocationID.x)).x));
    uint _116 = imageAtomicAdd(_26, int(1u), subgroupBroadcastFirst(texelFetch(_20[0u], int(1u)).x));
    uint _123 = imageAtomicAdd(_26, int(1u), subgroupBroadcastFirst(imageLoad(_26, int(2u)).x));
    uint _131 = imageAtomicAdd(_26, int(1u), uint(subgroupBroadcastFirst(texelFetch(_23, int(0u)).x)));
    uint _134 = imageAtomicAdd(_26, int(0u), gl_WorkGroupID.x);
    uint _138 = imageAtomicAdd(_26, int(1u), subgroupBroadcastFirst(gl_GlobalInvocationID.x));
    uint _146 = imageAtomicAdd(_26, int(0u), subgroupBroadcastFirst(floatBitsToUint(_31._m0[1u]).x));
    uint _155 = imageAtomicAdd(_26, int(0u), subgroupBroadcastFirst(subgroupAdd(floatBitsToUint(_31._m0[gl_GlobalInvocationID.x]).x)));
    uint _164 = imageAtomicAdd(_26, int(0u), subgroupBroadcastFirst(subgroupOr(floatBitsToUint(_31._m0[gl_GlobalInvocationID.x]).x)));
    uint _175 = imageAtomicAdd(_26, int(0u), uint(subgroupBroadcastFirst(subgroupAllEqual(floatBitsToUint(_31._m0[gl_GlobalInvocationID.x]).x))));
    uint _186 = imageAtomicAdd(_26, int(0u), subgroupBroadcastFirst(subgroupBallot(floatBitsToUint(_31._m0[gl_GlobalInvocationID.x]).x != 0u).x));
    uint _197 = imageAtomicAdd(_26, int(0u), uint(subgroupBroadcastFirst(subgroupAny(floatBitsToUint(_31._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _208 = imageAtomicAdd(_26, int(0u), uint(subgroupBroadcastFirst(subgroupAll(floatBitsToUint(_31._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _217 = imageAtomicAdd(_26, int(1u), subgroupBroadcastFirst(subgroupExclusiveAdd(floatBitsToUint(_31._m0[gl_GlobalInvocationID.x]).x)));
}


#if 0
// SPIR-V disassembly
// HeuristicWaveSize(32)
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 220
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability SampledBuffer
OpCapability ImageBuffer
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpCapability RuntimeDescriptorArray
OpCapability UniformTexelBufferArrayDynamicIndexing
OpExtension "SPV_EXT_descriptor_indexing"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %42 %46
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %10 "BindlessCBV"
OpName %29 ""
OpName %33 ""
OpDecorate %9 ArrayStride 16
OpDecorate %10 Block
OpMemberDecorate %10 0 Offset 0
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 0
OpDecorate %16 DescriptorSet 0
OpDecorate %16 Binding 0
OpDecorate %20 DescriptorSet 0
OpDecorate %20 Binding 1
OpDecorate %23 DescriptorSet 0
OpDecorate %23 Binding 3
OpDecorate %26 DescriptorSet 0
OpDecorate %26 Binding 0
OpDecorate %28 ArrayStride 16
OpMemberDecorate %29 0 Offset 0
OpDecorate %29 Block
OpDecorate %31 DescriptorSet 0
OpDecorate %31 Binding 0
OpDecorate %32 ArrayStride 16
OpMemberDecorate %33 0 Offset 0
OpDecorate %33 Block
OpDecorate %36 DescriptorSet 0
OpDecorate %36 Binding 1
OpDecorate %42 BuiltIn GlobalInvocationId
OpDecorate %46 BuiltIn WorkgroupId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeFloat 32
%6 = OpTypeVector %5 4
%7 = OpTypeInt 32 0
%8 = OpConstant %7 4096
%9 = OpTypeArray %6 %8
%10 = OpTypeStruct %9
%11 = OpTypeRuntimeArray %10
%12 = OpTypePointer Uniform %11
%13 = OpVariable %12 Uniform
%14 = OpTypeImage %7 Buffer 0 0 0 1 Unknown
%15 = OpTypePointer UniformConstant %14
%16 = OpVariable %15 UniformConstant
%17 = OpConstant %7 2
%18 = OpTypeArray %14 %17
%19 = OpTypePointer UniformConstant %18
%20 = OpVariable %19 UniformConstant
%21 = OpTypeImage %5 Buffer 0 0 0 1 Unknown
%22 = OpTypePointer UniformConstant %21
%23 = OpVariable %22 UniformConstant
%24 = OpTypeImage %7 Buffer 0 0 0 2 R32ui
%25 = OpTypePointer UniformConstant %24
%26 = OpVariable %25 UniformConstant
%27 = OpConstant %7 1024
%28 = OpTypeArray %6 %27
%29 = OpTypeStruct %28
%30 = OpTypePointer Uniform %29
%31 = OpVariable %30 Uniform
%32 = OpTypeArray %6 %27
%33 = OpTypeStruct %32
%34 = OpTypeArray %33 %17
%35 = OpTypePointer Uniform %34
%36 = OpVariable %35 Uniform
%37 = OpConstant %7 0
%38 = OpTypePointer Uniform %33
%40 = OpTypeVector %7 3
%41 = OpTypePointer Input %40
%42 = OpVariable %41 Input
%43 = OpTypePointer Input %7
%46 = OpVariable %41 Input
%49 = OpTypePointer Uniform %10
%51 = OpTypePointer Uniform %6
%54 = OpTypeVector %7 4
%58 = OpConstant %7 3
%60 = OpConstant %7 1
%61 = OpTypePointer Image %7
%169 = OpTypeBool
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %218
%218 = OpLabel
%39 = OpAccessChain %38 %36 %37
%44 = OpAccessChain %43 %42 %37
%45 = OpLoad %7 %44
%47 = OpAccessChain %43 %46 %37
%48 = OpLoad %7 %47
%50 = OpAccessChain %49 %13 %37
%52 = OpAccessChain %51 %50 %37 %37
%53 = OpLoad %6 %52
%55 = OpBitcast %54 %53
%56 = OpCompositeExtract %7 %55 0
%57 = OpGroupNonUniformBroadcastFirst %7 %58 %56
%59 = OpLoad %24 %26
%62 = OpImageTexelPointer %61 %26 %60 %37
%63 = OpAtomicIAdd %7 %62 %60 %37 %57
%64 = OpAccessChain %51 %31 %37 %60
%65 = OpLoad %6 %64
%66 = OpBitcast %54 %65
%67 = OpCompositeExtract %7 %66 0
%68 = OpLoad %24 %26
%69 = OpImageTexelPointer %61 %26 %37 %37
%70 = OpAtomicIAdd %7 %69 %60 %37 %67
%71 = OpAccessChain %51 %31 %37 %45
%72 = OpLoad %6 %71
%73 = OpBitcast %54 %72
%74 = OpCompositeExtract %7 %73 0
%75 = OpGroupNonUniformBroadcastFirst %7 %58 %74
%76 = OpLoad %24 %26
%77 = OpImageTexelPointer %61 %26 %60 %37
%78 = OpAtomicIAdd %7 %77 %60 %37 %75
%79 = OpAccessChain %51 %39 %37 %60
%80 = OpLoad %6 %79
%81 = OpBitcast %54 %80
%82 = OpCompositeExtract %7 %81 0
%83 = OpGroupNonUniformBroadcastFirst %7 %58 %82
%84 = OpLoad %24 %26
%85 = OpImageTexelPointer %61 %26 %60 %37
%86 = OpAtomicIAdd %7 %85 %60 %37 %83
%87 = OpAccessChain %51 %39 %37 %45
%88 = OpLoad %6 %87
%89 = OpBitcast %54 %88
%90 = OpCompositeExtract %7 %89 0
%91 = OpGroupNonUniformBroadcastFirst %7 %58 %90
%92 = OpLoad %24 %26
%93 = OpImageTexelPointer %61 %26 %60 %37
%94 = OpAtomicIAdd %7 %93 %60 %37 %91
%95 = OpLoad %14 %16
%96 = OpImageFetch %54 %95 %60
%97 = OpCompositeExtract %7 %96 0
%98 = OpGroupNonUniformBroadcastFirst %7 %58 %97
%99 = OpLoad %24 %26
%100 = OpImageTexelPointer %61 %26 %37 %37
%101 = OpAtomicIAdd %7 %100 %60 %37 %98
%102 = OpLoad %14 %16
%103 = OpImageFetch %54 %102 %45
%104 = OpCompositeExtract %7 %103 0
%105 = OpGroupNonUniformBroadcastFirst %7 %58 %104
%106 = OpLoad %24 %26
%107 = OpImageTexelPointer %61 %26 %60 %37
%108 = OpAtomicIAdd %7 %107 %60 %37 %105
%109 = OpAccessChain %15 %20 %37
%110 = OpLoad %14 %109
%111 = OpImageFetch %54 %110 %60
%112 = OpCompositeExtract %7 %111 0
%113 = OpGroupNonUniformBroadcastFirst %7 %58 %112
%114 = OpLoad %24 %26
%115 = OpImageTexelPointer %61 %26 %60 %37
%116 = OpAtomicIAdd %7 %115 %60 %37 %113
%117 = OpLoad %24 %26
%118 = OpImageRead %54 %117 %17
%119 = OpCompositeExtract %7 %118 0
%120 = OpGroupNonUniformBroadcastFirst %7 %58 %119
%121 = OpLoad %24 %26
%122 = OpImageTexelPointer %61 %26 %60 %37
%123 = OpAtomicIAdd %7 %122 %60 %37 %120
%124 = OpLoad %21 %23
%125 = OpImageFetch %6 %124 %37
%126 = OpCompositeExtract %5 %125 0
%127 = OpGroupNonUniformBroadcastFirst %5 %58 %126
%128 = OpConvertFToU %7 %127
%129 = OpLoad %24 %26
%130 = OpImageTexelPointer %61 %26 %60 %37
%131 = OpAtomicIAdd %7 %130 %60 %37 %128
%132 = OpLoad %24 %26
%133 = OpImageTexelPointer %61 %26 %37 %37
%134 = OpAtomicIAdd %7 %133 %60 %37 %48
%135 = OpGroupNonUniformBroadcastFirst %7 %58 %45
%136 = OpLoad %24 %26
%137 = OpImageTexelPointer %61 %26 %60 %37
%138 = OpAtomicIAdd %7 %137 %60 %37 %135
%139 = OpAccessChain %51 %31 %37 %60
%140 = OpLoad %6 %139
%141 = OpBitcast %54 %140
%142 = OpCompositeExtract %7 %141 0
%143 = OpGroupNonUniformBroadcastFirst %7 %58 %142
%144 = OpLoad %24 %26
%145 = OpImageTexelPointer %61 %26 %37 %37
%146 = OpAtomicIAdd %7 %145 %60 %37 %143
%147 = OpAccessChain %51 %31 %37 %45
%148 = OpLoad %6 %147
%149 = OpBitcast %54 %148
%150 = OpCompositeExtract %7 %149 0
%151 = OpGroupNonUniformIAdd %7 %58 Reduce %150
%152 = OpGroupNonUniformBroadcastFirst %7 %58 %151
%153 = OpLoad %24 %26
%154 = OpImageTexelPointer %61 %26 %37 %37
%155 = OpAtomicIAdd %7 %154 %60 %37 %152
%156 = OpAccessChain %51 %31 %37 %45
%157 = OpLoad %6 %156
%158 = OpBitcast %54 %157
%159 = OpCompositeExtract %7 %158 0
%160 = OpGroupNonUniformBitwiseOr %7 %58 Reduce %159
%161 = OpGroupNonUniformBroadcastFirst %7 %58 %160
%162 = OpLoad %24 %26
%163 = OpImageTexelPointer %61 %26 %37 %37
%164 = OpAtomicIAdd %7 %163 %60 %37 %161
%165 = OpAccessChain %51 %31 %37 %45
%166 = OpLoad %6 %165
%167 = OpBitcast %54 %166
%168 = OpCompositeExtract %7 %167 0
%170 = OpGroupNonUniformAllEqual %169 %58 %168
%171 = OpGroupNonUniformBroadcastFirst %169 %58 %170
%172 = OpSelect %7 %171 %60 %37
%173 = OpLoad %24 %26
%174 = OpImageTexelPointer %61 %26 %37 %37
%175 = OpAtomicIAdd %7 %174 %60 %37 %172
%176 = OpAccessChain %51 %31 %37 %45
%177 = OpLoad %6 %176
%178 = OpBitcast %54 %177
%179 = OpCompositeExtract %7 %178 0
%180 = OpINotEqual %169 %179 %37
%181 = OpGroupNonUniformBallot %54 %58 %180
%182 = OpCompositeExtract %7 %181 0
%183 = OpGroupNonUniformBroadcastFirst %7 %58 %182
%184 = OpLoad %24 %26
%185 = OpImageTexelPointer %61 %26 %37 %37
%186 = OpAtomicIAdd %7 %185 %60 %37 %183
%187 = OpAccessChain %51 %31 %37 %45
%188 = OpLoad %6 %187
%189 = OpBitcast %54 %188
%190 = OpCompositeExtract %7 %189 0
%191 = OpINotEqual %169 %190 %37
%192 = OpGroupNonUniformAny %169 %58 %191
%193 = OpGroupNonUniformBroadcastFirst %169 %58 %192
%194 = OpSelect %7 %193 %60 %37
%195 = OpLoad %24 %26
%196 = OpImageTexelPointer %61 %26 %37 %37
%197 = OpAtomicIAdd %7 %196 %60 %37 %194
%198 = OpAccessChain %51 %31 %37 %45
%199 = OpLoad %6 %198
%200 = OpBitcast %54 %199
%201 = OpCompositeExtract %7 %200 0
%202 = OpINotEqual %169 %201 %37
%203 = OpGroupNonUniformAll %169 %58 %202
%204 = OpGroupNonUniformBroadcastFirst %169 %58 %203
%205 = OpSelect %7 %204 %60 %37
%206 = OpLoad %24 %26
%207 = OpImageTexelPointer %61 %26 %37 %37
%208 = OpAtomicIAdd %7 %207 %60 %37 %205
%209 = OpAccessChain %51 %31 %37 %45
%210 = OpLoad %6 %209
%211 = OpBitcast %54 %210
%212 = OpCompositeExtract %7 %211 0
%213 = OpGroupNonUniformIAdd %7 %58 ExclusiveScan %212
%214 = OpGroupNonUniformBroadcastFirst %7 %58 %213
%215 = OpLoad %24 %26
%216 = OpImageTexelPointer %61 %26 %60 %37
%217 = OpAtomicIAdd %7 %216 %60 %37 %214
OpReturn
OpFunctionEnd
#endif
