#version 460
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) restrict readonly buffer SSBO
{
    uint _m0[];
} _9;

layout(set = 0, binding = 1, std430) restrict readonly buffer _11_15
{
    uint _m0[];
} _15[2];

layout(set = 0, binding = 0, std430) buffer _21_23
{
    uint _m0[];
} _23;

layout(set = 0, binding = 0, std140) uniform _27_29
{
    vec4 _m0[1024];
} _29;

layout(set = 0, binding = 1, std140) uniform _31_34
{
    vec4 _m0[1024];
} _34[2];

layout(set = 0, binding = 3) uniform samplerBuffer _19;

void main()
{
    uint _56 = atomicAdd(_23._m0[0u], floatBitsToUint(_29._m0[1u]).x);
    uint _64 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x));
    uint _71 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_34[0u]._m0[1u]).x));
    uint _78 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(floatBitsToUint(_34[0u]._m0[gl_GlobalInvocationID.x]).x));
    uint _82 = atomicAdd(_23._m0[0u], _9._m0[1u]);
    uint _87 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(_9._m0[gl_GlobalInvocationID.x]));
    uint _94 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(_15[0u]._m0[1u]));
    uint _99 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(_23._m0[2u]));
    uint _106 = atomicAdd(_23._m0[1u], uint(subgroupBroadcastFirst(texelFetch(_19, int(0u)).x)));
    uint _108 = atomicAdd(_23._m0[0u], gl_WorkGroupID.x);
    uint _111 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(gl_GlobalInvocationID.x));
    uint _117 = atomicAdd(_23._m0[0u], floatBitsToUint(_29._m0[1u]).x);
    uint _125 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(subgroupAdd(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x)));
    uint _133 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(subgroupOr(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x)));
    uint _143 = atomicAdd(_23._m0[0u], uint(subgroupBroadcastFirst(subgroupAllEqual(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x))));
    uint _153 = atomicAdd(_23._m0[0u], subgroupBroadcastFirst(subgroupBallot(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x != 0u).x));
    uint _163 = atomicAdd(_23._m0[0u], uint(subgroupBroadcastFirst(subgroupAny(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _173 = atomicAdd(_23._m0[0u], uint(subgroupBroadcastFirst(subgroupAll(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x != 0u))));
    uint _181 = atomicAdd(_23._m0[1u], subgroupBroadcastFirst(subgroupExclusiveAdd(floatBitsToUint(_29._m0[gl_GlobalInvocationID.x]).x)));
}


#if 0
// SPIR-V disassembly
// HeuristicWaveSize(32)
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 184
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability StorageBufferArrayDynamicIndexing
OpCapability SampledBuffer
OpCapability GroupNonUniformVote
OpCapability GroupNonUniformArithmetic
OpCapability GroupNonUniformBallot
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %40 %44
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %21 "SSBO"
OpName %27 ""
OpName %31 ""
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %15 DescriptorSet 0
OpDecorate %15 Binding 1
OpDecorate %15 NonWritable
OpDecorate %15 Restrict
OpDecorate %19 DescriptorSet 0
OpDecorate %19 Binding 3
OpDecorate %20 ArrayStride 4
OpMemberDecorate %21 0 Offset 0
OpDecorate %21 Block
OpDecorate %23 DescriptorSet 0
OpDecorate %23 Binding 0
OpDecorate %26 ArrayStride 16
OpMemberDecorate %27 0 Offset 0
OpDecorate %27 Block
OpDecorate %29 DescriptorSet 0
OpDecorate %29 Binding 0
OpDecorate %30 ArrayStride 16
OpMemberDecorate %31 0 Offset 0
OpDecorate %31 Block
OpDecorate %34 DescriptorSet 0
OpDecorate %34 Binding 1
OpDecorate %40 BuiltIn GlobalInvocationId
OpDecorate %44 BuiltIn WorkgroupId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpConstant %5 2
%13 = OpTypeArray %11 %12
%14 = OpTypePointer StorageBuffer %13
%15 = OpVariable %14 StorageBuffer
%16 = OpTypeFloat 32
%17 = OpTypeImage %16 Buffer 0 0 0 1 Unknown
%18 = OpTypePointer UniformConstant %17
%19 = OpVariable %18 UniformConstant
%20 = OpTypeRuntimeArray %5
%21 = OpTypeStruct %20
%22 = OpTypePointer StorageBuffer %21
%23 = OpVariable %22 StorageBuffer
%24 = OpConstant %5 1024
%25 = OpTypeVector %16 4
%26 = OpTypeArray %25 %24
%27 = OpTypeStruct %26
%28 = OpTypePointer Uniform %27
%29 = OpVariable %28 Uniform
%30 = OpTypeArray %25 %24
%31 = OpTypeStruct %30
%32 = OpTypeArray %31 %12
%33 = OpTypePointer Uniform %32
%34 = OpVariable %33 Uniform
%35 = OpConstant %5 0
%36 = OpTypePointer Uniform %31
%38 = OpTypeVector %5 3
%39 = OpTypePointer Input %38
%40 = OpVariable %39 Input
%41 = OpTypePointer Input %5
%44 = OpVariable %39 Input
%47 = OpConstant %5 1
%48 = OpTypePointer Uniform %25
%51 = OpTypeVector %5 4
%54 = OpTypePointer StorageBuffer %5
%62 = OpConstant %5 3
%88 = OpTypePointer StorageBuffer %11
%138 = OpTypeBool
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %182
%182 = OpLabel
%37 = OpAccessChain %36 %34 %35
%42 = OpAccessChain %41 %40 %35
%43 = OpLoad %5 %42
%45 = OpAccessChain %41 %44 %35
%46 = OpLoad %5 %45
%49 = OpAccessChain %48 %29 %35 %47
%50 = OpLoad %25 %49
%52 = OpBitcast %51 %50
%53 = OpCompositeExtract %5 %52 0
%55 = OpAccessChain %54 %23 %35 %35
%56 = OpAtomicIAdd %5 %55 %47 %35 %53
%57 = OpAccessChain %48 %29 %35 %43
%58 = OpLoad %25 %57
%59 = OpBitcast %51 %58
%60 = OpCompositeExtract %5 %59 0
%61 = OpGroupNonUniformBroadcastFirst %5 %62 %60
%63 = OpAccessChain %54 %23 %35 %47
%64 = OpAtomicIAdd %5 %63 %47 %35 %61
%65 = OpAccessChain %48 %37 %35 %47
%66 = OpLoad %25 %65
%67 = OpBitcast %51 %66
%68 = OpCompositeExtract %5 %67 0
%69 = OpGroupNonUniformBroadcastFirst %5 %62 %68
%70 = OpAccessChain %54 %23 %35 %47
%71 = OpAtomicIAdd %5 %70 %47 %35 %69
%72 = OpAccessChain %48 %37 %35 %43
%73 = OpLoad %25 %72
%74 = OpBitcast %51 %73
%75 = OpCompositeExtract %5 %74 0
%76 = OpGroupNonUniformBroadcastFirst %5 %62 %75
%77 = OpAccessChain %54 %23 %35 %47
%78 = OpAtomicIAdd %5 %77 %47 %35 %76
%79 = OpAccessChain %54 %9 %35 %47
%80 = OpLoad %5 %79
%81 = OpAccessChain %54 %23 %35 %35
%82 = OpAtomicIAdd %5 %81 %47 %35 %80
%83 = OpAccessChain %54 %9 %35 %43
%84 = OpLoad %5 %83
%85 = OpGroupNonUniformBroadcastFirst %5 %62 %84
%86 = OpAccessChain %54 %23 %35 %47
%87 = OpAtomicIAdd %5 %86 %47 %35 %85
%89 = OpAccessChain %88 %15 %35
%90 = OpAccessChain %54 %89 %35 %47
%91 = OpLoad %5 %90
%92 = OpGroupNonUniformBroadcastFirst %5 %62 %91
%93 = OpAccessChain %54 %23 %35 %47
%94 = OpAtomicIAdd %5 %93 %47 %35 %92
%95 = OpAccessChain %54 %23 %35 %12
%96 = OpLoad %5 %95
%97 = OpGroupNonUniformBroadcastFirst %5 %62 %96
%98 = OpAccessChain %54 %23 %35 %47
%99 = OpAtomicIAdd %5 %98 %47 %35 %97
%100 = OpLoad %17 %19
%101 = OpImageFetch %25 %100 %35
%102 = OpCompositeExtract %16 %101 0
%103 = OpGroupNonUniformBroadcastFirst %16 %62 %102
%104 = OpConvertFToU %5 %103
%105 = OpAccessChain %54 %23 %35 %47
%106 = OpAtomicIAdd %5 %105 %47 %35 %104
%107 = OpAccessChain %54 %23 %35 %35
%108 = OpAtomicIAdd %5 %107 %47 %35 %46
%109 = OpGroupNonUniformBroadcastFirst %5 %62 %43
%110 = OpAccessChain %54 %23 %35 %47
%111 = OpAtomicIAdd %5 %110 %47 %35 %109
%112 = OpAccessChain %48 %29 %35 %47
%113 = OpLoad %25 %112
%114 = OpBitcast %51 %113
%115 = OpCompositeExtract %5 %114 0
%116 = OpAccessChain %54 %23 %35 %35
%117 = OpAtomicIAdd %5 %116 %47 %35 %115
%118 = OpAccessChain %48 %29 %35 %43
%119 = OpLoad %25 %118
%120 = OpBitcast %51 %119
%121 = OpCompositeExtract %5 %120 0
%122 = OpGroupNonUniformIAdd %5 %62 Reduce %121
%123 = OpGroupNonUniformBroadcastFirst %5 %62 %122
%124 = OpAccessChain %54 %23 %35 %35
%125 = OpAtomicIAdd %5 %124 %47 %35 %123
%126 = OpAccessChain %48 %29 %35 %43
%127 = OpLoad %25 %126
%128 = OpBitcast %51 %127
%129 = OpCompositeExtract %5 %128 0
%130 = OpGroupNonUniformBitwiseOr %5 %62 Reduce %129
%131 = OpGroupNonUniformBroadcastFirst %5 %62 %130
%132 = OpAccessChain %54 %23 %35 %35
%133 = OpAtomicIAdd %5 %132 %47 %35 %131
%134 = OpAccessChain %48 %29 %35 %43
%135 = OpLoad %25 %134
%136 = OpBitcast %51 %135
%137 = OpCompositeExtract %5 %136 0
%139 = OpGroupNonUniformAllEqual %138 %62 %137
%140 = OpGroupNonUniformBroadcastFirst %138 %62 %139
%141 = OpSelect %5 %140 %47 %35
%142 = OpAccessChain %54 %23 %35 %35
%143 = OpAtomicIAdd %5 %142 %47 %35 %141
%144 = OpAccessChain %48 %29 %35 %43
%145 = OpLoad %25 %144
%146 = OpBitcast %51 %145
%147 = OpCompositeExtract %5 %146 0
%148 = OpINotEqual %138 %147 %35
%149 = OpGroupNonUniformBallot %51 %62 %148
%150 = OpCompositeExtract %5 %149 0
%151 = OpGroupNonUniformBroadcastFirst %5 %62 %150
%152 = OpAccessChain %54 %23 %35 %35
%153 = OpAtomicIAdd %5 %152 %47 %35 %151
%154 = OpAccessChain %48 %29 %35 %43
%155 = OpLoad %25 %154
%156 = OpBitcast %51 %155
%157 = OpCompositeExtract %5 %156 0
%158 = OpINotEqual %138 %157 %35
%159 = OpGroupNonUniformAny %138 %62 %158
%160 = OpGroupNonUniformBroadcastFirst %138 %62 %159
%161 = OpSelect %5 %160 %47 %35
%162 = OpAccessChain %54 %23 %35 %35
%163 = OpAtomicIAdd %5 %162 %47 %35 %161
%164 = OpAccessChain %48 %29 %35 %43
%165 = OpLoad %25 %164
%166 = OpBitcast %51 %165
%167 = OpCompositeExtract %5 %166 0
%168 = OpINotEqual %138 %167 %35
%169 = OpGroupNonUniformAll %138 %62 %168
%170 = OpGroupNonUniformBroadcastFirst %138 %62 %169
%171 = OpSelect %5 %170 %47 %35
%172 = OpAccessChain %54 %23 %35 %35
%173 = OpAtomicIAdd %5 %172 %47 %35 %171
%174 = OpAccessChain %48 %29 %35 %43
%175 = OpLoad %25 %174
%176 = OpBitcast %51 %175
%177 = OpCompositeExtract %5 %176 0
%178 = OpGroupNonUniformIAdd %5 %62 ExclusiveScan %177
%179 = OpGroupNonUniformBroadcastFirst %5 %62 %178
%180 = OpAccessChain %54 %23 %35 %47
%181 = OpAtomicIAdd %5 %180 %47 %35 %179
OpReturn
OpFunctionEnd
#endif
