#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference_uvec2 : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(buffer_reference) buffer uintPointer;

layout(buffer_reference, buffer_reference_align = 4) buffer uintPointer
{
    uint value;
};

layout(set = 7, binding = 0, std430) readonly buffer AtomicCounters
{
    uvec2 counters[];
} _30;

layout(set = 0, binding = 0, std430) buffer SSBO
{
    uvec4 _m0[];
} _36[];

layout(set = 0, binding = 0, std140) uniform BindlessCBV
{
    vec4 _m0[4096];
} _43[];

layout(set = 10, binding = 20, std140) uniform DescriptorHeapSizeUBO
{
    uint count;
} DescriptorHeapSize;

layout(set = 4, binding = 0, std430) writeonly buffer _54_57
{
    uvec4 _m0[];
} _57[];

layout(set = 5, binding = 0, std140) uniform _59_62
{
    vec4 _m0[4096];
} _62[];

layout(push_constant, std430) uniform RootConstants
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
    uint _m5;
    uint _m6;
    uint _m7;
} registers;

layout(set = 0, binding = 0) uniform texture2D _13[];
layout(set = 0, binding = 0) uniform sampler _17[];
layout(set = 0, binding = 0) uniform writeonly image2D _21[];
layout(set = 0, binding = 0) uniform writeonly imageBuffer _25[];
layout(set = 3, binding = 0) uniform writeonly image2D _49[];
layout(set = 4, binding = 0) uniform writeonly imageBuffer _52[];
layout(set = 2, binding = 0) uniform sampler _65[];

uint RobustPhysicalAtomicCounter(uvec2 _236, uint _237, uint _238)
{
    uint _253;
    if (any(notEqual(_236, uvec2(0u))))
    {
        uint _250 = atomicAdd(uintPointer(_236).value, _237);
        _253 = _250 + _238;
    }
    else
    {
        _253 = 0u;
    }
    return _253;
}

void main()
{
    uint _73 = gl_GlobalInvocationID.x + 0u;
    uint _86 = gl_GlobalInvocationID.x + 0u;
    vec4 _100 = textureLod(nonuniformEXT(sampler2D(_13[min((registers._m0 + _73), DescriptorHeapSize.count)], _65[min((registers._m2 + _86), 2047u)])), vec2(0.5), 0.0);
    _57[registers._m4 + 100u]._m0[gl_GlobalInvocationID.x] = uvec4(floatBitsToUint(_100.x), floatBitsToUint(_100.y), floatBitsToUint(_100.z), floatBitsToUint(_100.w));
    barrier();
    imageStore(_49[nonuniformEXT(min((registers._m3 + (gl_GlobalInvocationID.x + 0u)), DescriptorHeapSize.count))], ivec2(uvec2(gl_GlobalInvocationID.x, 0u)), vec4(textureLod(nonuniformEXT(sampler2D(_13[min((registers._m0 + _73), DescriptorHeapSize.count)], _65[min((registers._m2 + _86), 2047u)])), vec2(0.5), 0.0)));
    barrier();
    imageStore(_52[nonuniformEXT(min((registers._m4 + (gl_GlobalInvocationID.x + 0u)), DescriptorHeapSize.count))], int(gl_GlobalInvocationID.x), vec4(_62[nonuniformEXT(min((registers._m5 + (gl_GlobalInvocationID.x + 0u)), DescriptorHeapSize.count))]._m0[0u]));
    barrier();
    vec4 _199 = textureLod(nonuniformEXT(sampler2D(_13[min((registers._m0 + _73), DescriptorHeapSize.count)], _65[min((registers._m2 + _86), 2047u)])), vec2(0.5), 0.0);
    uint _205 = gl_GlobalInvocationID.x + 0u;
    _57[nonuniformEXT(min((registers._m4 + _205), DescriptorHeapSize.count))]._m0[gl_GlobalInvocationID.x] = uvec4(floatBitsToUint(_199.x), floatBitsToUint(_199.y), floatBitsToUint(_199.z), floatBitsToUint(_199.w));
    barrier();
    uvec2 _234 = _30.counters[min((registers._m4 + _205), DescriptorHeapSize.count)];
    uint _255 = RobustPhysicalAtomicCounter(_234, 1u, 0u);
    barrier();
    uint _279 = gl_GlobalInvocationID.x + 400u;
    uvec2 _290 = _30.counters[min(_279, DescriptorHeapSize.count)];
    vec4 _299 = textureLod(nonuniformEXT(sampler2D(_13[min(gl_GlobalInvocationID.x, DescriptorHeapSize.count)], _17[min((gl_GlobalInvocationID.x + 100u), 2047u)])), vec2(0.5), 0.0);
    _57[registers._m4 + 100u]._m0[gl_GlobalInvocationID.x] = uvec4(floatBitsToUint(_299.x), floatBitsToUint(_299.y), floatBitsToUint(_299.z), floatBitsToUint(_299.w));
    barrier();
    imageStore(_21[nonuniformEXT(min((gl_GlobalInvocationID.x + 200u), DescriptorHeapSize.count))], ivec2(uvec2(gl_GlobalInvocationID.x, 0u)), vec4(textureLod(nonuniformEXT(sampler2D(_13[min(gl_GlobalInvocationID.x, DescriptorHeapSize.count)], _17[min((gl_GlobalInvocationID.x + 100u), 2047u)])), vec2(0.5), 0.0)));
    barrier();
    imageStore(_25[nonuniformEXT(min((gl_GlobalInvocationID.x + 300u), DescriptorHeapSize.count))], int(gl_GlobalInvocationID.x), vec4(_43[nonuniformEXT(min((gl_GlobalInvocationID.x + 500u), DescriptorHeapSize.count))]._m0[0u]));
    barrier();
    vec4 _330 = textureLod(nonuniformEXT(sampler2D(_13[min(gl_GlobalInvocationID.x, DescriptorHeapSize.count)], _17[min((gl_GlobalInvocationID.x + 100u), 2047u)])), vec2(0.5), 0.0);
    _36[nonuniformEXT(min(_279, DescriptorHeapSize.count))]._m0[gl_GlobalInvocationID.x] = uvec4(floatBitsToUint(_330.x), floatBitsToUint(_330.y), floatBitsToUint(_330.z), floatBitsToUint(_330.w));
    barrier();
    uint _342 = RobustPhysicalAtomicCounter(_290, 1u, 0u);
    barrier();
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 345
; Schema: 0
OpCapability Shader
OpCapability UniformBufferArrayDynamicIndexing
OpCapability SampledImageArrayDynamicIndexing
OpCapability StorageBufferArrayDynamicIndexing
OpCapability StorageImageArrayDynamicIndexing
OpCapability ImageBuffer
OpCapability StorageImageWriteWithoutFormat
OpCapability RuntimeDescriptorArray
OpCapability StorageTexelBufferArrayDynamicIndexing
OpCapability UniformBufferArrayNonUniformIndexing
OpCapability SampledImageArrayNonUniformIndexing
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability StorageImageArrayNonUniformIndexing
OpCapability StorageTexelBufferArrayNonUniformIndexing
OpCapability PhysicalStorageBufferAddresses
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_physical_storage_buffer"
%83 = OpExtInstImport "GLSL.std.450"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %68
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %28 "AtomicCounters"
OpMemberName %28 0 "counters"
OpName %33 "SSBO"
OpName %40 "BindlessCBV"
OpName %44 "DescriptorHeapSizeUBO"
OpMemberName %44 0 "count"
OpName %46 "DescriptorHeapSize"
OpName %54 "SSBO"
OpName %59 "BindlessCBV"
OpName %239 "RobustPhysicalAtomicCounter"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 0
OpDecorate %17 DescriptorSet 0
OpDecorate %17 Binding 0
OpDecorate %21 DescriptorSet 0
OpDecorate %21 Binding 0
OpDecorate %21 NonReadable
OpDecorate %25 DescriptorSet 0
OpDecorate %25 Binding 0
OpDecorate %25 NonReadable
OpDecorate %27 ArrayStride 8
OpDecorate %28 Block
OpMemberDecorate %28 0 Offset 0
OpMemberDecorate %28 0 NonWritable
OpDecorate %30 DescriptorSet 7
OpDecorate %30 Binding 0
OpDecorate %30 AliasedPointer
OpDecorate %32 ArrayStride 16
OpMemberDecorate %33 0 Offset 0
OpDecorate %33 Block
OpDecorate %36 DescriptorSet 0
OpDecorate %36 Binding 0
OpDecorate %39 ArrayStride 16
OpDecorate %40 Block
OpMemberDecorate %40 0 Offset 0
OpDecorate %43 DescriptorSet 0
OpDecorate %43 Binding 0
OpDecorate %44 Block
OpMemberDecorate %44 0 Offset 0
OpDecorate %46 DescriptorSet 10
OpDecorate %46 Binding 20
OpDecorate %49 DescriptorSet 3
OpDecorate %49 Binding 0
OpDecorate %49 NonReadable
OpDecorate %52 DescriptorSet 4
OpDecorate %52 Binding 0
OpDecorate %52 NonReadable
OpDecorate %53 ArrayStride 16
OpMemberDecorate %54 0 Offset 0
OpDecorate %54 Block
OpDecorate %57 DescriptorSet 4
OpDecorate %57 Binding 0
OpDecorate %57 NonReadable
OpDecorate %58 ArrayStride 16
OpDecorate %59 Block
OpMemberDecorate %59 0 Offset 0
OpDecorate %62 DescriptorSet 5
OpDecorate %62 Binding 0
OpDecorate %65 DescriptorSet 2
OpDecorate %65 Binding 0
OpDecorate %68 BuiltIn GlobalInvocationId
OpDecorate %84 NonUniform
OpDecorate %85 NonUniform
OpDecorate %94 NonUniform
OpDecorate %95 NonUniform
OpDecorate %97 NonUniform
OpDecorate %128 NonUniform
OpDecorate %129 NonUniform
OpDecorate %134 NonUniform
OpDecorate %135 NonUniform
OpDecorate %136 NonUniform
OpDecorate %152 NonUniform
OpDecorate %153 NonUniform
OpDecorate %165 NonUniform
OpDecorate %162 NonUniform
OpDecorate %167 NonUniform
OpDecorate %181 NonUniform
OpDecorate %182 NonUniform
OpDecorate %190 NonUniform
OpDecorate %191 NonUniform
OpDecorate %196 NonUniform
OpDecorate %197 NonUniform
OpDecorate %198 NonUniform
OpDecorate %212 NonUniform
OpDecorate %209 NonUniform
OpDecorate %218 NonUniform
OpDecorate %225 NonUniform
OpDecorate %222 NonUniform
OpDecorate %259 NonUniform
OpDecorate %260 NonUniform
OpDecorate %263 NonUniform
OpDecorate %264 NonUniform
OpDecorate %270 NonUniform
OpDecorate %271 NonUniform
OpDecorate %277 NonUniform
OpDecorate %278 NonUniform
OpDecorate %285 NonUniform
OpDecorate %282 NonUniform
OpDecorate %297 NonUniform
OpDecorate %294 NonUniform
OpDecorate %298 NonUniform
OpDecorate %323 NonUniform
OpDecorate %341 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeFloat 32
%10 = OpTypeImage %9 2D 0 0 0 1 Unknown
%11 = OpTypeRuntimeArray %10
%12 = OpTypePointer UniformConstant %11
%13 = OpVariable %12 UniformConstant
%14 = OpTypeSampler
%15 = OpTypeRuntimeArray %14
%16 = OpTypePointer UniformConstant %15
%17 = OpVariable %16 UniformConstant
%18 = OpTypeImage %9 2D 0 0 0 2 Unknown
%19 = OpTypeRuntimeArray %18
%20 = OpTypePointer UniformConstant %19
%21 = OpVariable %20 UniformConstant
%22 = OpTypeImage %9 Buffer 0 0 0 2 Unknown
%23 = OpTypeRuntimeArray %22
%24 = OpTypePointer UniformConstant %23
%25 = OpVariable %24 UniformConstant
%26 = OpTypeVector %5 2
%27 = OpTypeRuntimeArray %26
%28 = OpTypeStruct %27
%29 = OpTypePointer StorageBuffer %28
%30 = OpVariable %29 StorageBuffer
%31 = OpTypeVector %5 4
%32 = OpTypeRuntimeArray %31
%33 = OpTypeStruct %32
%34 = OpTypeRuntimeArray %33
%35 = OpTypePointer StorageBuffer %34
%36 = OpVariable %35 StorageBuffer
%37 = OpTypeVector %9 4
%38 = OpConstant %5 4096
%39 = OpTypeArray %37 %38
%40 = OpTypeStruct %39
%41 = OpTypeRuntimeArray %40
%42 = OpTypePointer Uniform %41
%43 = OpVariable %42 Uniform
%44 = OpTypeStruct %5
%45 = OpTypePointer Uniform %44
%46 = OpVariable %45 Uniform
%47 = OpTypeRuntimeArray %18
%48 = OpTypePointer UniformConstant %47
%49 = OpVariable %48 UniformConstant
%50 = OpTypeRuntimeArray %22
%51 = OpTypePointer UniformConstant %50
%52 = OpVariable %51 UniformConstant
%53 = OpTypeRuntimeArray %31
%54 = OpTypeStruct %53
%55 = OpTypeRuntimeArray %54
%56 = OpTypePointer StorageBuffer %55
%57 = OpVariable %56 StorageBuffer
%58 = OpTypeArray %37 %38
%59 = OpTypeStruct %58
%60 = OpTypeRuntimeArray %59
%61 = OpTypePointer Uniform %60
%62 = OpVariable %61 Uniform
%63 = OpTypeRuntimeArray %14
%64 = OpTypePointer UniformConstant %63
%65 = OpVariable %64 UniformConstant
%66 = OpTypeVector %5 3
%67 = OpTypePointer Input %66
%68 = OpVariable %67 Input
%69 = OpTypePointer Input %5
%71 = OpConstant %5 0
%74 = OpTypePointer PushConstant %5
%78 = OpTypePointer UniformConstant %10
%80 = OpTypePointer Uniform %5
%88 = OpConstant %5 2
%91 = OpTypePointer UniformConstant %14
%93 = OpConstant %5 2047
%96 = OpTypeSampledImage %10
%98 = OpConstant %9 0.5
%99 = OpConstant %9 0
%101 = OpTypeVector %9 2
%108 = OpConstant %5 4
%111 = OpConstant %5 100
%112 = OpTypePointer StorageBuffer %54
%119 = OpTypePointer StorageBuffer %31
%121 = OpConstant %5 264
%145 = OpConstant %5 3
%148 = OpTypePointer UniformConstant %18
%158 = OpConstant %5 5
%161 = OpTypePointer Uniform %59
%166 = OpTypePointer Uniform %37
%177 = OpTypePointer UniformConstant %22
%226 = OpTypePointer StorageBuffer %26
%235 = OpTypeFunction %5 %26 %5 %5
%243 = OpTypeBool
%244 = OpTypeVector %243 2
%245 = OpConstantNull %26
%248 = OpTypePointer PhysicalStorageBuffer %5
%251 = OpConstant %5 1
%266 = OpConstant %5 200
%273 = OpConstant %5 300
%280 = OpConstant %5 400
%281 = OpTypePointer StorageBuffer %33
%292 = OpConstant %5 500
%293 = OpTypePointer Uniform %40
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %343
%343 = OpLabel
%70 = OpAccessChain %69 %68 %71
%72 = OpLoad %5 %70
%73 = OpIAdd %5 %72 %71
%75 = OpAccessChain %74 %8 %71
%76 = OpLoad %5 %75
%77 = OpIAdd %5 %76 %73
%81 = OpAccessChain %80 %46 %71
%82 = OpLoad %5 %81
%84 = OpExtInst %5 %83 UMin %77 %82
%79 = OpAccessChain %78 %13 %84
%85 = OpLoad %10 %79
%86 = OpIAdd %5 %72 %71
%87 = OpAccessChain %74 %8 %88
%89 = OpLoad %5 %87
%90 = OpIAdd %5 %89 %86
%94 = OpExtInst %5 %83 UMin %90 %93
%92 = OpAccessChain %91 %65 %94
%95 = OpLoad %14 %92
%97 = OpSampledImage %96 %85 %95
%102 = OpCompositeConstruct %101 %98 %98
%100 = OpImageSampleExplicitLod %37 %97 %102 Lod %99
%103 = OpCompositeExtract %9 %100 0
%104 = OpCompositeExtract %9 %100 1
%105 = OpCompositeExtract %9 %100 2
%106 = OpCompositeExtract %9 %100 3
%107 = OpAccessChain %74 %8 %108
%109 = OpLoad %5 %107
%110 = OpIAdd %5 %109 %111
%113 = OpAccessChain %112 %57 %110
%114 = OpBitcast %5 %103
%115 = OpBitcast %5 %104
%116 = OpBitcast %5 %105
%117 = OpBitcast %5 %106
%118 = OpCompositeConstruct %31 %114 %115 %116 %117
%120 = OpAccessChain %119 %113 %71 %72
OpStore %120 %118
OpControlBarrier %88 %88 %121
%122 = OpAccessChain %74 %8 %71
%123 = OpLoad %5 %122
%124 = OpIAdd %5 %123 %73
%126 = OpAccessChain %80 %46 %71
%127 = OpLoad %5 %126
%128 = OpExtInst %5 %83 UMin %124 %127
%125 = OpAccessChain %78 %13 %128
%129 = OpLoad %10 %125
%130 = OpAccessChain %74 %8 %88
%131 = OpLoad %5 %130
%132 = OpIAdd %5 %131 %86
%134 = OpExtInst %5 %83 UMin %132 %93
%133 = OpAccessChain %91 %65 %134
%135 = OpLoad %14 %133
%136 = OpSampledImage %96 %129 %135
%138 = OpCompositeConstruct %101 %98 %98
%137 = OpImageSampleExplicitLod %37 %136 %138 Lod %99
%139 = OpCompositeExtract %9 %137 0
%140 = OpCompositeExtract %9 %137 1
%141 = OpCompositeExtract %9 %137 2
%142 = OpCompositeExtract %9 %137 3
%143 = OpIAdd %5 %72 %71
%144 = OpAccessChain %74 %8 %145
%146 = OpLoad %5 %144
%147 = OpIAdd %5 %146 %143
%150 = OpAccessChain %80 %46 %71
%151 = OpLoad %5 %150
%152 = OpExtInst %5 %83 UMin %147 %151
%149 = OpAccessChain %148 %49 %152
%153 = OpLoad %18 %149
%154 = OpCompositeConstruct %26 %72 %71
%155 = OpCompositeConstruct %37 %139 %140 %141 %142
OpImageWrite %153 %154 %155
OpControlBarrier %88 %88 %121
%156 = OpIAdd %5 %72 %71
%157 = OpAccessChain %74 %8 %158
%159 = OpLoad %5 %157
%160 = OpIAdd %5 %159 %156
%163 = OpAccessChain %80 %46 %71
%164 = OpLoad %5 %163
%165 = OpExtInst %5 %83 UMin %160 %164
%162 = OpAccessChain %161 %62 %165
%167 = OpAccessChain %166 %162 %71 %71
%168 = OpLoad %37 %167
%169 = OpCompositeExtract %9 %168 0
%170 = OpCompositeExtract %9 %168 1
%171 = OpCompositeExtract %9 %168 2
%172 = OpCompositeExtract %9 %168 3
%173 = OpIAdd %5 %72 %71
%174 = OpAccessChain %74 %8 %108
%175 = OpLoad %5 %174
%176 = OpIAdd %5 %175 %173
%179 = OpAccessChain %80 %46 %71
%180 = OpLoad %5 %179
%181 = OpExtInst %5 %83 UMin %176 %180
%178 = OpAccessChain %177 %52 %181
%182 = OpLoad %22 %178
%183 = OpCompositeConstruct %37 %169 %170 %171 %172
OpImageWrite %182 %72 %183
OpControlBarrier %88 %88 %121
%184 = OpAccessChain %74 %8 %71
%185 = OpLoad %5 %184
%186 = OpIAdd %5 %185 %73
%188 = OpAccessChain %80 %46 %71
%189 = OpLoad %5 %188
%190 = OpExtInst %5 %83 UMin %186 %189
%187 = OpAccessChain %78 %13 %190
%191 = OpLoad %10 %187
%192 = OpAccessChain %74 %8 %88
%193 = OpLoad %5 %192
%194 = OpIAdd %5 %193 %86
%196 = OpExtInst %5 %83 UMin %194 %93
%195 = OpAccessChain %91 %65 %196
%197 = OpLoad %14 %195
%198 = OpSampledImage %96 %191 %197
%200 = OpCompositeConstruct %101 %98 %98
%199 = OpImageSampleExplicitLod %37 %198 %200 Lod %99
%201 = OpCompositeExtract %9 %199 0
%202 = OpCompositeExtract %9 %199 1
%203 = OpCompositeExtract %9 %199 2
%204 = OpCompositeExtract %9 %199 3
%205 = OpIAdd %5 %72 %71
%206 = OpAccessChain %74 %8 %108
%207 = OpLoad %5 %206
%208 = OpIAdd %5 %207 %205
%210 = OpAccessChain %80 %46 %71
%211 = OpLoad %5 %210
%212 = OpExtInst %5 %83 UMin %208 %211
%209 = OpAccessChain %112 %57 %212
%213 = OpBitcast %5 %201
%214 = OpBitcast %5 %202
%215 = OpBitcast %5 %203
%216 = OpBitcast %5 %204
%217 = OpCompositeConstruct %31 %213 %214 %215 %216
%218 = OpAccessChain %119 %209 %71 %72
OpStore %218 %217
OpControlBarrier %88 %88 %121
%219 = OpAccessChain %74 %8 %108
%220 = OpLoad %5 %219
%221 = OpIAdd %5 %220 %205
%223 = OpAccessChain %80 %46 %71
%224 = OpLoad %5 %223
%225 = OpExtInst %5 %83 UMin %221 %224
%222 = OpAccessChain %112 %57 %225
%228 = OpAccessChain %74 %8 %108
%229 = OpLoad %5 %228
%230 = OpIAdd %5 %229 %205
%231 = OpAccessChain %80 %46 %71
%232 = OpLoad %5 %231
%233 = OpExtInst %5 %83 UMin %230 %232
%227 = OpAccessChain %226 %30 %71 %233
%234 = OpLoad %26 %227
%255 = OpFunctionCall %5 %239 %234 %251 %71
OpControlBarrier %88 %88 %121
%257 = OpAccessChain %80 %46 %71
%258 = OpLoad %5 %257
%259 = OpExtInst %5 %83 UMin %72 %258
%256 = OpAccessChain %78 %13 %259
%260 = OpLoad %10 %256
%261 = OpIAdd %5 %72 %111
%263 = OpExtInst %5 %83 UMin %261 %93
%262 = OpAccessChain %91 %17 %263
%264 = OpLoad %14 %262
%265 = OpIAdd %5 %72 %266
%268 = OpAccessChain %80 %46 %71
%269 = OpLoad %5 %268
%270 = OpExtInst %5 %83 UMin %265 %269
%267 = OpAccessChain %148 %21 %270
%271 = OpLoad %18 %267
%272 = OpIAdd %5 %72 %273
%275 = OpAccessChain %80 %46 %71
%276 = OpLoad %5 %275
%277 = OpExtInst %5 %83 UMin %272 %276
%274 = OpAccessChain %177 %25 %277
%278 = OpLoad %22 %274
%279 = OpIAdd %5 %72 %280
%283 = OpAccessChain %80 %46 %71
%284 = OpLoad %5 %283
%285 = OpExtInst %5 %83 UMin %279 %284
%282 = OpAccessChain %281 %36 %285
%287 = OpAccessChain %80 %46 %71
%288 = OpLoad %5 %287
%289 = OpExtInst %5 %83 UMin %279 %288
%286 = OpAccessChain %226 %30 %71 %289
%290 = OpLoad %26 %286
%291 = OpIAdd %5 %72 %292
%295 = OpAccessChain %80 %46 %71
%296 = OpLoad %5 %295
%297 = OpExtInst %5 %83 UMin %291 %296
%294 = OpAccessChain %293 %43 %297
%298 = OpSampledImage %96 %260 %264
%300 = OpCompositeConstruct %101 %98 %98
%299 = OpImageSampleExplicitLod %37 %298 %300 Lod %99
%301 = OpCompositeExtract %9 %299 0
%302 = OpCompositeExtract %9 %299 1
%303 = OpCompositeExtract %9 %299 2
%304 = OpCompositeExtract %9 %299 3
%305 = OpAccessChain %74 %8 %108
%306 = OpLoad %5 %305
%307 = OpIAdd %5 %306 %111
%308 = OpAccessChain %112 %57 %307
%309 = OpBitcast %5 %301
%310 = OpBitcast %5 %302
%311 = OpBitcast %5 %303
%312 = OpBitcast %5 %304
%313 = OpCompositeConstruct %31 %309 %310 %311 %312
%314 = OpAccessChain %119 %308 %71 %72
OpStore %314 %313
OpControlBarrier %88 %88 %121
%316 = OpCompositeConstruct %101 %98 %98
%315 = OpImageSampleExplicitLod %37 %298 %316 Lod %99
%317 = OpCompositeExtract %9 %315 0
%318 = OpCompositeExtract %9 %315 1
%319 = OpCompositeExtract %9 %315 2
%320 = OpCompositeExtract %9 %315 3
%321 = OpCompositeConstruct %26 %72 %71
%322 = OpCompositeConstruct %37 %317 %318 %319 %320
OpImageWrite %271 %321 %322
OpControlBarrier %88 %88 %121
%323 = OpAccessChain %166 %294 %71 %71
%324 = OpLoad %37 %323
%325 = OpCompositeExtract %9 %324 0
%326 = OpCompositeExtract %9 %324 1
%327 = OpCompositeExtract %9 %324 2
%328 = OpCompositeExtract %9 %324 3
%329 = OpCompositeConstruct %37 %325 %326 %327 %328
OpImageWrite %278 %72 %329
OpControlBarrier %88 %88 %121
%331 = OpCompositeConstruct %101 %98 %98
%330 = OpImageSampleExplicitLod %37 %298 %331 Lod %99
%332 = OpCompositeExtract %9 %330 0
%333 = OpCompositeExtract %9 %330 1
%334 = OpCompositeExtract %9 %330 2
%335 = OpCompositeExtract %9 %330 3
%336 = OpBitcast %5 %332
%337 = OpBitcast %5 %333
%338 = OpBitcast %5 %334
%339 = OpBitcast %5 %335
%340 = OpCompositeConstruct %31 %336 %337 %338 %339
%341 = OpAccessChain %119 %282 %71 %72
OpStore %341 %340
OpControlBarrier %88 %88 %121
%342 = OpFunctionCall %5 %239 %290 %251 %71
OpControlBarrier %88 %88 %121
OpReturn
OpFunctionEnd
%239 = OpFunction %5 None %235
%236 = OpFunctionParameter %26
%237 = OpFunctionParameter %5
%238 = OpFunctionParameter %5
%240 = OpLabel
%246 = OpINotEqual %244 %236 %245
%247 = OpAny %243 %246
OpSelectionMerge %242 None
OpBranchConditional %247 %241 %242
%241 = OpLabel
%249 = OpBitcast %248 %236
%250 = OpAtomicIAdd %5 %249 %251 %71 %237
%252 = OpIAdd %5 %250 %238
OpBranch %242
%242 = OpLabel
%253 = OpPhi %5 %71 %240 %252 %241
OpReturnValue %253
OpFunctionEnd
#endif
